// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/adminpb/admin.proto

package adminpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Response int32

const (
	Response_SUCCESS Response = 0
	Response_FAIL    Response = 1
)

var Response_name = map[int32]string{
	0: "SUCCESS",
	1: "FAIL",
}

var Response_value = map[string]int32{
	"SUCCESS": 0,
	"FAIL":    1,
}

func (x Response) String() string {
	return proto.EnumName(Response_name, int32(x))
}

func (Response) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b89f257325c17cfa, []int{0}
}

// AdminClientNewTopic
type AdminClientNewTopicRequest struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	NumPartitions        int32    `protobuf:"varint,2,opt,name=numPartitions,proto3" json:"numPartitions,omitempty"`
	ReplicationFactor    int32    `protobuf:"varint,3,opt,name=replicationFactor,proto3" json:"replicationFactor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminClientNewTopicRequest) Reset()         { *m = AdminClientNewTopicRequest{} }
func (m *AdminClientNewTopicRequest) String() string { return proto.CompactTextString(m) }
func (*AdminClientNewTopicRequest) ProtoMessage()    {}
func (*AdminClientNewTopicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b89f257325c17cfa, []int{0}
}

func (m *AdminClientNewTopicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminClientNewTopicRequest.Unmarshal(m, b)
}
func (m *AdminClientNewTopicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminClientNewTopicRequest.Marshal(b, m, deterministic)
}
func (m *AdminClientNewTopicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminClientNewTopicRequest.Merge(m, src)
}
func (m *AdminClientNewTopicRequest) XXX_Size() int {
	return xxx_messageInfo_AdminClientNewTopicRequest.Size(m)
}
func (m *AdminClientNewTopicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminClientNewTopicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminClientNewTopicRequest proto.InternalMessageInfo

func (m *AdminClientNewTopicRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *AdminClientNewTopicRequest) GetNumPartitions() int32 {
	if m != nil {
		return m.NumPartitions
	}
	return 0
}

func (m *AdminClientNewTopicRequest) GetReplicationFactor() int32 {
	if m != nil {
		return m.ReplicationFactor
	}
	return 0
}

type AdminClientNewTopicResponse struct {
	Response             Response `protobuf:"varint,1,opt,name=response,proto3,enum=proto.adminpb.Response" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminClientNewTopicResponse) Reset()         { *m = AdminClientNewTopicResponse{} }
func (m *AdminClientNewTopicResponse) String() string { return proto.CompactTextString(m) }
func (*AdminClientNewTopicResponse) ProtoMessage()    {}
func (*AdminClientNewTopicResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b89f257325c17cfa, []int{1}
}

func (m *AdminClientNewTopicResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminClientNewTopicResponse.Unmarshal(m, b)
}
func (m *AdminClientNewTopicResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminClientNewTopicResponse.Marshal(b, m, deterministic)
}
func (m *AdminClientNewTopicResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminClientNewTopicResponse.Merge(m, src)
}
func (m *AdminClientNewTopicResponse) XXX_Size() int {
	return xxx_messageInfo_AdminClientNewTopicResponse.Size(m)
}
func (m *AdminClientNewTopicResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminClientNewTopicResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AdminClientNewTopicResponse proto.InternalMessageInfo

func (m *AdminClientNewTopicResponse) GetResponse() Response {
	if m != nil {
		return m.Response
	}
	return Response_SUCCESS
}

// AdminClientNewPartition
type AdminClientNewPartitionRequest struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	PartitionID          []int32  `protobuf:"varint,2,rep,packed,name=partitionID,proto3" json:"partitionID,omitempty"`
	ReplicaID            int32    `protobuf:"varint,3,opt,name=replicaID,proto3" json:"replicaID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminClientNewPartitionRequest) Reset()         { *m = AdminClientNewPartitionRequest{} }
func (m *AdminClientNewPartitionRequest) String() string { return proto.CompactTextString(m) }
func (*AdminClientNewPartitionRequest) ProtoMessage()    {}
func (*AdminClientNewPartitionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b89f257325c17cfa, []int{2}
}

func (m *AdminClientNewPartitionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminClientNewPartitionRequest.Unmarshal(m, b)
}
func (m *AdminClientNewPartitionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminClientNewPartitionRequest.Marshal(b, m, deterministic)
}
func (m *AdminClientNewPartitionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminClientNewPartitionRequest.Merge(m, src)
}
func (m *AdminClientNewPartitionRequest) XXX_Size() int {
	return xxx_messageInfo_AdminClientNewPartitionRequest.Size(m)
}
func (m *AdminClientNewPartitionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminClientNewPartitionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminClientNewPartitionRequest proto.InternalMessageInfo

func (m *AdminClientNewPartitionRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *AdminClientNewPartitionRequest) GetPartitionID() []int32 {
	if m != nil {
		return m.PartitionID
	}
	return nil
}

func (m *AdminClientNewPartitionRequest) GetReplicaID() int32 {
	if m != nil {
		return m.ReplicaID
	}
	return 0
}

type AdminClientNewPartitionResponse struct {
	Response             Response `protobuf:"varint,1,opt,name=response,proto3,enum=proto.adminpb.Response" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminClientNewPartitionResponse) Reset()         { *m = AdminClientNewPartitionResponse{} }
func (m *AdminClientNewPartitionResponse) String() string { return proto.CompactTextString(m) }
func (*AdminClientNewPartitionResponse) ProtoMessage()    {}
func (*AdminClientNewPartitionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b89f257325c17cfa, []int{3}
}

func (m *AdminClientNewPartitionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminClientNewPartitionResponse.Unmarshal(m, b)
}
func (m *AdminClientNewPartitionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminClientNewPartitionResponse.Marshal(b, m, deterministic)
}
func (m *AdminClientNewPartitionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminClientNewPartitionResponse.Merge(m, src)
}
func (m *AdminClientNewPartitionResponse) XXX_Size() int {
	return xxx_messageInfo_AdminClientNewPartitionResponse.Size(m)
}
func (m *AdminClientNewPartitionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminClientNewPartitionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AdminClientNewPartitionResponse proto.InternalMessageInfo

func (m *AdminClientNewPartitionResponse) GetResponse() Response {
	if m != nil {
		return m.Response
	}
	return Response_SUCCESS
}

// LeaderAndIsr
type LeaderAndIsrPartitionState struct {
	TopicName            string   `protobuf:"bytes,1,opt,name=topicName,proto3" json:"topicName,omitempty"`
	PartitionIndex       int32    `protobuf:"varint,2,opt,name=partitionIndex,proto3" json:"partitionIndex,omitempty"`
	Leader               int32    `protobuf:"varint,3,opt,name=leader,proto3" json:"leader,omitempty"`
	Isr                  []int32  `protobuf:"varint,4,rep,packed,name=isr,proto3" json:"isr,omitempty"`
	Replicas             []int32  `protobuf:"varint,5,rep,packed,name=replicas,proto3" json:"replicas,omitempty"`
	AddingReplicas       []int32  `protobuf:"varint,6,rep,packed,name=addingReplicas,proto3" json:"addingReplicas,omitempty"`
	RemovingReplicas     []int32  `protobuf:"varint,7,rep,packed,name=removingReplicas,proto3" json:"removingReplicas,omitempty"`
	IsNew                bool     `protobuf:"varint,8,opt,name=isNew,proto3" json:"isNew,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaderAndIsrPartitionState) Reset()         { *m = LeaderAndIsrPartitionState{} }
func (m *LeaderAndIsrPartitionState) String() string { return proto.CompactTextString(m) }
func (*LeaderAndIsrPartitionState) ProtoMessage()    {}
func (*LeaderAndIsrPartitionState) Descriptor() ([]byte, []int) {
	return fileDescriptor_b89f257325c17cfa, []int{4}
}

func (m *LeaderAndIsrPartitionState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaderAndIsrPartitionState.Unmarshal(m, b)
}
func (m *LeaderAndIsrPartitionState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaderAndIsrPartitionState.Marshal(b, m, deterministic)
}
func (m *LeaderAndIsrPartitionState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaderAndIsrPartitionState.Merge(m, src)
}
func (m *LeaderAndIsrPartitionState) XXX_Size() int {
	return xxx_messageInfo_LeaderAndIsrPartitionState.Size(m)
}
func (m *LeaderAndIsrPartitionState) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaderAndIsrPartitionState.DiscardUnknown(m)
}

var xxx_messageInfo_LeaderAndIsrPartitionState proto.InternalMessageInfo

func (m *LeaderAndIsrPartitionState) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *LeaderAndIsrPartitionState) GetPartitionIndex() int32 {
	if m != nil {
		return m.PartitionIndex
	}
	return 0
}

func (m *LeaderAndIsrPartitionState) GetLeader() int32 {
	if m != nil {
		return m.Leader
	}
	return 0
}

func (m *LeaderAndIsrPartitionState) GetIsr() []int32 {
	if m != nil {
		return m.Isr
	}
	return nil
}

func (m *LeaderAndIsrPartitionState) GetReplicas() []int32 {
	if m != nil {
		return m.Replicas
	}
	return nil
}

func (m *LeaderAndIsrPartitionState) GetAddingReplicas() []int32 {
	if m != nil {
		return m.AddingReplicas
	}
	return nil
}

func (m *LeaderAndIsrPartitionState) GetRemovingReplicas() []int32 {
	if m != nil {
		return m.RemovingReplicas
	}
	return nil
}

func (m *LeaderAndIsrPartitionState) GetIsNew() bool {
	if m != nil {
		return m.IsNew
	}
	return false
}

type LeaderAndIsrTopicState struct {
	TopicName            string                        `protobuf:"bytes,1,opt,name=topicName,proto3" json:"topicName,omitempty"`
	PartitionStates      []*LeaderAndIsrPartitionState `protobuf:"bytes,2,rep,name=partitionStates,proto3" json:"partitionStates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *LeaderAndIsrTopicState) Reset()         { *m = LeaderAndIsrTopicState{} }
func (m *LeaderAndIsrTopicState) String() string { return proto.CompactTextString(m) }
func (*LeaderAndIsrTopicState) ProtoMessage()    {}
func (*LeaderAndIsrTopicState) Descriptor() ([]byte, []int) {
	return fileDescriptor_b89f257325c17cfa, []int{5}
}

func (m *LeaderAndIsrTopicState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaderAndIsrTopicState.Unmarshal(m, b)
}
func (m *LeaderAndIsrTopicState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaderAndIsrTopicState.Marshal(b, m, deterministic)
}
func (m *LeaderAndIsrTopicState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaderAndIsrTopicState.Merge(m, src)
}
func (m *LeaderAndIsrTopicState) XXX_Size() int {
	return xxx_messageInfo_LeaderAndIsrTopicState.Size(m)
}
func (m *LeaderAndIsrTopicState) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaderAndIsrTopicState.DiscardUnknown(m)
}

var xxx_messageInfo_LeaderAndIsrTopicState proto.InternalMessageInfo

func (m *LeaderAndIsrTopicState) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *LeaderAndIsrTopicState) GetPartitionStates() []*LeaderAndIsrPartitionState {
	if m != nil {
		return m.PartitionStates
	}
	return nil
}

type LeaderAndIsrLiveLeader struct {
	BrokerID             int32    `protobuf:"varint,1,opt,name=brokerID,proto3" json:"brokerID,omitempty"`
	HostName             string   `protobuf:"bytes,2,opt,name=hostName,proto3" json:"hostName,omitempty"`
	Port                 int32    `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaderAndIsrLiveLeader) Reset()         { *m = LeaderAndIsrLiveLeader{} }
func (m *LeaderAndIsrLiveLeader) String() string { return proto.CompactTextString(m) }
func (*LeaderAndIsrLiveLeader) ProtoMessage()    {}
func (*LeaderAndIsrLiveLeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_b89f257325c17cfa, []int{6}
}

func (m *LeaderAndIsrLiveLeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaderAndIsrLiveLeader.Unmarshal(m, b)
}
func (m *LeaderAndIsrLiveLeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaderAndIsrLiveLeader.Marshal(b, m, deterministic)
}
func (m *LeaderAndIsrLiveLeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaderAndIsrLiveLeader.Merge(m, src)
}
func (m *LeaderAndIsrLiveLeader) XXX_Size() int {
	return xxx_messageInfo_LeaderAndIsrLiveLeader.Size(m)
}
func (m *LeaderAndIsrLiveLeader) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaderAndIsrLiveLeader.DiscardUnknown(m)
}

var xxx_messageInfo_LeaderAndIsrLiveLeader proto.InternalMessageInfo

func (m *LeaderAndIsrLiveLeader) GetBrokerID() int32 {
	if m != nil {
		return m.BrokerID
	}
	return 0
}

func (m *LeaderAndIsrLiveLeader) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *LeaderAndIsrLiveLeader) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type LeaderAndIsrRequest struct {
	ControllerID         int32                     `protobuf:"varint,1,opt,name=controllerID,proto3" json:"controllerID,omitempty"`
	TopicStates          []*LeaderAndIsrTopicState `protobuf:"bytes,2,rep,name=topicStates,proto3" json:"topicStates,omitempty"`
	LiveLeaders          []*LeaderAndIsrLiveLeader `protobuf:"bytes,3,rep,name=liveLeaders,proto3" json:"liveLeaders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *LeaderAndIsrRequest) Reset()         { *m = LeaderAndIsrRequest{} }
func (m *LeaderAndIsrRequest) String() string { return proto.CompactTextString(m) }
func (*LeaderAndIsrRequest) ProtoMessage()    {}
func (*LeaderAndIsrRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b89f257325c17cfa, []int{7}
}

func (m *LeaderAndIsrRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaderAndIsrRequest.Unmarshal(m, b)
}
func (m *LeaderAndIsrRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaderAndIsrRequest.Marshal(b, m, deterministic)
}
func (m *LeaderAndIsrRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaderAndIsrRequest.Merge(m, src)
}
func (m *LeaderAndIsrRequest) XXX_Size() int {
	return xxx_messageInfo_LeaderAndIsrRequest.Size(m)
}
func (m *LeaderAndIsrRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaderAndIsrRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LeaderAndIsrRequest proto.InternalMessageInfo

func (m *LeaderAndIsrRequest) GetControllerID() int32 {
	if m != nil {
		return m.ControllerID
	}
	return 0
}

func (m *LeaderAndIsrRequest) GetTopicStates() []*LeaderAndIsrTopicState {
	if m != nil {
		return m.TopicStates
	}
	return nil
}

func (m *LeaderAndIsrRequest) GetLiveLeaders() []*LeaderAndIsrLiveLeader {
	if m != nil {
		return m.LiveLeaders
	}
	return nil
}

type LeaderAndIsrResponse struct {
	Response             Response `protobuf:"varint,1,opt,name=response,proto3,enum=proto.adminpb.Response" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LeaderAndIsrResponse) Reset()         { *m = LeaderAndIsrResponse{} }
func (m *LeaderAndIsrResponse) String() string { return proto.CompactTextString(m) }
func (*LeaderAndIsrResponse) ProtoMessage()    {}
func (*LeaderAndIsrResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b89f257325c17cfa, []int{8}
}

func (m *LeaderAndIsrResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LeaderAndIsrResponse.Unmarshal(m, b)
}
func (m *LeaderAndIsrResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LeaderAndIsrResponse.Marshal(b, m, deterministic)
}
func (m *LeaderAndIsrResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LeaderAndIsrResponse.Merge(m, src)
}
func (m *LeaderAndIsrResponse) XXX_Size() int {
	return xxx_messageInfo_LeaderAndIsrResponse.Size(m)
}
func (m *LeaderAndIsrResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LeaderAndIsrResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LeaderAndIsrResponse proto.InternalMessageInfo

func (m *LeaderAndIsrResponse) GetResponse() Response {
	if m != nil {
		return m.Response
	}
	return Response_SUCCESS
}

// UpdateMetadata
type UpdateMetadataPartitionState struct {
	TopicName            string   `protobuf:"bytes,1,opt,name=topicName,proto3" json:"topicName,omitempty"`
	PartitionIndex       int32    `protobuf:"varint,2,opt,name=partitionIndex,proto3" json:"partitionIndex,omitempty"`
	Leader               int32    `protobuf:"varint,3,opt,name=leader,proto3" json:"leader,omitempty"`
	Isr                  []int32  `protobuf:"varint,4,rep,packed,name=isr,proto3" json:"isr,omitempty"`
	Replicas             []int32  `protobuf:"varint,5,rep,packed,name=replicas,proto3" json:"replicas,omitempty"`
	OfflineReplicas      []int32  `protobuf:"varint,6,rep,packed,name=offlineReplicas,proto3" json:"offlineReplicas,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateMetadataPartitionState) Reset()         { *m = UpdateMetadataPartitionState{} }
func (m *UpdateMetadataPartitionState) String() string { return proto.CompactTextString(m) }
func (*UpdateMetadataPartitionState) ProtoMessage()    {}
func (*UpdateMetadataPartitionState) Descriptor() ([]byte, []int) {
	return fileDescriptor_b89f257325c17cfa, []int{9}
}

func (m *UpdateMetadataPartitionState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMetadataPartitionState.Unmarshal(m, b)
}
func (m *UpdateMetadataPartitionState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMetadataPartitionState.Marshal(b, m, deterministic)
}
func (m *UpdateMetadataPartitionState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMetadataPartitionState.Merge(m, src)
}
func (m *UpdateMetadataPartitionState) XXX_Size() int {
	return xxx_messageInfo_UpdateMetadataPartitionState.Size(m)
}
func (m *UpdateMetadataPartitionState) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMetadataPartitionState.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMetadataPartitionState proto.InternalMessageInfo

func (m *UpdateMetadataPartitionState) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *UpdateMetadataPartitionState) GetPartitionIndex() int32 {
	if m != nil {
		return m.PartitionIndex
	}
	return 0
}

func (m *UpdateMetadataPartitionState) GetLeader() int32 {
	if m != nil {
		return m.Leader
	}
	return 0
}

func (m *UpdateMetadataPartitionState) GetIsr() []int32 {
	if m != nil {
		return m.Isr
	}
	return nil
}

func (m *UpdateMetadataPartitionState) GetReplicas() []int32 {
	if m != nil {
		return m.Replicas
	}
	return nil
}

func (m *UpdateMetadataPartitionState) GetOfflineReplicas() []int32 {
	if m != nil {
		return m.OfflineReplicas
	}
	return nil
}

type UpdateMetadataTopicState struct {
	TopicName            string                          `protobuf:"bytes,1,opt,name=topicName,proto3" json:"topicName,omitempty"`
	PartitionStates      []*UpdateMetadataPartitionState `protobuf:"bytes,2,rep,name=partitionStates,proto3" json:"partitionStates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *UpdateMetadataTopicState) Reset()         { *m = UpdateMetadataTopicState{} }
func (m *UpdateMetadataTopicState) String() string { return proto.CompactTextString(m) }
func (*UpdateMetadataTopicState) ProtoMessage()    {}
func (*UpdateMetadataTopicState) Descriptor() ([]byte, []int) {
	return fileDescriptor_b89f257325c17cfa, []int{10}
}

func (m *UpdateMetadataTopicState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMetadataTopicState.Unmarshal(m, b)
}
func (m *UpdateMetadataTopicState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMetadataTopicState.Marshal(b, m, deterministic)
}
func (m *UpdateMetadataTopicState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMetadataTopicState.Merge(m, src)
}
func (m *UpdateMetadataTopicState) XXX_Size() int {
	return xxx_messageInfo_UpdateMetadataTopicState.Size(m)
}
func (m *UpdateMetadataTopicState) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMetadataTopicState.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMetadataTopicState proto.InternalMessageInfo

func (m *UpdateMetadataTopicState) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *UpdateMetadataTopicState) GetPartitionStates() []*UpdateMetadataPartitionState {
	if m != nil {
		return m.PartitionStates
	}
	return nil
}

type UpdateMetadataEndpoint struct {
	Port                 int32    `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateMetadataEndpoint) Reset()         { *m = UpdateMetadataEndpoint{} }
func (m *UpdateMetadataEndpoint) String() string { return proto.CompactTextString(m) }
func (*UpdateMetadataEndpoint) ProtoMessage()    {}
func (*UpdateMetadataEndpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_b89f257325c17cfa, []int{11}
}

func (m *UpdateMetadataEndpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMetadataEndpoint.Unmarshal(m, b)
}
func (m *UpdateMetadataEndpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMetadataEndpoint.Marshal(b, m, deterministic)
}
func (m *UpdateMetadataEndpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMetadataEndpoint.Merge(m, src)
}
func (m *UpdateMetadataEndpoint) XXX_Size() int {
	return xxx_messageInfo_UpdateMetadataEndpoint.Size(m)
}
func (m *UpdateMetadataEndpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMetadataEndpoint.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMetadataEndpoint proto.InternalMessageInfo

func (m *UpdateMetadataEndpoint) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *UpdateMetadataEndpoint) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

type UpdateMetadataBroker struct {
	ID                   int32                     `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Host                 string                    `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32                     `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Endpoints            []*UpdateMetadataEndpoint `protobuf:"bytes,4,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *UpdateMetadataBroker) Reset()         { *m = UpdateMetadataBroker{} }
func (m *UpdateMetadataBroker) String() string { return proto.CompactTextString(m) }
func (*UpdateMetadataBroker) ProtoMessage()    {}
func (*UpdateMetadataBroker) Descriptor() ([]byte, []int) {
	return fileDescriptor_b89f257325c17cfa, []int{12}
}

func (m *UpdateMetadataBroker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMetadataBroker.Unmarshal(m, b)
}
func (m *UpdateMetadataBroker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMetadataBroker.Marshal(b, m, deterministic)
}
func (m *UpdateMetadataBroker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMetadataBroker.Merge(m, src)
}
func (m *UpdateMetadataBroker) XXX_Size() int {
	return xxx_messageInfo_UpdateMetadataBroker.Size(m)
}
func (m *UpdateMetadataBroker) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMetadataBroker.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMetadataBroker proto.InternalMessageInfo

func (m *UpdateMetadataBroker) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *UpdateMetadataBroker) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *UpdateMetadataBroker) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *UpdateMetadataBroker) GetEndpoints() []*UpdateMetadataEndpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

type UpdateMetadatRequest struct {
	ControllerID         int32                       `protobuf:"varint,1,opt,name=controllerID,proto3" json:"controllerID,omitempty"`
	TopicStates          []*UpdateMetadataTopicState `protobuf:"bytes,2,rep,name=topicStates,proto3" json:"topicStates,omitempty"`
	LiveBrokers          []*UpdateMetadataBroker     `protobuf:"bytes,3,rep,name=liveBrokers,proto3" json:"liveBrokers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *UpdateMetadatRequest) Reset()         { *m = UpdateMetadatRequest{} }
func (m *UpdateMetadatRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateMetadatRequest) ProtoMessage()    {}
func (*UpdateMetadatRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b89f257325c17cfa, []int{13}
}

func (m *UpdateMetadatRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMetadatRequest.Unmarshal(m, b)
}
func (m *UpdateMetadatRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMetadatRequest.Marshal(b, m, deterministic)
}
func (m *UpdateMetadatRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMetadatRequest.Merge(m, src)
}
func (m *UpdateMetadatRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateMetadatRequest.Size(m)
}
func (m *UpdateMetadatRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMetadatRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMetadatRequest proto.InternalMessageInfo

func (m *UpdateMetadatRequest) GetControllerID() int32 {
	if m != nil {
		return m.ControllerID
	}
	return 0
}

func (m *UpdateMetadatRequest) GetTopicStates() []*UpdateMetadataTopicState {
	if m != nil {
		return m.TopicStates
	}
	return nil
}

func (m *UpdateMetadatRequest) GetLiveBrokers() []*UpdateMetadataBroker {
	if m != nil {
		return m.LiveBrokers
	}
	return nil
}

type UpdateMetadataResponse struct {
	Response             Response `protobuf:"varint,1,opt,name=response,proto3,enum=proto.adminpb.Response" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateMetadataResponse) Reset()         { *m = UpdateMetadataResponse{} }
func (m *UpdateMetadataResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateMetadataResponse) ProtoMessage()    {}
func (*UpdateMetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b89f257325c17cfa, []int{14}
}

func (m *UpdateMetadataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMetadataResponse.Unmarshal(m, b)
}
func (m *UpdateMetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMetadataResponse.Marshal(b, m, deterministic)
}
func (m *UpdateMetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMetadataResponse.Merge(m, src)
}
func (m *UpdateMetadataResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateMetadataResponse.Size(m)
}
func (m *UpdateMetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMetadataResponse proto.InternalMessageInfo

func (m *UpdateMetadataResponse) GetResponse() Response {
	if m != nil {
		return m.Response
	}
	return Response_SUCCESS
}

func init() {
	proto.RegisterEnum("proto.adminpb.Response", Response_name, Response_value)
	proto.RegisterType((*AdminClientNewTopicRequest)(nil), "proto.adminpb.AdminClientNewTopicRequest")
	proto.RegisterType((*AdminClientNewTopicResponse)(nil), "proto.adminpb.AdminClientNewTopicResponse")
	proto.RegisterType((*AdminClientNewPartitionRequest)(nil), "proto.adminpb.AdminClientNewPartitionRequest")
	proto.RegisterType((*AdminClientNewPartitionResponse)(nil), "proto.adminpb.AdminClientNewPartitionResponse")
	proto.RegisterType((*LeaderAndIsrPartitionState)(nil), "proto.adminpb.LeaderAndIsrPartitionState")
	proto.RegisterType((*LeaderAndIsrTopicState)(nil), "proto.adminpb.LeaderAndIsrTopicState")
	proto.RegisterType((*LeaderAndIsrLiveLeader)(nil), "proto.adminpb.LeaderAndIsrLiveLeader")
	proto.RegisterType((*LeaderAndIsrRequest)(nil), "proto.adminpb.LeaderAndIsrRequest")
	proto.RegisterType((*LeaderAndIsrResponse)(nil), "proto.adminpb.LeaderAndIsrResponse")
	proto.RegisterType((*UpdateMetadataPartitionState)(nil), "proto.adminpb.UpdateMetadataPartitionState")
	proto.RegisterType((*UpdateMetadataTopicState)(nil), "proto.adminpb.UpdateMetadataTopicState")
	proto.RegisterType((*UpdateMetadataEndpoint)(nil), "proto.adminpb.UpdateMetadataEndpoint")
	proto.RegisterType((*UpdateMetadataBroker)(nil), "proto.adminpb.UpdateMetadataBroker")
	proto.RegisterType((*UpdateMetadatRequest)(nil), "proto.adminpb.UpdateMetadatRequest")
	proto.RegisterType((*UpdateMetadataResponse)(nil), "proto.adminpb.UpdateMetadataResponse")
}

func init() {
	proto.RegisterFile("proto/adminpb/admin.proto", fileDescriptor_b89f257325c17cfa)
}

var fileDescriptor_b89f257325c17cfa = []byte{
	// 773 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x56, 0xcb, 0x6e, 0xd3, 0x40,
	0x14, 0xad, 0x93, 0xa6, 0x4d, 0x6f, 0xda, 0x34, 0x4c, 0x4b, 0x6b, 0x42, 0x05, 0x61, 0xca, 0x23,
	0x14, 0x48, 0xa5, 0xf6, 0x07, 0x48, 0x93, 0x16, 0x59, 0x7d, 0x08, 0x4d, 0x28, 0x12, 0x2c, 0x90,
	0xdc, 0x78, 0x0a, 0x16, 0x8e, 0xc7, 0x8c, 0xa7, 0x29, 0xe2, 0x03, 0xd8, 0xb0, 0x40, 0x82, 0x6f,
	0xe1, 0x2b, 0x60, 0xc9, 0x07, 0x21, 0x8f, 0xdf, 0x4e, 0x62, 0x82, 0xba, 0x61, 0xe5, 0xb9, 0xd7,
	0xf7, 0x71, 0xce, 0x7d, 0x8c, 0x0d, 0x37, 0x1c, 0xce, 0x04, 0xdb, 0xd6, 0x8d, 0x81, 0x69, 0x3b,
	0x67, 0xfe, 0xb3, 0x25, 0x75, 0x68, 0x49, 0x3e, 0x5a, 0xc1, 0x2b, 0xfc, 0x59, 0x81, 0x7a, 0xdb,
	0x3b, 0x77, 0x2c, 0x93, 0xda, 0xe2, 0x84, 0x5e, 0xbe, 0x60, 0x8e, 0xd9, 0x27, 0xf4, 0xc3, 0x05,
	0x75, 0x05, 0x5a, 0x85, 0x92, 0xf0, 0x64, 0x55, 0x69, 0x28, 0xcd, 0x05, 0xe2, 0x0b, 0xe8, 0x2e,
	0x2c, 0xd9, 0x17, 0x83, 0xe7, 0x3a, 0x17, 0xa6, 0x30, 0x99, 0xed, 0xaa, 0x85, 0x86, 0xd2, 0x2c,
	0x91, 0xb4, 0x12, 0x3d, 0x86, 0x6b, 0x9c, 0x3a, 0x96, 0xd9, 0xd7, 0x3d, 0xf9, 0x40, 0xef, 0x0b,
	0xc6, 0xd5, 0xa2, 0xb4, 0x1c, 0x7d, 0x81, 0x09, 0xdc, 0x1c, 0x8b, 0xc3, 0x75, 0x98, 0xed, 0x52,
	0xb4, 0x0b, 0x65, 0x1e, 0x9c, 0x25, 0x96, 0xea, 0xce, 0x7a, 0x2b, 0xc5, 0xa4, 0x15, 0x9a, 0x92,
	0xc8, 0x10, 0x0f, 0xe1, 0x56, 0x3a, 0x66, 0x84, 0x2e, 0x9f, 0x5f, 0x03, 0x2a, 0x4e, 0x68, 0xa9,
	0x75, 0xd5, 0x42, 0xa3, 0xd8, 0x2c, 0x91, 0xa4, 0x0a, 0x6d, 0xc0, 0x42, 0x40, 0x41, 0xeb, 0x06,
	0x9c, 0x62, 0x05, 0x7e, 0x09, 0xb7, 0x27, 0xe6, 0xbd, 0x0a, 0x9f, 0x6f, 0x05, 0xa8, 0x1f, 0x51,
	0xdd, 0xa0, 0xbc, 0x6d, 0x1b, 0x9a, 0xcb, 0xa3, 0xb0, 0x3d, 0xa1, 0x0b, 0xea, 0x81, 0x92, 0xf8,
	0x4f, 0xf4, 0x01, 0x0d, 0x08, 0xc5, 0x0a, 0x74, 0x1f, 0xaa, 0x31, 0x03, 0xdb, 0xa0, 0x1f, 0x83,
	0xae, 0x65, 0xb4, 0x68, 0x0d, 0xe6, 0x2c, 0x99, 0x23, 0xe0, 0x15, 0x48, 0xa8, 0x06, 0x45, 0xd3,
	0xe5, 0xea, 0xac, 0x2c, 0x86, 0x77, 0x44, 0x75, 0x8f, 0x83, 0xe4, 0xec, 0xaa, 0x25, 0xa9, 0x8e,
	0x64, 0x2f, 0x9b, 0x6e, 0x18, 0xa6, 0xfd, 0x96, 0x84, 0x16, 0x73, 0xd2, 0x22, 0xa3, 0x45, 0x5b,
	0x50, 0xe3, 0x74, 0xc0, 0x86, 0x49, 0xcb, 0x79, 0x69, 0x39, 0xa2, 0xf7, 0x9a, 0x65, 0xba, 0x27,
	0xf4, 0x52, 0x2d, 0x37, 0x94, 0x66, 0x99, 0xf8, 0x02, 0xfe, 0xa2, 0xc0, 0x5a, 0xb2, 0x28, 0x72,
	0x6e, 0xa6, 0x29, 0x48, 0x0f, 0x96, 0x9d, 0x54, 0x01, 0x5d, 0xd9, 0xe9, 0xca, 0xce, 0xc3, 0x4c,
	0x27, 0x26, 0x97, 0x9c, 0x64, 0x23, 0x60, 0x23, 0x0d, 0xe6, 0xc8, 0x1c, 0x52, 0x5f, 0xf6, 0xaa,
	0x75, 0xc6, 0xd9, 0x7b, 0xca, 0xb5, 0xae, 0xc4, 0x52, 0x22, 0x91, 0xec, 0xbd, 0x7b, 0xc7, 0x5c,
	0x21, 0x71, 0x16, 0x24, 0xce, 0x48, 0x46, 0x08, 0x66, 0x1d, 0xc6, 0x45, 0xd0, 0x0d, 0x79, 0xc6,
	0x3f, 0x15, 0x58, 0x49, 0xa6, 0x09, 0xc7, 0x19, 0xc3, 0x62, 0x9f, 0xd9, 0x82, 0x33, 0xcb, 0x4a,
	0xe4, 0x49, 0xe9, 0xd0, 0x33, 0xa8, 0x88, 0xa8, 0x44, 0x21, 0xe5, 0x7b, 0x39, 0x94, 0xe3, 0x82,
	0x92, 0xa4, 0xa7, 0x17, 0xc8, 0x8a, 0xe8, 0xb9, 0x6a, 0xf1, 0xaf, 0x81, 0xe2, 0x62, 0x90, 0xa4,
	0x27, 0x3e, 0x84, 0xd5, 0x34, 0x99, 0xab, 0xec, 0xc8, 0x6f, 0x05, 0x36, 0x4e, 0x1d, 0x43, 0x17,
	0xf4, 0x98, 0x0a, 0xdd, 0xd0, 0x85, 0xfe, 0x1f, 0x6f, 0x49, 0x13, 0x96, 0xd9, 0xf9, 0xb9, 0x65,
	0xda, 0x34, 0xb3, 0x26, 0x59, 0x35, 0xfe, 0xaa, 0x80, 0x9a, 0xa6, 0x35, 0xf5, 0x9c, 0x9f, 0x4e,
	0x9a, 0xf3, 0x47, 0x99, 0x6a, 0xe6, 0x95, 0x6d, 0x74, 0xd2, 0x9f, 0xc2, 0x5a, 0xda, 0x61, 0xdf,
	0x36, 0x1c, 0x66, 0xda, 0x22, 0x9a, 0x58, 0x25, 0x9e, 0x58, 0x4f, 0xe7, 0x4d, 0x74, 0x30, 0xdd,
	0xf2, 0x8c, 0xbf, 0x2b, 0xb0, 0x9a, 0x0e, 0xb1, 0x27, 0x17, 0x02, 0x55, 0xa1, 0x10, 0x0d, 0x6f,
	0x41, 0xeb, 0x8e, 0x73, 0x1e, 0xb7, 0x16, 0xa8, 0x03, 0x0b, 0x34, 0x00, 0xe1, 0xca, 0x16, 0x8c,
	0xce, 0xe3, 0x78, 0xc8, 0x24, 0xf6, 0xc3, 0xbf, 0xb2, 0xa8, 0xfe, 0x65, 0xb9, 0xb4, 0x71, 0xcb,
	0xf5, 0x20, 0x17, 0xc3, 0xa4, 0xf5, 0xda, 0xf7, 0xd7, 0xcb, 0x2f, 0x49, 0xb8, 0x5e, 0x9b, 0xb9,
	0xa1, 0x7c, 0x5b, 0x92, 0xf4, 0xc3, 0xc7, 0xd9, 0x36, 0x5d, 0x69, 0xbd, 0xb6, 0xee, 0x40, 0x39,
	0x0a, 0x50, 0x81, 0xf9, 0xde, 0x69, 0xa7, 0xb3, 0xdf, 0xeb, 0xd5, 0x66, 0x50, 0x19, 0x66, 0x0f,
	0xda, 0xda, 0x51, 0x4d, 0xd9, 0xf9, 0x51, 0x84, 0x45, 0xf9, 0xf9, 0xeb, 0x51, 0x3e, 0x34, 0xfb,
	0x14, 0xd9, 0xb0, 0x32, 0xe6, 0xd3, 0x8e, 0xb2, 0xd7, 0xec, 0xe4, 0xdf, 0x90, 0xfa, 0xd6, 0x34,
	0xa6, 0xc1, 0x05, 0x30, 0x83, 0x3e, 0xc1, 0xfa, 0x84, 0xcf, 0x2f, 0x7a, 0x92, 0x1b, 0x28, 0xfb,
	0x7b, 0x50, 0x6f, 0x4d, 0x6b, 0x1e, 0xe5, 0x7e, 0x05, 0x8b, 0xc9, 0xbb, 0x0c, 0xe1, 0x9c, 0xfb,
	0x30, 0xcc, 0xb2, 0x99, 0x6b, 0x13, 0x85, 0x7e, 0x03, 0xd5, 0x74, 0x27, 0x51, 0xee, 0x34, 0x84,
	0xd1, 0xf3, 0x37, 0x20, 0x8e, 0xbf, 0x77, 0xfd, 0xf5, 0x4a, 0xfb, 0xf0, 0xa0, 0x7d, 0xb8, 0x9d,
	0xfa, 0x79, 0x3c, 0x9b, 0x93, 0xe2, 0xee, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdd, 0x8a, 0x51,
	0xdc, 0x54, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AdminServiceClient interface {
	AdminClientNewTopic(ctx context.Context, in *AdminClientNewTopicRequest, opts ...grpc.CallOption) (*AdminClientNewTopicResponse, error)
	AdminClientNewPartition(ctx context.Context, in *AdminClientNewPartitionRequest, opts ...grpc.CallOption) (*AdminClientNewPartitionResponse, error)
	LeaderAndIsr(ctx context.Context, in *LeaderAndIsrRequest, opts ...grpc.CallOption) (*LeaderAndIsrResponse, error)
	UpdateMetadata(ctx context.Context, in *UpdateMetadatRequest, opts ...grpc.CallOption) (*UpdateMetadataResponse, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) AdminClientNewTopic(ctx context.Context, in *AdminClientNewTopicRequest, opts ...grpc.CallOption) (*AdminClientNewTopicResponse, error) {
	out := new(AdminClientNewTopicResponse)
	err := c.cc.Invoke(ctx, "/proto.adminpb.AdminService/AdminClientNewTopic", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) AdminClientNewPartition(ctx context.Context, in *AdminClientNewPartitionRequest, opts ...grpc.CallOption) (*AdminClientNewPartitionResponse, error) {
	out := new(AdminClientNewPartitionResponse)
	err := c.cc.Invoke(ctx, "/proto.adminpb.AdminService/AdminClientNewPartition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) LeaderAndIsr(ctx context.Context, in *LeaderAndIsrRequest, opts ...grpc.CallOption) (*LeaderAndIsrResponse, error) {
	out := new(LeaderAndIsrResponse)
	err := c.cc.Invoke(ctx, "/proto.adminpb.AdminService/LeaderAndIsr", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) UpdateMetadata(ctx context.Context, in *UpdateMetadatRequest, opts ...grpc.CallOption) (*UpdateMetadataResponse, error) {
	out := new(UpdateMetadataResponse)
	err := c.cc.Invoke(ctx, "/proto.adminpb.AdminService/UpdateMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
type AdminServiceServer interface {
	AdminClientNewTopic(context.Context, *AdminClientNewTopicRequest) (*AdminClientNewTopicResponse, error)
	AdminClientNewPartition(context.Context, *AdminClientNewPartitionRequest) (*AdminClientNewPartitionResponse, error)
	LeaderAndIsr(context.Context, *LeaderAndIsrRequest) (*LeaderAndIsrResponse, error)
	UpdateMetadata(context.Context, *UpdateMetadatRequest) (*UpdateMetadataResponse, error)
}

// UnimplementedAdminServiceServer can be embedded to have forward compatible implementations.
type UnimplementedAdminServiceServer struct {
}

func (*UnimplementedAdminServiceServer) AdminClientNewTopic(ctx context.Context, req *AdminClientNewTopicRequest) (*AdminClientNewTopicResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminClientNewTopic not implemented")
}
func (*UnimplementedAdminServiceServer) AdminClientNewPartition(ctx context.Context, req *AdminClientNewPartitionRequest) (*AdminClientNewPartitionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminClientNewPartition not implemented")
}
func (*UnimplementedAdminServiceServer) LeaderAndIsr(ctx context.Context, req *LeaderAndIsrRequest) (*LeaderAndIsrResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LeaderAndIsr not implemented")
}
func (*UnimplementedAdminServiceServer) UpdateMetadata(ctx context.Context, req *UpdateMetadatRequest) (*UpdateMetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateMetadata not implemented")
}

func RegisterAdminServiceServer(s *grpc.Server, srv AdminServiceServer) {
	s.RegisterService(&_AdminService_serviceDesc, srv)
}

func _AdminService_AdminClientNewTopic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminClientNewTopicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).AdminClientNewTopic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.adminpb.AdminService/AdminClientNewTopic",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).AdminClientNewTopic(ctx, req.(*AdminClientNewTopicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_AdminClientNewPartition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminClientNewPartitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).AdminClientNewPartition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.adminpb.AdminService/AdminClientNewPartition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).AdminClientNewPartition(ctx, req.(*AdminClientNewPartitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_LeaderAndIsr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaderAndIsrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).LeaderAndIsr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.adminpb.AdminService/LeaderAndIsr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).LeaderAndIsr(ctx, req.(*LeaderAndIsrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_UpdateMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMetadatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).UpdateMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.adminpb.AdminService/UpdateMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).UpdateMetadata(ctx, req.(*UpdateMetadatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AdminService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.adminpb.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AdminClientNewTopic",
			Handler:    _AdminService_AdminClientNewTopic_Handler,
		},
		{
			MethodName: "AdminClientNewPartition",
			Handler:    _AdminService_AdminClientNewPartition_Handler,
		},
		{
			MethodName: "LeaderAndIsr",
			Handler:    _AdminService_LeaderAndIsr_Handler,
		},
		{
			MethodName: "UpdateMetadata",
			Handler:    _AdminService_UpdateMetadata_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/adminpb/admin.proto",
}
