// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/zkmessagepb/cluster_metadata.proto

package zkmessagepb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MetadataPartitionState struct {
	TopicName            string   `protobuf:"bytes,1,opt,name=topicName,proto3" json:"topicName,omitempty"`
	PartitionIndex       int32    `protobuf:"varint,2,opt,name=partitionIndex,proto3" json:"partitionIndex,omitempty"`
	Leader               int32    `protobuf:"varint,3,opt,name=leader,proto3" json:"leader,omitempty"`
	Isr                  []int32  `protobuf:"varint,4,rep,packed,name=isr,proto3" json:"isr,omitempty"`
	Replicas             []int32  `protobuf:"varint,5,rep,packed,name=replicas,proto3" json:"replicas,omitempty"`
	OfflineReplicas      []int32  `protobuf:"varint,6,rep,packed,name=offlineReplicas,proto3" json:"offlineReplicas,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetadataPartitionState) Reset()         { *m = MetadataPartitionState{} }
func (m *MetadataPartitionState) String() string { return proto.CompactTextString(m) }
func (*MetadataPartitionState) ProtoMessage()    {}
func (*MetadataPartitionState) Descriptor() ([]byte, []int) {
	return fileDescriptor_a57440a646d706ac, []int{0}
}

func (m *MetadataPartitionState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetadataPartitionState.Unmarshal(m, b)
}
func (m *MetadataPartitionState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetadataPartitionState.Marshal(b, m, deterministic)
}
func (m *MetadataPartitionState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetadataPartitionState.Merge(m, src)
}
func (m *MetadataPartitionState) XXX_Size() int {
	return xxx_messageInfo_MetadataPartitionState.Size(m)
}
func (m *MetadataPartitionState) XXX_DiscardUnknown() {
	xxx_messageInfo_MetadataPartitionState.DiscardUnknown(m)
}

var xxx_messageInfo_MetadataPartitionState proto.InternalMessageInfo

func (m *MetadataPartitionState) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *MetadataPartitionState) GetPartitionIndex() int32 {
	if m != nil {
		return m.PartitionIndex
	}
	return 0
}

func (m *MetadataPartitionState) GetLeader() int32 {
	if m != nil {
		return m.Leader
	}
	return 0
}

func (m *MetadataPartitionState) GetIsr() []int32 {
	if m != nil {
		return m.Isr
	}
	return nil
}

func (m *MetadataPartitionState) GetReplicas() []int32 {
	if m != nil {
		return m.Replicas
	}
	return nil
}

func (m *MetadataPartitionState) GetOfflineReplicas() []int32 {
	if m != nil {
		return m.OfflineReplicas
	}
	return nil
}

type MetadataTopicState struct {
	TopicName            string                    `protobuf:"bytes,1,opt,name=topicName,proto3" json:"topicName,omitempty"`
	PartitionStates      []*MetadataPartitionState `protobuf:"bytes,2,rep,name=partitionStates,proto3" json:"partitionStates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *MetadataTopicState) Reset()         { *m = MetadataTopicState{} }
func (m *MetadataTopicState) String() string { return proto.CompactTextString(m) }
func (*MetadataTopicState) ProtoMessage()    {}
func (*MetadataTopicState) Descriptor() ([]byte, []int) {
	return fileDescriptor_a57440a646d706ac, []int{1}
}

func (m *MetadataTopicState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetadataTopicState.Unmarshal(m, b)
}
func (m *MetadataTopicState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetadataTopicState.Marshal(b, m, deterministic)
}
func (m *MetadataTopicState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetadataTopicState.Merge(m, src)
}
func (m *MetadataTopicState) XXX_Size() int {
	return xxx_messageInfo_MetadataTopicState.Size(m)
}
func (m *MetadataTopicState) XXX_DiscardUnknown() {
	xxx_messageInfo_MetadataTopicState.DiscardUnknown(m)
}

var xxx_messageInfo_MetadataTopicState proto.InternalMessageInfo

func (m *MetadataTopicState) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *MetadataTopicState) GetPartitionStates() []*MetadataPartitionState {
	if m != nil {
		return m.PartitionStates
	}
	return nil
}

type MetadataBroker struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32    `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetadataBroker) Reset()         { *m = MetadataBroker{} }
func (m *MetadataBroker) String() string { return proto.CompactTextString(m) }
func (*MetadataBroker) ProtoMessage()    {}
func (*MetadataBroker) Descriptor() ([]byte, []int) {
	return fileDescriptor_a57440a646d706ac, []int{2}
}

func (m *MetadataBroker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetadataBroker.Unmarshal(m, b)
}
func (m *MetadataBroker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetadataBroker.Marshal(b, m, deterministic)
}
func (m *MetadataBroker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetadataBroker.Merge(m, src)
}
func (m *MetadataBroker) XXX_Size() int {
	return xxx_messageInfo_MetadataBroker.Size(m)
}
func (m *MetadataBroker) XXX_DiscardUnknown() {
	xxx_messageInfo_MetadataBroker.DiscardUnknown(m)
}

var xxx_messageInfo_MetadataBroker proto.InternalMessageInfo

func (m *MetadataBroker) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *MetadataBroker) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *MetadataBroker) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type MetadataCluster struct {
	LiveBrokers          []*MetadataBroker     `protobuf:"bytes,1,rep,name=liveBrokers,proto3" json:"liveBrokers,omitempty"`
	TopicStates          []*MetadataTopicState `protobuf:"bytes,2,rep,name=topicStates,proto3" json:"topicStates,omitempty"`
	Brokers              []*MetadataBroker     `protobuf:"bytes,3,rep,name=brokers,proto3" json:"brokers,omitempty"`
	Controller           *MetadataBroker       `protobuf:"bytes,4,opt,name=controller,proto3" json:"controller,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *MetadataCluster) Reset()         { *m = MetadataCluster{} }
func (m *MetadataCluster) String() string { return proto.CompactTextString(m) }
func (*MetadataCluster) ProtoMessage()    {}
func (*MetadataCluster) Descriptor() ([]byte, []int) {
	return fileDescriptor_a57440a646d706ac, []int{3}
}

func (m *MetadataCluster) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetadataCluster.Unmarshal(m, b)
}
func (m *MetadataCluster) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetadataCluster.Marshal(b, m, deterministic)
}
func (m *MetadataCluster) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetadataCluster.Merge(m, src)
}
func (m *MetadataCluster) XXX_Size() int {
	return xxx_messageInfo_MetadataCluster.Size(m)
}
func (m *MetadataCluster) XXX_DiscardUnknown() {
	xxx_messageInfo_MetadataCluster.DiscardUnknown(m)
}

var xxx_messageInfo_MetadataCluster proto.InternalMessageInfo

func (m *MetadataCluster) GetLiveBrokers() []*MetadataBroker {
	if m != nil {
		return m.LiveBrokers
	}
	return nil
}

func (m *MetadataCluster) GetTopicStates() []*MetadataTopicState {
	if m != nil {
		return m.TopicStates
	}
	return nil
}

func (m *MetadataCluster) GetBrokers() []*MetadataBroker {
	if m != nil {
		return m.Brokers
	}
	return nil
}

func (m *MetadataCluster) GetController() *MetadataBroker {
	if m != nil {
		return m.Controller
	}
	return nil
}

func init() {
	proto.RegisterType((*MetadataPartitionState)(nil), "proto.zkmessagepb.MetadataPartitionState")
	proto.RegisterType((*MetadataTopicState)(nil), "proto.zkmessagepb.MetadataTopicState")
	proto.RegisterType((*MetadataBroker)(nil), "proto.zkmessagepb.MetadataBroker")
	proto.RegisterType((*MetadataCluster)(nil), "proto.zkmessagepb.MetadataCluster")
}

func init() {
	proto.RegisterFile("proto/zkmessagepb/cluster_metadata.proto", fileDescriptor_a57440a646d706ac)
}

var fileDescriptor_a57440a646d706ac = []byte{
	// 379 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xcd, 0x4e, 0xea, 0x40,
	0x18, 0x4d, 0x5b, 0xca, 0xbd, 0x7c, 0x24, 0x70, 0xef, 0xb7, 0xc0, 0x6a, 0x5c, 0xd4, 0x26, 0x9a,
	0xba, 0x29, 0x89, 0x2e, 0x5d, 0xf1, 0x13, 0x95, 0x10, 0x8d, 0x19, 0x5c, 0xb9, 0x31, 0x43, 0x19,
	0xb4, 0xa1, 0x74, 0x9a, 0x99, 0xd1, 0x18, 0x5f, 0xc0, 0xc7, 0xf0, 0x8d, 0x7c, 0x26, 0xd3, 0xa1,
	0x85, 0x0a, 0x86, 0xb0, 0xea, 0x37, 0xa7, 0xe7, 0x7c, 0x3d, 0xe7, 0xb4, 0x05, 0x3f, 0x15, 0x5c,
	0xf1, 0xf6, 0xfb, 0x6c, 0xce, 0xa4, 0xa4, 0x4f, 0x2c, 0x1d, 0xb7, 0xc3, 0xf8, 0x45, 0x2a, 0x26,
	0x1e, 0xe7, 0x4c, 0xd1, 0x09, 0x55, 0x34, 0xd0, 0x14, 0xfc, 0xaf, 0x2f, 0x41, 0x89, 0xe9, 0x7d,
	0x19, 0xd0, 0xba, 0xc9, 0x59, 0x77, 0x54, 0xa8, 0x48, 0x45, 0x3c, 0x19, 0x29, 0xaa, 0x18, 0x1e,
	0x42, 0x4d, 0xf1, 0x34, 0x0a, 0x6f, 0xe9, 0x9c, 0x39, 0x86, 0x6b, 0xf8, 0x35, 0xb2, 0x02, 0xf0,
	0x04, 0x1a, 0x69, 0xc1, 0x1f, 0x24, 0x13, 0xf6, 0xe6, 0x98, 0xae, 0xe1, 0xdb, 0x64, 0x0d, 0xc5,
	0x16, 0x54, 0x63, 0x46, 0x27, 0x4c, 0x38, 0x96, 0xbe, 0x9f, 0x9f, 0xf0, 0x1f, 0x58, 0x91, 0x14,
	0x4e, 0xc5, 0xb5, 0x7c, 0x9b, 0x64, 0x23, 0x1e, 0xc0, 0x5f, 0xc1, 0xd2, 0x38, 0x0a, 0xa9, 0x74,
	0x6c, 0x0d, 0x2f, 0xcf, 0xe8, 0x43, 0x93, 0x4f, 0xa7, 0x71, 0x94, 0x30, 0x52, 0x50, 0xaa, 0x9a,
	0xb2, 0x0e, 0x7b, 0x1f, 0x06, 0x60, 0x11, 0xe8, 0x3e, 0x73, 0xbb, 0x4b, 0x98, 0x11, 0x34, 0xd3,
	0x1f, 0xe1, 0xa5, 0x63, 0xba, 0x96, 0x5f, 0x3f, 0x3b, 0x0d, 0x36, 0x2a, 0x0b, 0x7e, 0xaf, 0x8b,
	0xac, 0x6f, 0xf0, 0xae, 0xa1, 0x51, 0x50, 0xbb, 0x82, 0xcf, 0x98, 0xc0, 0x06, 0x98, 0x83, 0xbe,
	0x7e, 0xba, 0x4d, 0xcc, 0x41, 0x1f, 0x11, 0x2a, 0xcf, 0x5c, 0x2a, 0xdd, 0x5c, 0x8d, 0xe8, 0x39,
	0xc3, 0x52, 0x2e, 0x54, 0xde, 0x96, 0x9e, 0xbd, 0x4f, 0x13, 0x9a, 0xc5, 0xaa, 0xde, 0xe2, 0xd5,
	0x62, 0x0f, 0xea, 0x71, 0xf4, 0xca, 0x16, 0x9b, 0xa5, 0x63, 0x68, 0xbb, 0x47, 0x5b, 0xec, 0x2e,
	0x98, 0xa4, 0xac, 0xc2, 0x2b, 0xa8, 0xab, 0x65, 0x47, 0x45, 0xe6, 0xe3, 0x2d, 0x4b, 0x56, 0x8d,
	0x92, 0xb2, 0x12, 0x2f, 0xe0, 0xcf, 0x38, 0x77, 0x62, 0xed, 0xea, 0xa4, 0x50, 0x60, 0x07, 0x20,
	0xe4, 0x89, 0x12, 0x3c, 0x8e, 0x59, 0xf6, 0x45, 0x18, 0xbb, 0xe9, 0x4b, 0xa2, 0xee, 0xfe, 0xc3,
	0x5e, 0x67, 0x78, 0xd9, 0x19, 0xb6, 0x37, 0xfe, 0x85, 0x71, 0x55, 0x43, 0xe7, 0xdf, 0x01, 0x00,
	0x00, 0xff, 0xff, 0x02, 0x39, 0xc8, 0x72, 0x27, 0x03, 0x00, 0x00,
}
