// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/zkmessagepb/get_consumer_metadata.proto

package zkmessagepb

import (
	clustermetadatapb "AKFAK/proto/clustermetadatapb"
	consumermetadatapb "AKFAK/proto/consumermetadatapb"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetConsumerMetadataRequest struct {
	Broker               *clustermetadatapb.MetadataBroker `protobuf:"bytes,1,opt,name=broker,proto3" json:"broker,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *GetConsumerMetadataRequest) Reset()         { *m = GetConsumerMetadataRequest{} }
func (m *GetConsumerMetadataRequest) String() string { return proto.CompactTextString(m) }
func (*GetConsumerMetadataRequest) ProtoMessage()    {}
func (*GetConsumerMetadataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a02edacd3c7e42d, []int{0}
}

func (m *GetConsumerMetadataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConsumerMetadataRequest.Unmarshal(m, b)
}
func (m *GetConsumerMetadataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConsumerMetadataRequest.Marshal(b, m, deterministic)
}
func (m *GetConsumerMetadataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConsumerMetadataRequest.Merge(m, src)
}
func (m *GetConsumerMetadataRequest) XXX_Size() int {
	return xxx_messageInfo_GetConsumerMetadataRequest.Size(m)
}
func (m *GetConsumerMetadataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConsumerMetadataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConsumerMetadataRequest proto.InternalMessageInfo

func (m *GetConsumerMetadataRequest) GetBroker() *clustermetadatapb.MetadataBroker {
	if m != nil {
		return m.Broker
	}
	return nil
}

type GetConsumerMetadataResponse struct {
	ConsumerMetadata     *consumermetadatapb.MetadataConsumerState `protobuf:"bytes,1,opt,name=consumerMetadata,proto3" json:"consumerMetadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *GetConsumerMetadataResponse) Reset()         { *m = GetConsumerMetadataResponse{} }
func (m *GetConsumerMetadataResponse) String() string { return proto.CompactTextString(m) }
func (*GetConsumerMetadataResponse) ProtoMessage()    {}
func (*GetConsumerMetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1a02edacd3c7e42d, []int{1}
}

func (m *GetConsumerMetadataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConsumerMetadataResponse.Unmarshal(m, b)
}
func (m *GetConsumerMetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConsumerMetadataResponse.Marshal(b, m, deterministic)
}
func (m *GetConsumerMetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConsumerMetadataResponse.Merge(m, src)
}
func (m *GetConsumerMetadataResponse) XXX_Size() int {
	return xxx_messageInfo_GetConsumerMetadataResponse.Size(m)
}
func (m *GetConsumerMetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConsumerMetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetConsumerMetadataResponse proto.InternalMessageInfo

func (m *GetConsumerMetadataResponse) GetConsumerMetadata() *consumermetadatapb.MetadataConsumerState {
	if m != nil {
		return m.ConsumerMetadata
	}
	return nil
}

func init() {
	proto.RegisterType((*GetConsumerMetadataRequest)(nil), "proto.zkmessagepb.GetConsumerMetadataRequest")
	proto.RegisterType((*GetConsumerMetadataResponse)(nil), "proto.zkmessagepb.GetConsumerMetadataResponse")
}

func init() {
	proto.RegisterFile("proto/zkmessagepb/get_consumer_metadata.proto", fileDescriptor_1a02edacd3c7e42d)
}

var fileDescriptor_1a02edacd3c7e42d = []byte{
	// 213 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xaf, 0xca, 0xce, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x2d, 0x48, 0xd2, 0x4f, 0x4f,
	0x2d, 0x89, 0x4f, 0xce, 0xcf, 0x2b, 0x2e, 0xcd, 0x4d, 0x2d, 0x8a, 0xcf, 0x4d, 0x2d, 0x49, 0x4c,
	0x49, 0x2c, 0x49, 0xd4, 0x03, 0xab, 0x13, 0x12, 0x04, 0x53, 0x7a, 0x48, 0xca, 0xa5, 0x20, 0x32,
	0xfa, 0xc9, 0x39, 0xa5, 0xc5, 0x25, 0xa9, 0x45, 0x30, 0xf5, 0x05, 0x49, 0x30, 0x11, 0x34, 0x23,
	0xa4, 0x0c, 0xa0, 0xea, 0xa1, 0x36, 0x20, 0x6b, 0xc0, 0x6e, 0xa9, 0x52, 0x2c, 0x97, 0x94, 0x7b,
	0x6a, 0x89, 0x33, 0x54, 0xd6, 0x17, 0x2a, 0x19, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x22, 0x64,
	0xcf, 0xc5, 0x96, 0x54, 0x94, 0x9f, 0x9d, 0x5a, 0x24, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x6d, 0xa4,
	0x0e, 0xd1, 0xa5, 0x87, 0xe1, 0x20, 0x3d, 0x98, 0x4e, 0x27, 0xb0, 0xf2, 0x20, 0xa8, 0x36, 0xa5,
	0x2a, 0x2e, 0x69, 0xac, 0xc6, 0x17, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x45, 0x73, 0x09, 0x24,
	0xa3, 0xc9, 0x41, 0x6d, 0xd2, 0x87, 0xd9, 0x84, 0xe1, 0x15, 0xb8, 0x55, 0x30, 0x53, 0x83, 0x4b,
	0x12, 0x4b, 0x52, 0x83, 0x30, 0x0c, 0x72, 0x92, 0x8c, 0x12, 0x77, 0xf4, 0x76, 0x73, 0xf4, 0xd6,
	0xc7, 0x88, 0x86, 0x24, 0x36, 0xb0, 0x90, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x5e, 0x83, 0x99,
	0x06, 0xa2, 0x01, 0x00, 0x00,
}
