// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/zkmessagepb/update_consumer_metadata.proto

package zkmessagepb

import (
	commonpb "AKFAK/proto/commonpb"
	consumermetadatapb "AKFAK/proto/consumermetadatapb"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpdateConsumerMetadataRequest struct {
	NewState             *consumermetadatapb.MetadataConsumerState `protobuf:"bytes,1,opt,name=newState,proto3" json:"newState,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                  `json:"-"`
	XXX_unrecognized     []byte                                    `json:"-"`
	XXX_sizecache        int32                                     `json:"-"`
}

func (m *UpdateConsumerMetadataRequest) Reset()         { *m = UpdateConsumerMetadataRequest{} }
func (m *UpdateConsumerMetadataRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateConsumerMetadataRequest) ProtoMessage()    {}
func (*UpdateConsumerMetadataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3f1f58b4b02e2ad, []int{0}
}

func (m *UpdateConsumerMetadataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateConsumerMetadataRequest.Unmarshal(m, b)
}
func (m *UpdateConsumerMetadataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateConsumerMetadataRequest.Marshal(b, m, deterministic)
}
func (m *UpdateConsumerMetadataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateConsumerMetadataRequest.Merge(m, src)
}
func (m *UpdateConsumerMetadataRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateConsumerMetadataRequest.Size(m)
}
func (m *UpdateConsumerMetadataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateConsumerMetadataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateConsumerMetadataRequest proto.InternalMessageInfo

func (m *UpdateConsumerMetadataRequest) GetNewState() *consumermetadatapb.MetadataConsumerState {
	if m != nil {
		return m.NewState
	}
	return nil
}

type UpdateConsumerMetadataResponse struct {
	Response             *commonpb.Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *UpdateConsumerMetadataResponse) Reset()         { *m = UpdateConsumerMetadataResponse{} }
func (m *UpdateConsumerMetadataResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateConsumerMetadataResponse) ProtoMessage()    {}
func (*UpdateConsumerMetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a3f1f58b4b02e2ad, []int{1}
}

func (m *UpdateConsumerMetadataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateConsumerMetadataResponse.Unmarshal(m, b)
}
func (m *UpdateConsumerMetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateConsumerMetadataResponse.Marshal(b, m, deterministic)
}
func (m *UpdateConsumerMetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateConsumerMetadataResponse.Merge(m, src)
}
func (m *UpdateConsumerMetadataResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateConsumerMetadataResponse.Size(m)
}
func (m *UpdateConsumerMetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateConsumerMetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateConsumerMetadataResponse proto.InternalMessageInfo

func (m *UpdateConsumerMetadataResponse) GetResponse() *commonpb.Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterType((*UpdateConsumerMetadataRequest)(nil), "proto.zkmessagepb.UpdateConsumerMetadataRequest")
	proto.RegisterType((*UpdateConsumerMetadataResponse)(nil), "proto.zkmessagepb.UpdateConsumerMetadataResponse")
}

func init() {
	proto.RegisterFile("proto/zkmessagepb/update_consumer_metadata.proto", fileDescriptor_a3f1f58b4b02e2ad)
}

var fileDescriptor_a3f1f58b4b02e2ad = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xaf, 0xca, 0xce, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x2d, 0x48, 0xd2, 0x2f, 0x2d,
	0x48, 0x49, 0x2c, 0x49, 0x8d, 0x4f, 0xce, 0xcf, 0x2b, 0x2e, 0xcd, 0x4d, 0x2d, 0x8a, 0xcf, 0x4d,
	0x2d, 0x49, 0x4c, 0x49, 0x2c, 0x49, 0xd4, 0x03, 0x2b, 0x15, 0x12, 0x04, 0x53, 0x7a, 0x48, 0x3a,
	0xa4, 0x64, 0x21, 0x86, 0x24, 0xe7, 0xe7, 0xe6, 0xe6, 0xe7, 0x15, 0x24, 0xe9, 0x17, 0xa5, 0x16,
	0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x42, 0x74, 0x48, 0x19, 0xc0, 0xa4, 0x21, 0x06, 0xc2, 0xcc, 0x2b,
	0x48, 0xd2, 0xc7, 0x61, 0x87, 0x52, 0x0e, 0x97, 0x6c, 0x28, 0xd8, 0x15, 0xce, 0x50, 0x05, 0xbe,
	0x50, 0xf9, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x6f, 0x2e, 0x8e, 0xbc, 0xd4, 0xf2,
	0xe0, 0x92, 0xc4, 0x92, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x6e, 0x23, 0x7d, 0x88, 0x56, 0x3d,
	0x4c, 0x5b, 0xf4, 0x60, 0x9a, 0x61, 0x86, 0x81, 0xb5, 0x05, 0xc1, 0x0d, 0x50, 0x0a, 0xe3, 0x92,
	0xc3, 0x65, 0x1b, 0xc4, 0x1f, 0x42, 0x26, 0x5c, 0x1c, 0x30, 0x3f, 0x41, 0xad, 0x93, 0x80, 0x5b,
	0x07, 0xf1, 0xb3, 0x1e, 0x4c, 0x6d, 0x10, 0x5c, 0xa5, 0x93, 0x64, 0x94, 0xb8, 0xa3, 0xb7, 0x9b,
	0xa3, 0xb7, 0x3e, 0x46, 0x18, 0x27, 0xb1, 0x81, 0x85, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xf3, 0x50, 0x5e, 0x77, 0x7f, 0x01, 0x00, 0x00,
}
