// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/zkpb/service_discovery.proto

package zkpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ServiceDiscoveryRequest_Request int32

const (
	ServiceDiscoveryRequest_BROKER ServiceDiscoveryRequest_Request = 0
)

var ServiceDiscoveryRequest_Request_name = map[int32]string{
	0: "BROKER",
}

var ServiceDiscoveryRequest_Request_value = map[string]int32{
	"BROKER": 0,
}

func (x ServiceDiscoveryRequest_Request) String() string {
	return proto.EnumName(ServiceDiscoveryRequest_Request_name, int32(x))
}

func (ServiceDiscoveryRequest_Request) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e746e1ef44659db2, []int{0, 0}
}

// Discover brokers in broker_config.json
type ServiceDiscoveryRequest struct {
	Query                string                          `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Request              ServiceDiscoveryRequest_Request `protobuf:"varint,2,opt,name=request,proto3,enum=proto.zkpb.ServiceDiscoveryRequest_Request" json:"request,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ServiceDiscoveryRequest) Reset()         { *m = ServiceDiscoveryRequest{} }
func (m *ServiceDiscoveryRequest) String() string { return proto.CompactTextString(m) }
func (*ServiceDiscoveryRequest) ProtoMessage()    {}
func (*ServiceDiscoveryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e746e1ef44659db2, []int{0}
}

func (m *ServiceDiscoveryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceDiscoveryRequest.Unmarshal(m, b)
}
func (m *ServiceDiscoveryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceDiscoveryRequest.Marshal(b, m, deterministic)
}
func (m *ServiceDiscoveryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceDiscoveryRequest.Merge(m, src)
}
func (m *ServiceDiscoveryRequest) XXX_Size() int {
	return xxx_messageInfo_ServiceDiscoveryRequest.Size(m)
}
func (m *ServiceDiscoveryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceDiscoveryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceDiscoveryRequest proto.InternalMessageInfo

func (m *ServiceDiscoveryRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *ServiceDiscoveryRequest) GetRequest() ServiceDiscoveryRequest_Request {
	if m != nil {
		return m.Request
	}
	return ServiceDiscoveryRequest_BROKER
}

type ServiceDiscoveryResponse struct {
	BrokerList           []*Broker `protobuf:"bytes,1,rep,name=brokerList,proto3" json:"brokerList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ServiceDiscoveryResponse) Reset()         { *m = ServiceDiscoveryResponse{} }
func (m *ServiceDiscoveryResponse) String() string { return proto.CompactTextString(m) }
func (*ServiceDiscoveryResponse) ProtoMessage()    {}
func (*ServiceDiscoveryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e746e1ef44659db2, []int{1}
}

func (m *ServiceDiscoveryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceDiscoveryResponse.Unmarshal(m, b)
}
func (m *ServiceDiscoveryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceDiscoveryResponse.Marshal(b, m, deterministic)
}
func (m *ServiceDiscoveryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceDiscoveryResponse.Merge(m, src)
}
func (m *ServiceDiscoveryResponse) XXX_Size() int {
	return xxx_messageInfo_ServiceDiscoveryResponse.Size(m)
}
func (m *ServiceDiscoveryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceDiscoveryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceDiscoveryResponse proto.InternalMessageInfo

func (m *ServiceDiscoveryResponse) GetBrokerList() []*Broker {
	if m != nil {
		return m.BrokerList
	}
	return nil
}

type Broker struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32    `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	IsCoordinator        bool     `protobuf:"varint,4,opt,name=isCoordinator,proto3" json:"isCoordinator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Broker) Reset()         { *m = Broker{} }
func (m *Broker) String() string { return proto.CompactTextString(m) }
func (*Broker) ProtoMessage()    {}
func (*Broker) Descriptor() ([]byte, []int) {
	return fileDescriptor_e746e1ef44659db2, []int{2}
}

func (m *Broker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Broker.Unmarshal(m, b)
}
func (m *Broker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Broker.Marshal(b, m, deterministic)
}
func (m *Broker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Broker.Merge(m, src)
}
func (m *Broker) XXX_Size() int {
	return xxx_messageInfo_Broker.Size(m)
}
func (m *Broker) XXX_DiscardUnknown() {
	xxx_messageInfo_Broker.DiscardUnknown(m)
}

var xxx_messageInfo_Broker proto.InternalMessageInfo

func (m *Broker) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Broker) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Broker) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Broker) GetIsCoordinator() bool {
	if m != nil {
		return m.IsCoordinator
	}
	return false
}

func init() {
	proto.RegisterEnum("proto.zkpb.ServiceDiscoveryRequest_Request", ServiceDiscoveryRequest_Request_name, ServiceDiscoveryRequest_Request_value)
	proto.RegisterType((*ServiceDiscoveryRequest)(nil), "proto.zkpb.ServiceDiscoveryRequest")
	proto.RegisterType((*ServiceDiscoveryResponse)(nil), "proto.zkpb.ServiceDiscoveryResponse")
	proto.RegisterType((*Broker)(nil), "proto.zkpb.Broker")
}

func init() {
	proto.RegisterFile("proto/zkpb/service_discovery.proto", fileDescriptor_e746e1ef44659db2)
}

var fileDescriptor_e746e1ef44659db2 = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xdd, 0xb4, 0x4d, 0xed, 0x88, 0xa5, 0x0c, 0x8a, 0x7b, 0x0c, 0xc1, 0x43, 0x40, 0x48,
	0x20, 0x3e, 0x41, 0xa3, 0xf5, 0x12, 0x51, 0x58, 0x6f, 0x5e, 0xc4, 0x34, 0x2b, 0x2e, 0x85, 0x4e,
	0x3a, 0xbb, 0x2d, 0xd4, 0x77, 0xf0, 0x9d, 0xa5, 0x9b, 0x86, 0x56, 0xc4, 0xd3, 0xfc, 0xfb, 0xcf,
	0xb7, 0xff, 0x30, 0x03, 0x71, 0xc3, 0xe4, 0x28, 0xfb, 0x5a, 0x34, 0x55, 0x66, 0x35, 0x6f, 0xcc,
	0x5c, 0xbf, 0xd5, 0xc6, 0xce, 0x69, 0xa3, 0x79, 0x9b, 0xfa, 0x26, 0x82, 0x2f, 0xe9, 0x8e, 0x89,
	0xbf, 0x05, 0x5c, 0xbd, 0xb4, 0xdc, 0x7d, 0x87, 0x29, 0xbd, 0x5a, 0x6b, 0xeb, 0xf0, 0x02, 0x06,
	0xab, 0xb5, 0xe6, 0xad, 0x14, 0x91, 0x48, 0x46, 0xaa, 0x7d, 0xe0, 0x0c, 0x86, 0xdc, 0x02, 0x32,
	0x88, 0x44, 0x32, 0xce, 0x6f, 0xd2, 0x43, 0x5e, 0xfa, 0x4f, 0x56, 0xba, 0xaf, 0xaa, 0xfb, 0x1b,
	0x5f, 0xc2, 0xb0, 0x9b, 0x03, 0x10, 0x16, 0xea, 0xb9, 0x9c, 0xa9, 0xc9, 0x49, 0xfc, 0x04, 0xf2,
	0x6f, 0x84, 0x6d, 0x68, 0x69, 0x35, 0xe6, 0x00, 0x15, 0xd3, 0x42, 0xf3, 0xa3, 0xb1, 0x4e, 0x8a,
	0xa8, 0x97, 0x9c, 0xe5, 0x78, 0x3c, 0xbc, 0xf0, 0x5d, 0x75, 0x44, 0xc5, 0x1f, 0x10, 0xb6, 0x2e,
	0x8e, 0x21, 0x30, 0xb5, 0x5f, 0x65, 0xa0, 0x02, 0x53, 0x23, 0x42, 0xff, 0x93, 0xf6, 0x4b, 0x8c,
	0x94, 0xd7, 0x3b, 0xaf, 0x21, 0x76, 0xb2, 0xe7, 0x29, 0xaf, 0xf1, 0x1a, 0xce, 0x8d, 0xbd, 0x23,
	0xe2, 0xda, 0x2c, 0xdf, 0x1d, 0xb1, 0xec, 0x47, 0x22, 0x39, 0x55, 0xbf, 0xcd, 0x02, 0x5f, 0x27,
	0xd3, 0xf2, 0x61, 0x5a, 0x66, 0x87, 0xfb, 0x57, 0xa1, 0xd7, 0xb7, 0x3f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x99, 0xed, 0x2d, 0xef, 0x94, 0x01, 0x00, 0x00,
}
