// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/producepb/produce.proto

package producepb

import (
	commonpb "AKFAK/proto/commonpb"
	recordpb "AKFAK/proto/recordpb"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ProduceRequest struct {
	Records      *recordpb.RecordBatch `protobuf:"bytes,1,opt,name=records,proto3" json:"records,omitempty"`
	TopicName    string                `protobuf:"bytes,2,opt,name=topicName,proto3" json:"topicName,omitempty"`
	RequiredAcks int32                 `protobuf:"varint,3,opt,name=requiredAcks,proto3" json:"requiredAcks,omitempty"`
	//
	// 0  - server will not send any response
	// 1  - server will wait the data written to the
	//      local log before sending a response
	// -1 - server will block until the message is committed
	//      by all in sync replicas before sending a response
	Partitions           int32    `protobuf:"varint,4,opt,name=partitions,proto3" json:"partitions,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProduceRequest) Reset()         { *m = ProduceRequest{} }
func (m *ProduceRequest) String() string { return proto.CompactTextString(m) }
func (*ProduceRequest) ProtoMessage()    {}
func (*ProduceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b1ed6af8408734c, []int{0}
}

func (m *ProduceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProduceRequest.Unmarshal(m, b)
}
func (m *ProduceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProduceRequest.Marshal(b, m, deterministic)
}
func (m *ProduceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProduceRequest.Merge(m, src)
}
func (m *ProduceRequest) XXX_Size() int {
	return xxx_messageInfo_ProduceRequest.Size(m)
}
func (m *ProduceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProduceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProduceRequest proto.InternalMessageInfo

func (m *ProduceRequest) GetRecords() *recordpb.RecordBatch {
	if m != nil {
		return m.Records
	}
	return nil
}

func (m *ProduceRequest) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *ProduceRequest) GetRequiredAcks() int32 {
	if m != nil {
		return m.RequiredAcks
	}
	return 0
}

func (m *ProduceRequest) GetPartitions() int32 {
	if m != nil {
		return m.Partitions
	}
	return 0
}

type ProduceResponse struct {
	Response             *commonpb.Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ProduceResponse) Reset()         { *m = ProduceResponse{} }
func (m *ProduceResponse) String() string { return proto.CompactTextString(m) }
func (*ProduceResponse) ProtoMessage()    {}
func (*ProduceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b1ed6af8408734c, []int{1}
}

func (m *ProduceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProduceResponse.Unmarshal(m, b)
}
func (m *ProduceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProduceResponse.Marshal(b, m, deterministic)
}
func (m *ProduceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProduceResponse.Merge(m, src)
}
func (m *ProduceResponse) XXX_Size() int {
	return xxx_messageInfo_ProduceResponse.Size(m)
}
func (m *ProduceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProduceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProduceResponse proto.InternalMessageInfo

func (m *ProduceResponse) GetResponse() *commonpb.Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterType((*ProduceRequest)(nil), "proto.producepb.ProduceRequest")
	proto.RegisterType((*ProduceResponse)(nil), "proto.producepb.ProduceResponse")
}

func init() {
	proto.RegisterFile("proto/producepb/produce.proto", fileDescriptor_8b1ed6af8408734c)
}

var fileDescriptor_8b1ed6af8408734c = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xcb, 0x4a, 0xc4, 0x30,
	0x18, 0x85, 0x89, 0xf7, 0xf9, 0x15, 0x07, 0x02, 0x62, 0x98, 0x51, 0x29, 0x5d, 0x75, 0x95, 0x01,
	0x2f, 0x0f, 0xd0, 0x59, 0xe8, 0xa2, 0x20, 0x92, 0xa5, 0xbb, 0x36, 0x0d, 0x18, 0xa4, 0xfd, 0xd3,
	0x24, 0x7d, 0x28, 0xdf, 0x52, 0xc8, 0xa5, 0x5e, 0x56, 0x3d, 0x9c, 0xff, 0xe3, 0xf4, 0x9c, 0xc0,
	0xad, 0xb1, 0xe8, 0x71, 0x67, 0x2c, 0xf6, 0xb3, 0x54, 0xa6, 0xcb, 0x8a, 0x07, 0x9f, 0xae, 0xc3,
	0x87, 0x2f, 0xe7, 0xcd, 0x36, 0xf2, 0x56, 0x49, 0xb4, 0xbd, 0xe9, 0x92, 0x88, 0xf4, 0x26, 0x85,
	0x49, 0x1c, 0x06, 0x1c, 0xc3, 0xd1, 0x19, 0x1c, 0x5d, 0x0a, 0x2b, 0xbf, 0x08, 0x5c, 0xbe, 0xc5,
	0x24, 0xa1, 0xa6, 0x59, 0x39, 0x4f, 0x9f, 0xe0, 0x34, 0x26, 0x38, 0x46, 0x0a, 0x52, 0x9d, 0xdf,
	0x6f, 0x23, 0xcb, 0xf3, 0x0f, 0xb8, 0x08, 0x62, 0xdf, 0x7a, 0xf9, 0x21, 0x32, 0x4b, 0x6f, 0x60,
	0xe5, 0xd1, 0x68, 0xf9, 0xda, 0x0e, 0x8a, 0x1d, 0x14, 0xa4, 0x5a, 0x89, 0x1f, 0x83, 0x96, 0x70,
	0x61, 0xd5, 0x34, 0x6b, 0xab, 0xfa, 0x5a, 0x7e, 0x3a, 0x76, 0x58, 0x90, 0xea, 0x58, 0xfc, 0xf1,
	0xe8, 0x1d, 0x80, 0x69, 0xad, 0xd7, 0x5e, 0xe3, 0xe8, 0xd8, 0x51, 0x20, 0x7e, 0x39, 0xe5, 0x0b,
	0xac, 0x97, 0xaa, 0x71, 0x04, 0x7d, 0x84, 0xb3, 0x3c, 0x28, 0x95, 0x65, 0xa9, 0x6c, 0x1e, 0xcc,
	0x33, 0x2b, 0x16, 0x72, 0x7f, 0xfd, 0x7e, 0x55, 0x37, 0xcf, 0x75, 0xb3, 0xfb, 0xf7, 0xd0, 0xdd,
	0x49, 0x30, 0x1e, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0xc4, 0x5e, 0x29, 0xf1, 0x82, 0x01, 0x00,
	0x00,
}
