// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/producepb/produce.proto

package producepb

import (
	commonpb "AKFAK/proto/commonpb"
	recordpb "AKFAK/proto/recordpb"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TopicData struct {
	Partition            int32                 `protobuf:"varint,1,opt,name=partition,proto3" json:"partition,omitempty"`
	RecordSet            *recordpb.RecordBatch `protobuf:"bytes,2,opt,name=recordSet,proto3" json:"recordSet,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *TopicData) Reset()         { *m = TopicData{} }
func (m *TopicData) String() string { return proto.CompactTextString(m) }
func (*TopicData) ProtoMessage()    {}
func (*TopicData) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b1ed6af8408734c, []int{0}
}

func (m *TopicData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TopicData.Unmarshal(m, b)
}
func (m *TopicData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TopicData.Marshal(b, m, deterministic)
}
func (m *TopicData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TopicData.Merge(m, src)
}
func (m *TopicData) XXX_Size() int {
	return xxx_messageInfo_TopicData.Size(m)
}
func (m *TopicData) XXX_DiscardUnknown() {
	xxx_messageInfo_TopicData.DiscardUnknown(m)
}

var xxx_messageInfo_TopicData proto.InternalMessageInfo

func (m *TopicData) GetPartition() int32 {
	if m != nil {
		return m.Partition
	}
	return 0
}

func (m *TopicData) GetRecordSet() *recordpb.RecordBatch {
	if m != nil {
		return m.RecordSet
	}
	return nil
}

type ProduceRequest struct {
	TopicData            []*TopicData `protobuf:"bytes,1,rep,name=topicData,proto3" json:"topicData,omitempty"`
	TopicName            string       `protobuf:"bytes,2,opt,name=topicName,proto3" json:"topicName,omitempty"`
	RequiredAcks         int32        `protobuf:"varint,3,opt,name=requiredAcks,proto3" json:"requiredAcks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ProduceRequest) Reset()         { *m = ProduceRequest{} }
func (m *ProduceRequest) String() string { return proto.CompactTextString(m) }
func (*ProduceRequest) ProtoMessage()    {}
func (*ProduceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b1ed6af8408734c, []int{1}
}

func (m *ProduceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProduceRequest.Unmarshal(m, b)
}
func (m *ProduceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProduceRequest.Marshal(b, m, deterministic)
}
func (m *ProduceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProduceRequest.Merge(m, src)
}
func (m *ProduceRequest) XXX_Size() int {
	return xxx_messageInfo_ProduceRequest.Size(m)
}
func (m *ProduceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProduceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProduceRequest proto.InternalMessageInfo

func (m *ProduceRequest) GetTopicData() []*TopicData {
	if m != nil {
		return m.TopicData
	}
	return nil
}

func (m *ProduceRequest) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *ProduceRequest) GetRequiredAcks() int32 {
	if m != nil {
		return m.RequiredAcks
	}
	return 0
}

type ProduceResponse struct {
	Response             *commonpb.Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ProduceResponse) Reset()         { *m = ProduceResponse{} }
func (m *ProduceResponse) String() string { return proto.CompactTextString(m) }
func (*ProduceResponse) ProtoMessage()    {}
func (*ProduceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b1ed6af8408734c, []int{2}
}

func (m *ProduceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProduceResponse.Unmarshal(m, b)
}
func (m *ProduceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProduceResponse.Marshal(b, m, deterministic)
}
func (m *ProduceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProduceResponse.Merge(m, src)
}
func (m *ProduceResponse) XXX_Size() int {
	return xxx_messageInfo_ProduceResponse.Size(m)
}
func (m *ProduceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProduceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProduceResponse proto.InternalMessageInfo

func (m *ProduceResponse) GetResponse() *commonpb.Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterType((*TopicData)(nil), "proto.producepb.TopicData")
	proto.RegisterType((*ProduceRequest)(nil), "proto.producepb.ProduceRequest")
	proto.RegisterType((*ProduceResponse)(nil), "proto.producepb.ProduceResponse")
}

func init() {
	proto.RegisterFile("proto/producepb/produce.proto", fileDescriptor_8b1ed6af8408734c)
}

var fileDescriptor_8b1ed6af8408734c = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0x89, 0x8b, 0x62, 0x52, 0x71, 0x21, 0x20, 0x86, 0xae, 0x42, 0xe9, 0xa9, 0xa7, 0x2c,
	0x54, 0x0f, 0x7a, 0xec, 0x22, 0x7a, 0x58, 0x10, 0x89, 0x9e, 0xbc, 0xa5, 0x69, 0xc0, 0x22, 0x6d,
	0xb2, 0x69, 0xfa, 0x2f, 0xfc, 0xd1, 0xe2, 0xa4, 0x69, 0x71, 0x4f, 0x9d, 0xbe, 0x79, 0xbc, 0xf9,
	0x66, 0x42, 0x6e, 0xad, 0x33, 0xde, 0x6c, 0xad, 0x33, 0xcd, 0xa8, 0xb4, 0xad, 0x63, 0xc5, 0x41,
	0xa7, 0x6b, 0xf8, 0xf0, 0xb9, 0x9d, 0x6e, 0x82, 0xdf, 0x69, 0x65, 0x5c, 0x63, 0xeb, 0xa9, 0x08,
	0xee, 0x74, 0x0a, 0x53, 0xa6, 0xeb, 0x4c, 0x0f, 0xcd, 0xc1, 0x9a, 0x7e, 0x98, 0xc2, 0xf2, 0x86,
	0xe0, 0x0f, 0x63, 0x5b, 0xf5, 0x24, 0xbd, 0xa4, 0x37, 0x04, 0x5b, 0xe9, 0x7c, 0xeb, 0x5b, 0xd3,
	0x33, 0x94, 0xa1, 0xe2, 0x54, 0x2c, 0x02, 0x7d, 0x24, 0x38, 0x24, 0xbf, 0x6b, 0xcf, 0x4e, 0x32,
	0x54, 0x24, 0xe5, 0x26, 0xa4, 0xf0, 0x38, 0x9a, 0x0b, 0x28, 0x76, 0xd2, 0xab, 0x2f, 0xb1, 0xb8,
	0xf3, 0x1f, 0x44, 0x2e, 0xdf, 0x02, 0xaf, 0xd0, 0x87, 0x51, 0x0f, 0x9e, 0x3e, 0x10, 0xec, 0xe3,
	0x60, 0x86, 0xb2, 0x55, 0x91, 0x94, 0x29, 0x3f, 0xda, 0x8c, 0xcf, 0x68, 0x62, 0x31, 0xff, 0x51,
	0xc2, 0xcf, 0xab, 0xec, 0x34, 0x70, 0x60, 0xb1, 0x08, 0x34, 0x27, 0x17, 0x4e, 0x1f, 0xc6, 0xd6,
	0xe9, 0xa6, 0x52, 0xdf, 0x03, 0x5b, 0xc1, 0x1a, 0xff, 0xb4, 0xfc, 0x85, 0xac, 0x67, 0x9a, 0x70,
	0x0d, 0x7a, 0x4f, 0xce, 0xe3, 0x65, 0x60, 0xf3, 0xa4, 0x64, 0x13, 0x4d, 0xbc, 0x1c, 0x8f, 0x5e,
	0x31, 0x3b, 0x77, 0xd7, 0x9f, 0x57, 0xd5, 0xfe, 0xb9, 0xda, 0x6f, 0x8f, 0x5e, 0xac, 0x3e, 0x03,
	0xe1, 0xee, 0x37, 0x00, 0x00, 0xff, 0xff, 0xaa, 0x23, 0xbd, 0x19, 0xcb, 0x01, 0x00, 0x00,
}
