// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/adminclientpb/admin_client_new_partition.proto

package adminclientpb

import (
	commonpb "AKFAK/proto/commonpb"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AdminClientNewPartitionRequest struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	PartitionID          []int32  `protobuf:"varint,2,rep,packed,name=partitionID,proto3" json:"partitionID,omitempty"`
	ReplicaID            int32    `protobuf:"varint,3,opt,name=replicaID,proto3" json:"replicaID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminClientNewPartitionRequest) Reset()         { *m = AdminClientNewPartitionRequest{} }
func (m *AdminClientNewPartitionRequest) String() string { return proto.CompactTextString(m) }
func (*AdminClientNewPartitionRequest) ProtoMessage()    {}
func (*AdminClientNewPartitionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ee3e6d56af28866, []int{0}
}

func (m *AdminClientNewPartitionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminClientNewPartitionRequest.Unmarshal(m, b)
}
func (m *AdminClientNewPartitionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminClientNewPartitionRequest.Marshal(b, m, deterministic)
}
func (m *AdminClientNewPartitionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminClientNewPartitionRequest.Merge(m, src)
}
func (m *AdminClientNewPartitionRequest) XXX_Size() int {
	return xxx_messageInfo_AdminClientNewPartitionRequest.Size(m)
}
func (m *AdminClientNewPartitionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminClientNewPartitionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminClientNewPartitionRequest proto.InternalMessageInfo

func (m *AdminClientNewPartitionRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *AdminClientNewPartitionRequest) GetPartitionID() []int32 {
	if m != nil {
		return m.PartitionID
	}
	return nil
}

func (m *AdminClientNewPartitionRequest) GetReplicaID() int32 {
	if m != nil {
		return m.ReplicaID
	}
	return 0
}

type AdminClientNewPartitionResponse struct {
	Response             *commonpb.Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AdminClientNewPartitionResponse) Reset()         { *m = AdminClientNewPartitionResponse{} }
func (m *AdminClientNewPartitionResponse) String() string { return proto.CompactTextString(m) }
func (*AdminClientNewPartitionResponse) ProtoMessage()    {}
func (*AdminClientNewPartitionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9ee3e6d56af28866, []int{1}
}

func (m *AdminClientNewPartitionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminClientNewPartitionResponse.Unmarshal(m, b)
}
func (m *AdminClientNewPartitionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminClientNewPartitionResponse.Marshal(b, m, deterministic)
}
func (m *AdminClientNewPartitionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminClientNewPartitionResponse.Merge(m, src)
}
func (m *AdminClientNewPartitionResponse) XXX_Size() int {
	return xxx_messageInfo_AdminClientNewPartitionResponse.Size(m)
}
func (m *AdminClientNewPartitionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminClientNewPartitionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AdminClientNewPartitionResponse proto.InternalMessageInfo

func (m *AdminClientNewPartitionResponse) GetResponse() *commonpb.Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterType((*AdminClientNewPartitionRequest)(nil), "proto.adminclientpb.AdminClientNewPartitionRequest")
	proto.RegisterType((*AdminClientNewPartitionResponse)(nil), "proto.adminclientpb.AdminClientNewPartitionResponse")
}

func init() {
	proto.RegisterFile("proto/adminclientpb/admin_client_new_partition.proto", fileDescriptor_9ee3e6d56af28866)
}

var fileDescriptor_9ee3e6d56af28866 = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x29, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x4c, 0xc9, 0xcd, 0xcc, 0x4b, 0xce, 0xc9, 0x4c, 0xcd, 0x2b, 0x29, 0x48, 0x82,
	0xf0, 0xe2, 0x21, 0xdc, 0xf8, 0xbc, 0xd4, 0xf2, 0xf8, 0x82, 0xc4, 0xa2, 0x92, 0xcc, 0x92, 0xcc,
	0xfc, 0x3c, 0x3d, 0xb0, 0x72, 0x21, 0x61, 0x30, 0xa5, 0x87, 0xa2, 0x4b, 0x4a, 0x16, 0x62, 0x54,
	0x72, 0x7e, 0x6e, 0x6e, 0x7e, 0x5e, 0x41, 0x92, 0x7e, 0x51, 0x6a, 0x71, 0x41, 0x7e, 0x5e, 0x71,
	0x2a, 0x44, 0x8f, 0x52, 0x19, 0x97, 0x9c, 0x23, 0x48, 0xbd, 0x33, 0x58, 0xbd, 0x5f, 0x6a, 0x79,
	0x00, 0xcc, 0xd0, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x11, 0x2e, 0xd6, 0x92, 0xfc,
	0x82, 0xcc, 0x64, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x08, 0x47, 0x48, 0x81, 0x8b, 0x1b,
	0x6e, 0xbd, 0xa7, 0x8b, 0x04, 0x93, 0x02, 0xb3, 0x06, 0x6b, 0x10, 0xb2, 0x90, 0x90, 0x0c, 0x17,
	0x67, 0x51, 0x6a, 0x41, 0x4e, 0x66, 0x72, 0xa2, 0xa7, 0x8b, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0x6b,
	0x10, 0x42, 0x40, 0x29, 0x9c, 0x4b, 0x1e, 0xa7, 0xbd, 0x10, 0x07, 0x0a, 0x99, 0x70, 0x71, 0xc0,
	0x1c, 0x0b, 0xb6, 0x9b, 0xdb, 0x48, 0x02, 0xe2, 0x68, 0x3d, 0x98, 0x67, 0xf4, 0x60, 0x6a, 0x83,
	0xe0, 0x2a, 0x9d, 0xa4, 0xa3, 0x24, 0x1d, 0xbd, 0xdd, 0x1c, 0xbd, 0xf5, 0xb1, 0x04, 0x61, 0x12,
	0x1b, 0x58, 0xd0, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xbc, 0x3b, 0xb5, 0xd2, 0x60, 0x01, 0x00,
	0x00,
}
