// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/adminclientpb/admin_client_new_topic.proto

package adminclientpb

import (
	commonpb "AKFAK/proto/commonpb"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AdminClientNewTopicRequest struct {
	Topic                string   `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	NumPartitions        int32    `protobuf:"varint,2,opt,name=numPartitions,proto3" json:"numPartitions,omitempty"`
	ReplicationFactor    int32    `protobuf:"varint,3,opt,name=replicationFactor,proto3" json:"replicationFactor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminClientNewTopicRequest) Reset()         { *m = AdminClientNewTopicRequest{} }
func (m *AdminClientNewTopicRequest) String() string { return proto.CompactTextString(m) }
func (*AdminClientNewTopicRequest) ProtoMessage()    {}
func (*AdminClientNewTopicRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_de07f89a3fbe7fbb, []int{0}
}

func (m *AdminClientNewTopicRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminClientNewTopicRequest.Unmarshal(m, b)
}
func (m *AdminClientNewTopicRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminClientNewTopicRequest.Marshal(b, m, deterministic)
}
func (m *AdminClientNewTopicRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminClientNewTopicRequest.Merge(m, src)
}
func (m *AdminClientNewTopicRequest) XXX_Size() int {
	return xxx_messageInfo_AdminClientNewTopicRequest.Size(m)
}
func (m *AdminClientNewTopicRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminClientNewTopicRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminClientNewTopicRequest proto.InternalMessageInfo

func (m *AdminClientNewTopicRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

func (m *AdminClientNewTopicRequest) GetNumPartitions() int32 {
	if m != nil {
		return m.NumPartitions
	}
	return 0
}

func (m *AdminClientNewTopicRequest) GetReplicationFactor() int32 {
	if m != nil {
		return m.ReplicationFactor
	}
	return 0
}

type AdminClientNewTopicResponse struct {
	Response             *commonpb.Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AdminClientNewTopicResponse) Reset()         { *m = AdminClientNewTopicResponse{} }
func (m *AdminClientNewTopicResponse) String() string { return proto.CompactTextString(m) }
func (*AdminClientNewTopicResponse) ProtoMessage()    {}
func (*AdminClientNewTopicResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_de07f89a3fbe7fbb, []int{1}
}

func (m *AdminClientNewTopicResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminClientNewTopicResponse.Unmarshal(m, b)
}
func (m *AdminClientNewTopicResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminClientNewTopicResponse.Marshal(b, m, deterministic)
}
func (m *AdminClientNewTopicResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminClientNewTopicResponse.Merge(m, src)
}
func (m *AdminClientNewTopicResponse) XXX_Size() int {
	return xxx_messageInfo_AdminClientNewTopicResponse.Size(m)
}
func (m *AdminClientNewTopicResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminClientNewTopicResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AdminClientNewTopicResponse proto.InternalMessageInfo

func (m *AdminClientNewTopicResponse) GetResponse() *commonpb.Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterType((*AdminClientNewTopicRequest)(nil), "proto.adminclientpb.AdminClientNewTopicRequest")
	proto.RegisterType((*AdminClientNewTopicResponse)(nil), "proto.adminclientpb.AdminClientNewTopicResponse")
}

func init() {
	proto.RegisterFile("proto/adminclientpb/admin_client_new_topic.proto", fileDescriptor_de07f89a3fbe7fbb)
}

var fileDescriptor_de07f89a3fbe7fbb = []byte{
	// 231 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x4c, 0xc9, 0xcd, 0xcc, 0x4b, 0xce, 0xc9, 0x4c, 0xcd, 0x2b, 0x29, 0x48, 0x82,
	0xf0, 0xe2, 0x21, 0xdc, 0xf8, 0xbc, 0xd4, 0xf2, 0xf8, 0x92, 0xfc, 0x82, 0xcc, 0x64, 0x3d, 0xb0,
	0x52, 0x21, 0x61, 0x30, 0xa5, 0x87, 0xa2, 0x43, 0x4a, 0x16, 0x62, 0x4c, 0x72, 0x7e, 0x6e, 0x6e,
	0x7e, 0x5e, 0x41, 0x92, 0x7e, 0x51, 0x6a, 0x71, 0x41, 0x7e, 0x5e, 0x71, 0x2a, 0x44, 0x8f, 0x52,
	0x1b, 0x23, 0x97, 0x94, 0x23, 0x48, 0x83, 0x33, 0x58, 0x83, 0x5f, 0x6a, 0x79, 0x08, 0xc8, 0xc4,
	0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21, 0x11, 0x2e, 0x56, 0xb0, 0x0d, 0x12, 0x8c, 0x0a,
	0x8c, 0x1a, 0x9c, 0x41, 0x10, 0x8e, 0x90, 0x0a, 0x17, 0x6f, 0x5e, 0x69, 0x6e, 0x40, 0x62, 0x51,
	0x49, 0x66, 0x49, 0x66, 0x7e, 0x5e, 0xb1, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0xaa, 0xa0,
	0x90, 0x0e, 0x97, 0x60, 0x51, 0x6a, 0x41, 0x4e, 0x66, 0x72, 0x22, 0x88, 0xef, 0x96, 0x98, 0x5c,
	0x92, 0x5f, 0x24, 0xc1, 0x0c, 0x56, 0x89, 0x29, 0xa1, 0x14, 0xcc, 0x25, 0x8d, 0xd5, 0x1d, 0x10,
	0xd7, 0x0a, 0x99, 0x70, 0x71, 0xc0, 0x5c, 0x0e, 0x76, 0x0b, 0xb7, 0x91, 0x04, 0xc4, 0x07, 0x7a,
	0x30, 0x9f, 0xe9, 0xc1, 0xd4, 0x06, 0xc1, 0x55, 0x3a, 0x49, 0x47, 0x49, 0x3a, 0x7a, 0xbb, 0x39,
	0x7a, 0xeb, 0x63, 0x09, 0xcb, 0x24, 0x36, 0xb0, 0xa0, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x2f,
	0xe8, 0x36, 0x4f, 0x69, 0x01, 0x00, 0x00,
}
