// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/adminclientpb/controller_election.proto

package adminclientpb

import (
	commonpb "AKFAK/proto/commonpb"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// TODO: Need to update again after ZK is finalised
type ControllerElectionRequest struct {
	BrokerID             int32    `protobuf:"varint,1,opt,name=brokerID,proto3" json:"brokerID,omitempty"`
	HostName             string   `protobuf:"bytes,2,opt,name=hostName,proto3" json:"hostName,omitempty"`
	Port                 int32    `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ControllerElectionRequest) Reset()         { *m = ControllerElectionRequest{} }
func (m *ControllerElectionRequest) String() string { return proto.CompactTextString(m) }
func (*ControllerElectionRequest) ProtoMessage()    {}
func (*ControllerElectionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9f552d1fe52aeb4, []int{0}
}

func (m *ControllerElectionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControllerElectionRequest.Unmarshal(m, b)
}
func (m *ControllerElectionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControllerElectionRequest.Marshal(b, m, deterministic)
}
func (m *ControllerElectionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControllerElectionRequest.Merge(m, src)
}
func (m *ControllerElectionRequest) XXX_Size() int {
	return xxx_messageInfo_ControllerElectionRequest.Size(m)
}
func (m *ControllerElectionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ControllerElectionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ControllerElectionRequest proto.InternalMessageInfo

func (m *ControllerElectionRequest) GetBrokerID() int32 {
	if m != nil {
		return m.BrokerID
	}
	return 0
}

func (m *ControllerElectionRequest) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *ControllerElectionRequest) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type ControllerElectionResponse struct {
	Response             *commonpb.Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ControllerElectionResponse) Reset()         { *m = ControllerElectionResponse{} }
func (m *ControllerElectionResponse) String() string { return proto.CompactTextString(m) }
func (*ControllerElectionResponse) ProtoMessage()    {}
func (*ControllerElectionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c9f552d1fe52aeb4, []int{1}
}

func (m *ControllerElectionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ControllerElectionResponse.Unmarshal(m, b)
}
func (m *ControllerElectionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ControllerElectionResponse.Marshal(b, m, deterministic)
}
func (m *ControllerElectionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ControllerElectionResponse.Merge(m, src)
}
func (m *ControllerElectionResponse) XXX_Size() int {
	return xxx_messageInfo_ControllerElectionResponse.Size(m)
}
func (m *ControllerElectionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ControllerElectionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ControllerElectionResponse proto.InternalMessageInfo

func (m *ControllerElectionResponse) GetResponse() *commonpb.Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterType((*ControllerElectionRequest)(nil), "proto.adminclientpb.ControllerElectionRequest")
	proto.RegisterType((*ControllerElectionResponse)(nil), "proto.adminclientpb.ControllerElectionResponse")
}

func init() {
	proto.RegisterFile("proto/adminclientpb/controller_election.proto", fileDescriptor_c9f552d1fe52aeb4)
}

var fileDescriptor_c9f552d1fe52aeb4 = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4d, 0x4b, 0x05, 0x21,
	0x14, 0x86, 0x99, 0xbe, 0xb8, 0xd9, 0xce, 0x36, 0xde, 0x89, 0xe0, 0x32, 0xab, 0xd9, 0xa4, 0x50,
	0xfd, 0x81, 0xe9, 0x0b, 0x62, 0xa0, 0x85, 0xcb, 0x36, 0x31, 0xda, 0xa1, 0x86, 0xd4, 0x63, 0x6a,
	0xff, 0x3f, 0xd2, 0x46, 0xb8, 0x30, 0x2b, 0x3d, 0xfa, 0x9c, 0xf7, 0x3c, 0x1c, 0x72, 0xe5, 0x03,
	0x26, 0x14, 0xd3, 0xbb, 0x9d, 0x9d, 0x36, 0x33, 0xb8, 0xe4, 0x95, 0xd0, 0xe8, 0x52, 0x40, 0x63,
	0x20, 0xbc, 0x81, 0x01, 0x9d, 0x66, 0x74, 0x3c, 0x73, 0xf4, 0x3c, 0x1f, 0x7c, 0x0f, 0x6f, 0x2f,
	0x4b, 0x86, 0x46, 0x6b, 0xd1, 0x79, 0x25, 0x02, 0x44, 0x8f, 0x2e, 0x42, 0xe9, 0xe9, 0x3e, 0xc8,
	0xf6, 0xbe, 0x06, 0x3e, 0xfe, 0xe7, 0x49, 0xf8, 0xfe, 0x81, 0x98, 0x68, 0x4b, 0x36, 0x2a, 0xe0,
	0x17, 0x84, 0xe7, 0x07, 0xd6, 0xec, 0x9a, 0xfe, 0x58, 0xd6, 0xfa, 0xef, 0xef, 0x13, 0x63, 0x7a,
	0x99, 0x2c, 0xb0, 0x83, 0x5d, 0xd3, 0x9f, 0xca, 0x5a, 0x53, 0x4a, 0x8e, 0x3c, 0x86, 0xc4, 0x0e,
	0x73, 0x4f, 0xbe, 0x77, 0x92, 0xb4, 0x6b, 0x83, 0x8a, 0x0c, 0xbd, 0x25, 0x9b, 0x45, 0x2c, 0x4f,
	0x3a, 0xbb, 0x66, 0x45, 0x90, 0x2f, 0xe2, 0x7c, 0x61, 0x65, 0x25, 0xef, 0x2e, 0x5e, 0xb7, 0xc3,
	0xf8, 0x34, 0x8c, 0x62, 0x65, 0x4f, 0xea, 0x24, 0x3f, 0xde, 0xfc, 0x06, 0x00, 0x00, 0xff, 0xff,
	0xd0, 0xef, 0xfe, 0x18, 0x45, 0x01, 0x00, 0x00,
}
