// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/adminclientpb/get_controller.proto

package adminclientpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetControllerRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetControllerRequest) Reset()         { *m = GetControllerRequest{} }
func (m *GetControllerRequest) String() string { return proto.CompactTextString(m) }
func (*GetControllerRequest) ProtoMessage()    {}
func (*GetControllerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcf653f85dfed209, []int{0}
}

func (m *GetControllerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetControllerRequest.Unmarshal(m, b)
}
func (m *GetControllerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetControllerRequest.Marshal(b, m, deterministic)
}
func (m *GetControllerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetControllerRequest.Merge(m, src)
}
func (m *GetControllerRequest) XXX_Size() int {
	return xxx_messageInfo_GetControllerRequest.Size(m)
}
func (m *GetControllerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetControllerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetControllerRequest proto.InternalMessageInfo

type GetControllerResponse struct {
	ControllerID         int32    `protobuf:"varint,1,opt,name=controllerID,proto3" json:"controllerID,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32    `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetControllerResponse) Reset()         { *m = GetControllerResponse{} }
func (m *GetControllerResponse) String() string { return proto.CompactTextString(m) }
func (*GetControllerResponse) ProtoMessage()    {}
func (*GetControllerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fcf653f85dfed209, []int{1}
}

func (m *GetControllerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetControllerResponse.Unmarshal(m, b)
}
func (m *GetControllerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetControllerResponse.Marshal(b, m, deterministic)
}
func (m *GetControllerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetControllerResponse.Merge(m, src)
}
func (m *GetControllerResponse) XXX_Size() int {
	return xxx_messageInfo_GetControllerResponse.Size(m)
}
func (m *GetControllerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetControllerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetControllerResponse proto.InternalMessageInfo

func (m *GetControllerResponse) GetControllerID() int32 {
	if m != nil {
		return m.ControllerID
	}
	return 0
}

func (m *GetControllerResponse) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *GetControllerResponse) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func init() {
	proto.RegisterType((*GetControllerRequest)(nil), "proto.adminclientpb.GetControllerRequest")
	proto.RegisterType((*GetControllerResponse)(nil), "proto.adminclientpb.GetControllerResponse")
}

func init() {
	proto.RegisterFile("proto/adminclientpb/get_controller.proto", fileDescriptor_fcf653f85dfed209)
}

var fileDescriptor_fcf653f85dfed209 = []byte{
	// 162 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x4c, 0xc9, 0xcd, 0xcc, 0x4b, 0xce, 0xc9, 0x4c, 0xcd, 0x2b, 0x29, 0x48, 0xd2,
	0x4f, 0x4f, 0x2d, 0x89, 0x4f, 0xce, 0xcf, 0x2b, 0x29, 0xca, 0xcf, 0xc9, 0x49, 0x2d, 0xd2, 0x03,
	0x2b, 0x11, 0x12, 0x06, 0x53, 0x7a, 0x28, 0x2a, 0x95, 0xc4, 0xb8, 0x44, 0xdc, 0x53, 0x4b, 0x9c,
	0xe1, 0x6a, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x94, 0x92, 0xb9, 0x44, 0xd1, 0xc4, 0x8b,
	0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x94, 0xb8, 0x78, 0x10, 0x26, 0x7b, 0xba, 0x48, 0x30, 0x2a,
	0x30, 0x6a, 0xb0, 0x06, 0xa1, 0x88, 0x09, 0x09, 0x71, 0xb1, 0x64, 0xe4, 0x17, 0x97, 0x48, 0x30,
	0x29, 0x30, 0x6a, 0x70, 0x06, 0x81, 0xd9, 0x20, 0xb1, 0x82, 0xfc, 0xa2, 0x12, 0x09, 0x66, 0xb0,
	0x7a, 0x30, 0xdb, 0x49, 0x3a, 0x4a, 0xd2, 0xd1, 0xdb, 0xcd, 0xd1, 0x5b, 0x1f, 0x8b, 0x1f, 0x92,
	0xd8, 0xc0, 0x82, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0b, 0x7d, 0x07, 0x8f, 0xe1, 0x00,
	0x00, 0x00,
}
