// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/adminclientpb/insync_message.proto

package adminclientpb

import (
	commonpb "AKFAK/proto/commonpb"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InSyncMessagesRequest struct {
	ReplicaID            int32    `protobuf:"varint,1,opt,name=replicaID,proto3" json:"replicaID,omitempty"`
	Partition            int32    `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	Topic                string   `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InSyncMessagesRequest) Reset()         { *m = InSyncMessagesRequest{} }
func (m *InSyncMessagesRequest) String() string { return proto.CompactTextString(m) }
func (*InSyncMessagesRequest) ProtoMessage()    {}
func (*InSyncMessagesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3880a990efeb89c, []int{0}
}

func (m *InSyncMessagesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InSyncMessagesRequest.Unmarshal(m, b)
}
func (m *InSyncMessagesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InSyncMessagesRequest.Marshal(b, m, deterministic)
}
func (m *InSyncMessagesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InSyncMessagesRequest.Merge(m, src)
}
func (m *InSyncMessagesRequest) XXX_Size() int {
	return xxx_messageInfo_InSyncMessagesRequest.Size(m)
}
func (m *InSyncMessagesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InSyncMessagesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InSyncMessagesRequest proto.InternalMessageInfo

func (m *InSyncMessagesRequest) GetReplicaID() int32 {
	if m != nil {
		return m.ReplicaID
	}
	return 0
}

func (m *InSyncMessagesRequest) GetPartition() int32 {
	if m != nil {
		return m.Partition
	}
	return 0
}

func (m *InSyncMessagesRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type InSyncMessagesResponse struct {
	Response             *commonpb.Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *InSyncMessagesResponse) Reset()         { *m = InSyncMessagesResponse{} }
func (m *InSyncMessagesResponse) String() string { return proto.CompactTextString(m) }
func (*InSyncMessagesResponse) ProtoMessage()    {}
func (*InSyncMessagesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d3880a990efeb89c, []int{1}
}

func (m *InSyncMessagesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InSyncMessagesResponse.Unmarshal(m, b)
}
func (m *InSyncMessagesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InSyncMessagesResponse.Marshal(b, m, deterministic)
}
func (m *InSyncMessagesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InSyncMessagesResponse.Merge(m, src)
}
func (m *InSyncMessagesResponse) XXX_Size() int {
	return xxx_messageInfo_InSyncMessagesResponse.Size(m)
}
func (m *InSyncMessagesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InSyncMessagesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InSyncMessagesResponse proto.InternalMessageInfo

func (m *InSyncMessagesResponse) GetResponse() *commonpb.Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterType((*InSyncMessagesRequest)(nil), "proto.adminclientpb.InSyncMessagesRequest")
	proto.RegisterType((*InSyncMessagesResponse)(nil), "proto.adminclientpb.InSyncMessagesResponse")
}

func init() {
	proto.RegisterFile("proto/adminclientpb/insync_message.proto", fileDescriptor_d3880a990efeb89c)
}

var fileDescriptor_d3880a990efeb89c = []byte{
	// 218 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x28, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x4c, 0xc9, 0xcd, 0xcc, 0x4b, 0xce, 0xc9, 0x4c, 0xcd, 0x2b, 0x29, 0x48, 0xd2,
	0xcf, 0xcc, 0x2b, 0xae, 0xcc, 0x4b, 0x8e, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x03,
	0x2b, 0x11, 0x12, 0x06, 0x53, 0x7a, 0x28, 0x2a, 0xa5, 0x64, 0x21, 0xda, 0x93, 0xf3, 0x73, 0x73,
	0xf3, 0xf3, 0x0a, 0x92, 0xf4, 0x8b, 0x52, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0xa1, 0x7a, 0x94, 0x32,
	0xb9, 0x44, 0x3d, 0xf3, 0x82, 0x2b, 0xf3, 0x92, 0x7d, 0x21, 0x46, 0x15, 0x07, 0xa5, 0x16, 0x96,
	0xa6, 0x16, 0x97, 0x08, 0xc9, 0x70, 0x71, 0x16, 0xa5, 0x16, 0xe4, 0x64, 0x26, 0x27, 0x7a, 0xba,
	0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x06, 0x21, 0x04, 0x40, 0xb2, 0x05, 0x89, 0x45, 0x25, 0x99,
	0x25, 0x99, 0xf9, 0x79, 0x12, 0x4c, 0x10, 0x59, 0xb8, 0x80, 0x90, 0x08, 0x17, 0x6b, 0x49, 0x7e,
	0x41, 0x66, 0xb2, 0x04, 0xb3, 0x02, 0xa3, 0x06, 0x67, 0x10, 0x84, 0xa3, 0xe4, 0xc7, 0x25, 0x86,
	0x6e, 0x15, 0xc4, 0x29, 0x42, 0x26, 0x5c, 0x1c, 0x30, 0x67, 0x81, 0xad, 0xe2, 0x36, 0x92, 0x80,
	0x38, 0x4f, 0x0f, 0xe6, 0x6c, 0x3d, 0x98, 0xda, 0x20, 0xb8, 0x4a, 0x27, 0xe9, 0x28, 0x49, 0x47,
	0x6f, 0x37, 0x47, 0x6f, 0x7d, 0x2c, 0x01, 0x94, 0xc4, 0x06, 0x16, 0x34, 0x06, 0x04, 0x00, 0x00,
	0xff, 0xff, 0xcd, 0x57, 0xaf, 0x2c, 0x3e, 0x01, 0x00, 0x00,
}
