// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/adminclientpb/update_metadata.proto

package adminclientpb

import (
	clustermetadatapb "AKFAK/proto/clustermetadatapb"
	commonpb "AKFAK/proto/commonpb"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpdateMetadataRequest struct {
	NewClusterInfo       *clustermetadatapb.MetadataCluster `protobuf:"bytes,1,opt,name=newClusterInfo,proto3" json:"newClusterInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *UpdateMetadataRequest) Reset()         { *m = UpdateMetadataRequest{} }
func (m *UpdateMetadataRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateMetadataRequest) ProtoMessage()    {}
func (*UpdateMetadataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbb28286b10953d7, []int{0}
}

func (m *UpdateMetadataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMetadataRequest.Unmarshal(m, b)
}
func (m *UpdateMetadataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMetadataRequest.Marshal(b, m, deterministic)
}
func (m *UpdateMetadataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMetadataRequest.Merge(m, src)
}
func (m *UpdateMetadataRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateMetadataRequest.Size(m)
}
func (m *UpdateMetadataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMetadataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMetadataRequest proto.InternalMessageInfo

func (m *UpdateMetadataRequest) GetNewClusterInfo() *clustermetadatapb.MetadataCluster {
	if m != nil {
		return m.NewClusterInfo
	}
	return nil
}

type UpdateMetadataResponse struct {
	Response             *commonpb.Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *UpdateMetadataResponse) Reset()         { *m = UpdateMetadataResponse{} }
func (m *UpdateMetadataResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateMetadataResponse) ProtoMessage()    {}
func (*UpdateMetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbb28286b10953d7, []int{1}
}

func (m *UpdateMetadataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMetadataResponse.Unmarshal(m, b)
}
func (m *UpdateMetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMetadataResponse.Marshal(b, m, deterministic)
}
func (m *UpdateMetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMetadataResponse.Merge(m, src)
}
func (m *UpdateMetadataResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateMetadataResponse.Size(m)
}
func (m *UpdateMetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMetadataResponse proto.InternalMessageInfo

func (m *UpdateMetadataResponse) GetResponse() *commonpb.Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterType((*UpdateMetadataRequest)(nil), "proto.adminclientpb.UpdateMetadataRequest")
	proto.RegisterType((*UpdateMetadataResponse)(nil), "proto.adminclientpb.UpdateMetadataResponse")
}

func init() {
	proto.RegisterFile("proto/adminclientpb/update_metadata.proto", fileDescriptor_fbb28286b10953d7)
}

var fileDescriptor_fbb28286b10953d7 = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0x4c, 0xc9, 0xcd, 0xcc, 0x4b, 0xce, 0xc9, 0x4c, 0xcd, 0x2b, 0x29, 0x48, 0xd2,
	0x2f, 0x2d, 0x48, 0x49, 0x2c, 0x49, 0x8d, 0xcf, 0x4d, 0x2d, 0x49, 0x4c, 0x49, 0x2c, 0x49, 0xd4,
	0x03, 0xab, 0x11, 0x12, 0x06, 0x53, 0x7a, 0x28, 0x4a, 0xa5, 0x64, 0x21, 0xfa, 0x93, 0xf3, 0x73,
	0x73, 0xf3, 0xf3, 0x0a, 0x92, 0xf4, 0x8b, 0x52, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x21, 0x7a,
	0xa4, 0xf4, 0xa0, 0xd2, 0x39, 0xa5, 0xc5, 0x25, 0xa9, 0x45, 0x30, 0x03, 0x0b, 0x92, 0x60, 0x22,
	0x68, 0x76, 0x28, 0x65, 0x72, 0x89, 0x86, 0x82, 0x2d, 0xf7, 0x85, 0x8a, 0x07, 0xa5, 0x16, 0x96,
	0xa6, 0x16, 0x97, 0x08, 0x05, 0x70, 0xf1, 0xe5, 0xa5, 0x96, 0x3b, 0x43, 0x74, 0x79, 0xe6, 0xa5,
	0xe5, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x1b, 0x69, 0x40, 0x34, 0xea, 0x61, 0xd8, 0xa0, 0x07,
	0x33, 0x01, 0xaa, 0x27, 0x08, 0x4d, 0xbf, 0x92, 0x1f, 0x97, 0x18, 0xba, 0x55, 0x10, 0xa7, 0x0b,
	0x99, 0x70, 0x71, 0xc0, 0xbc, 0x01, 0xb5, 0x45, 0x02, 0x66, 0x0b, 0xd4, 0x9b, 0x7a, 0x30, 0xb5,
	0x41, 0x70, 0x95, 0x4e, 0xd2, 0x51, 0x92, 0x8e, 0xde, 0x6e, 0x8e, 0xde, 0xfa, 0x58, 0x42, 0x34,
	0x89, 0x0d, 0x2c, 0x68, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x44, 0xaa, 0xc7, 0xa5, 0x6f, 0x01,
	0x00, 0x00,
}
