// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/adminclientpb/update_metadata.proto

package adminclientpb

import (
	commonpb "AKFAK/proto/commonpb"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpdateMetadataPartitionState struct {
	TopicName            string   `protobuf:"bytes,1,opt,name=topicName,proto3" json:"topicName,omitempty"`
	PartitionIndex       int32    `protobuf:"varint,2,opt,name=partitionIndex,proto3" json:"partitionIndex,omitempty"`
	Leader               int32    `protobuf:"varint,3,opt,name=leader,proto3" json:"leader,omitempty"`
	Isr                  []int32  `protobuf:"varint,4,rep,packed,name=isr,proto3" json:"isr,omitempty"`
	Replicas             []int32  `protobuf:"varint,5,rep,packed,name=replicas,proto3" json:"replicas,omitempty"`
	OfflineReplicas      []int32  `protobuf:"varint,6,rep,packed,name=offlineReplicas,proto3" json:"offlineReplicas,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateMetadataPartitionState) Reset()         { *m = UpdateMetadataPartitionState{} }
func (m *UpdateMetadataPartitionState) String() string { return proto.CompactTextString(m) }
func (*UpdateMetadataPartitionState) ProtoMessage()    {}
func (*UpdateMetadataPartitionState) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbb28286b10953d7, []int{0}
}

func (m *UpdateMetadataPartitionState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMetadataPartitionState.Unmarshal(m, b)
}
func (m *UpdateMetadataPartitionState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMetadataPartitionState.Marshal(b, m, deterministic)
}
func (m *UpdateMetadataPartitionState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMetadataPartitionState.Merge(m, src)
}
func (m *UpdateMetadataPartitionState) XXX_Size() int {
	return xxx_messageInfo_UpdateMetadataPartitionState.Size(m)
}
func (m *UpdateMetadataPartitionState) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMetadataPartitionState.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMetadataPartitionState proto.InternalMessageInfo

func (m *UpdateMetadataPartitionState) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *UpdateMetadataPartitionState) GetPartitionIndex() int32 {
	if m != nil {
		return m.PartitionIndex
	}
	return 0
}

func (m *UpdateMetadataPartitionState) GetLeader() int32 {
	if m != nil {
		return m.Leader
	}
	return 0
}

func (m *UpdateMetadataPartitionState) GetIsr() []int32 {
	if m != nil {
		return m.Isr
	}
	return nil
}

func (m *UpdateMetadataPartitionState) GetReplicas() []int32 {
	if m != nil {
		return m.Replicas
	}
	return nil
}

func (m *UpdateMetadataPartitionState) GetOfflineReplicas() []int32 {
	if m != nil {
		return m.OfflineReplicas
	}
	return nil
}

type UpdateMetadataTopicState struct {
	TopicName            string                          `protobuf:"bytes,1,opt,name=topicName,proto3" json:"topicName,omitempty"`
	PartitionStates      []*UpdateMetadataPartitionState `protobuf:"bytes,2,rep,name=partitionStates,proto3" json:"partitionStates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *UpdateMetadataTopicState) Reset()         { *m = UpdateMetadataTopicState{} }
func (m *UpdateMetadataTopicState) String() string { return proto.CompactTextString(m) }
func (*UpdateMetadataTopicState) ProtoMessage()    {}
func (*UpdateMetadataTopicState) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbb28286b10953d7, []int{1}
}

func (m *UpdateMetadataTopicState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMetadataTopicState.Unmarshal(m, b)
}
func (m *UpdateMetadataTopicState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMetadataTopicState.Marshal(b, m, deterministic)
}
func (m *UpdateMetadataTopicState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMetadataTopicState.Merge(m, src)
}
func (m *UpdateMetadataTopicState) XXX_Size() int {
	return xxx_messageInfo_UpdateMetadataTopicState.Size(m)
}
func (m *UpdateMetadataTopicState) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMetadataTopicState.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMetadataTopicState proto.InternalMessageInfo

func (m *UpdateMetadataTopicState) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *UpdateMetadataTopicState) GetPartitionStates() []*UpdateMetadataPartitionState {
	if m != nil {
		return m.PartitionStates
	}
	return nil
}

type UpdateMetadataEndpoint struct {
	Port                 int32    `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateMetadataEndpoint) Reset()         { *m = UpdateMetadataEndpoint{} }
func (m *UpdateMetadataEndpoint) String() string { return proto.CompactTextString(m) }
func (*UpdateMetadataEndpoint) ProtoMessage()    {}
func (*UpdateMetadataEndpoint) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbb28286b10953d7, []int{2}
}

func (m *UpdateMetadataEndpoint) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMetadataEndpoint.Unmarshal(m, b)
}
func (m *UpdateMetadataEndpoint) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMetadataEndpoint.Marshal(b, m, deterministic)
}
func (m *UpdateMetadataEndpoint) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMetadataEndpoint.Merge(m, src)
}
func (m *UpdateMetadataEndpoint) XXX_Size() int {
	return xxx_messageInfo_UpdateMetadataEndpoint.Size(m)
}
func (m *UpdateMetadataEndpoint) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMetadataEndpoint.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMetadataEndpoint proto.InternalMessageInfo

func (m *UpdateMetadataEndpoint) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *UpdateMetadataEndpoint) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

type UpdateMetadataBroker struct {
	ID                   int32                     `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Host                 string                    `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32                     `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Endpoints            []*UpdateMetadataEndpoint `protobuf:"bytes,4,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *UpdateMetadataBroker) Reset()         { *m = UpdateMetadataBroker{} }
func (m *UpdateMetadataBroker) String() string { return proto.CompactTextString(m) }
func (*UpdateMetadataBroker) ProtoMessage()    {}
func (*UpdateMetadataBroker) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbb28286b10953d7, []int{3}
}

func (m *UpdateMetadataBroker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMetadataBroker.Unmarshal(m, b)
}
func (m *UpdateMetadataBroker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMetadataBroker.Marshal(b, m, deterministic)
}
func (m *UpdateMetadataBroker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMetadataBroker.Merge(m, src)
}
func (m *UpdateMetadataBroker) XXX_Size() int {
	return xxx_messageInfo_UpdateMetadataBroker.Size(m)
}
func (m *UpdateMetadataBroker) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMetadataBroker.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMetadataBroker proto.InternalMessageInfo

func (m *UpdateMetadataBroker) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *UpdateMetadataBroker) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *UpdateMetadataBroker) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *UpdateMetadataBroker) GetEndpoints() []*UpdateMetadataEndpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

type UpdateMetadataRequest struct {
	ControllerID         int32                       `protobuf:"varint,1,opt,name=controllerID,proto3" json:"controllerID,omitempty"`
	TopicStates          []*UpdateMetadataTopicState `protobuf:"bytes,2,rep,name=topicStates,proto3" json:"topicStates,omitempty"`
	LiveBrokers          []*UpdateMetadataBroker     `protobuf:"bytes,3,rep,name=liveBrokers,proto3" json:"liveBrokers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *UpdateMetadataRequest) Reset()         { *m = UpdateMetadataRequest{} }
func (m *UpdateMetadataRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateMetadataRequest) ProtoMessage()    {}
func (*UpdateMetadataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbb28286b10953d7, []int{4}
}

func (m *UpdateMetadataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMetadataRequest.Unmarshal(m, b)
}
func (m *UpdateMetadataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMetadataRequest.Marshal(b, m, deterministic)
}
func (m *UpdateMetadataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMetadataRequest.Merge(m, src)
}
func (m *UpdateMetadataRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateMetadataRequest.Size(m)
}
func (m *UpdateMetadataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMetadataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMetadataRequest proto.InternalMessageInfo

func (m *UpdateMetadataRequest) GetControllerID() int32 {
	if m != nil {
		return m.ControllerID
	}
	return 0
}

func (m *UpdateMetadataRequest) GetTopicStates() []*UpdateMetadataTopicState {
	if m != nil {
		return m.TopicStates
	}
	return nil
}

func (m *UpdateMetadataRequest) GetLiveBrokers() []*UpdateMetadataBroker {
	if m != nil {
		return m.LiveBrokers
	}
	return nil
}

type UpdateMetadataResponse struct {
	Response             *commonpb.Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *UpdateMetadataResponse) Reset()         { *m = UpdateMetadataResponse{} }
func (m *UpdateMetadataResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateMetadataResponse) ProtoMessage()    {}
func (*UpdateMetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fbb28286b10953d7, []int{5}
}

func (m *UpdateMetadataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateMetadataResponse.Unmarshal(m, b)
}
func (m *UpdateMetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateMetadataResponse.Marshal(b, m, deterministic)
}
func (m *UpdateMetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateMetadataResponse.Merge(m, src)
}
func (m *UpdateMetadataResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateMetadataResponse.Size(m)
}
func (m *UpdateMetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateMetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateMetadataResponse proto.InternalMessageInfo

func (m *UpdateMetadataResponse) GetResponse() *commonpb.Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterType((*UpdateMetadataPartitionState)(nil), "proto.adminclientpb.UpdateMetadataPartitionState")
	proto.RegisterType((*UpdateMetadataTopicState)(nil), "proto.adminclientpb.UpdateMetadataTopicState")
	proto.RegisterType((*UpdateMetadataEndpoint)(nil), "proto.adminclientpb.UpdateMetadataEndpoint")
	proto.RegisterType((*UpdateMetadataBroker)(nil), "proto.adminclientpb.UpdateMetadataBroker")
	proto.RegisterType((*UpdateMetadataRequest)(nil), "proto.adminclientpb.UpdateMetadataRequest")
	proto.RegisterType((*UpdateMetadataResponse)(nil), "proto.adminclientpb.UpdateMetadataResponse")
}

func init() {
	proto.RegisterFile("proto/adminclientpb/update_metadata.proto", fileDescriptor_fbb28286b10953d7)
}

var fileDescriptor_fbb28286b10953d7 = []byte{
	// 455 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0x55, 0x9a, 0xb5, 0xa2, 0x37, 0x68, 0x43, 0x06, 0x26, 0x33, 0x86, 0x54, 0xe5, 0x01, 0x65,
	0x42, 0xa4, 0xa2, 0xf0, 0x03, 0xd8, 0x34, 0x90, 0xaa, 0x8a, 0x81, 0x0c, 0xbc, 0xc0, 0x03, 0x72,
	0x93, 0x3b, 0x61, 0x91, 0xd8, 0xc6, 0xf6, 0x10, 0x7f, 0x84, 0x07, 0xfe, 0x17, 0x2f, 0xfc, 0x1b,
	0x54, 0xe7, 0xa3, 0x4d, 0x54, 0xa1, 0x3c, 0xf5, 0xfa, 0xf4, 0x9c, 0xe3, 0x7b, 0xcf, 0x8d, 0xe1,
	0x4c, 0x1b, 0xe5, 0xd4, 0x9c, 0xe7, 0xa5, 0x90, 0x59, 0x21, 0x50, 0x3a, 0xbd, 0x9e, 0xdf, 0xe8,
	0x9c, 0x3b, 0xfc, 0x52, 0xa2, 0xe3, 0x39, 0x77, 0x3c, 0xf5, 0x1c, 0x72, 0xd7, 0xff, 0xa4, 0x1d,
	0xea, 0xc9, 0xa3, 0x4a, 0x9f, 0xa9, 0xb2, 0x54, 0x52, 0xaf, 0xe7, 0x06, 0xad, 0x56, 0xd2, 0x62,
	0xa5, 0x89, 0xff, 0x04, 0x70, 0xfa, 0xd1, 0xbb, 0xbd, 0xa9, 0xcd, 0xde, 0x71, 0xe3, 0x84, 0x13,
	0x4a, 0xbe, 0x77, 0xdc, 0x21, 0x39, 0x85, 0xa9, 0x53, 0x5a, 0x64, 0x57, 0xbc, 0x44, 0x1a, 0xcc,
	0x82, 0x64, 0xca, 0xb6, 0x00, 0x79, 0x0c, 0x87, 0xba, 0xe1, 0x2f, 0x65, 0x8e, 0x3f, 0xe9, 0x68,
	0x16, 0x24, 0x63, 0xd6, 0x43, 0xc9, 0x31, 0x4c, 0x0a, 0xe4, 0x39, 0x1a, 0x1a, 0xfa, 0xff, 0xeb,
	0x13, 0xb9, 0x03, 0xa1, 0xb0, 0x86, 0x1e, 0xcc, 0xc2, 0x64, 0xcc, 0x36, 0x25, 0x39, 0x81, 0x5b,
	0x06, 0x75, 0x21, 0x32, 0x6e, 0xe9, 0xd8, 0xc3, 0xed, 0x99, 0x24, 0x70, 0xa4, 0xae, 0xaf, 0x0b,
	0x21, 0x91, 0x35, 0x94, 0x89, 0xa7, 0xf4, 0xe1, 0xf8, 0x57, 0x00, 0xb4, 0x3b, 0xd6, 0x87, 0x4d,
	0xcf, 0x43, 0x46, 0xfa, 0x0c, 0x47, 0xba, 0x13, 0x81, 0xa5, 0xa3, 0x59, 0x98, 0x44, 0x8b, 0x67,
	0xe9, 0x9e, 0x7c, 0xd3, 0xff, 0x85, 0xc7, 0xfa, 0x4e, 0xf1, 0x4b, 0x38, 0xee, 0x0a, 0x5e, 0xc9,
	0x5c, 0x2b, 0x21, 0x1d, 0x21, 0x70, 0xa0, 0x95, 0x71, 0xbe, 0x9f, 0x31, 0xf3, 0xf5, 0x06, 0xfb,
	0xaa, 0xac, 0xf3, 0x99, 0x4e, 0x99, 0xaf, 0xe3, 0xdf, 0x01, 0xdc, 0xeb, 0x5a, 0x5c, 0x18, 0xf5,
	0x0d, 0x0d, 0x39, 0x84, 0xd1, 0xf2, 0xb2, 0x96, 0x8f, 0x96, 0x97, 0xfb, 0xc4, 0xed, 0x25, 0xe1,
	0xce, 0x25, 0x4b, 0x98, 0x62, 0xdd, 0x84, 0xf5, 0x8b, 0x88, 0x16, 0x4f, 0x06, 0x4c, 0xda, 0x34,
	0xce, 0xb6, 0xea, 0xf8, 0x6f, 0x00, 0xf7, 0xbb, 0x2c, 0x86, 0xdf, 0x6f, 0xd0, 0x3a, 0x12, 0xc3,
	0xed, 0x4c, 0x49, 0x67, 0x54, 0x51, 0xa0, 0x69, 0xdb, 0xec, 0x60, 0xe4, 0x2d, 0x44, 0xae, 0x5d,
	0x52, 0x13, 0xfa, 0xd3, 0x01, 0xad, 0x6c, 0x57, 0xcb, 0x76, 0x1d, 0xc8, 0x0a, 0xa2, 0x42, 0xfc,
	0xc0, 0x2a, 0x1f, 0x4b, 0x43, 0x6f, 0x78, 0x36, 0xc0, 0xb0, 0x52, 0xb0, 0x5d, 0x75, 0x7c, 0xd5,
	0xdf, 0x1c, 0xab, 0x1f, 0x12, 0x79, 0xb1, 0xf9, 0x62, 0xab, 0xda, 0xcf, 0x15, 0x2d, 0x68, 0x7d,
	0x47, 0xf3, 0xe8, 0xd2, 0x86, 0xcb, 0x5a, 0xe6, 0xc5, 0xc3, 0x4f, 0x0f, 0xce, 0x57, 0xaf, 0xcf,
	0x57, 0xf3, 0x3d, 0xef, 0x7b, 0x3d, 0xf1, 0xe0, 0xf3, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x59,
	0x0e, 0x64, 0x31, 0xfd, 0x03, 0x00, 0x00,
}
