// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/commonpb/response.proto

package commonpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ResponseStatus int32

const (
	ResponseStatus_SUCCESS ResponseStatus = 0
	ResponseStatus_FAIL    ResponseStatus = 1
)

var ResponseStatus_name = map[int32]string{
	0: "SUCCESS",
	1: "FAIL",
}

var ResponseStatus_value = map[string]int32{
	"SUCCESS": 0,
	"FAIL":    1,
}

func (x ResponseStatus) String() string {
	return proto.EnumName(ResponseStatus_name, int32(x))
}

func (ResponseStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_acc93f5027f34a07, []int{0}
}

type ResponseMsg struct {
	Status               ResponseStatus `protobuf:"varint,1,opt,name=status,proto3,enum=proto.commonpb.ResponseStatus" json:"status,omitempty"`
	Message              string         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ResponseMsg) Reset()         { *m = ResponseMsg{} }
func (m *ResponseMsg) String() string { return proto.CompactTextString(m) }
func (*ResponseMsg) ProtoMessage()    {}
func (*ResponseMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_acc93f5027f34a07, []int{0}
}

func (m *ResponseMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseMsg.Unmarshal(m, b)
}
func (m *ResponseMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseMsg.Marshal(b, m, deterministic)
}
func (m *ResponseMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseMsg.Merge(m, src)
}
func (m *ResponseMsg) XXX_Size() int {
	return xxx_messageInfo_ResponseMsg.Size(m)
}
func (m *ResponseMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseMsg.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseMsg proto.InternalMessageInfo

func (m *ResponseMsg) GetStatus() ResponseStatus {
	if m != nil {
		return m.Status
	}
	return ResponseStatus_SUCCESS
}

func (m *ResponseMsg) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.commonpb.ResponseStatus", ResponseStatus_name, ResponseStatus_value)
	proto.RegisterType((*ResponseMsg)(nil), "proto.commonpb.ResponseMsg")
}

func init() {
	proto.RegisterFile("proto/commonpb/response.proto", fileDescriptor_acc93f5027f34a07)
}

var fileDescriptor_acc93f5027f34a07 = []byte{
	// 165 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0x2b, 0x48, 0xd2, 0x2f, 0x4a, 0x2d, 0x2e, 0xc8,
	0xcf, 0x2b, 0x4e, 0xd5, 0x03, 0x8b, 0x0b, 0xf1, 0x81, 0x29, 0x3d, 0x98, 0xb4, 0x52, 0x3c, 0x17,
	0x77, 0x10, 0x54, 0x85, 0x6f, 0x71, 0xba, 0x90, 0x19, 0x17, 0x5b, 0x71, 0x49, 0x62, 0x49, 0x69,
	0xb1, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x9f, 0x91, 0x9c, 0x1e, 0xaa, 0x7a, 0x3d, 0x98, 0xe2, 0x60,
	0xb0, 0xaa, 0x20, 0xa8, 0x6a, 0x21, 0x09, 0x2e, 0xf6, 0xdc, 0xd4, 0xe2, 0xe2, 0xc4, 0xf4, 0x54,
	0x09, 0x26, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x18, 0x57, 0x4b, 0x9d, 0x8b, 0x0f, 0x55, 0x8f, 0x10,
	0x37, 0x17, 0x7b, 0x70, 0xa8, 0xb3, 0xb3, 0x6b, 0x70, 0xb0, 0x00, 0x83, 0x10, 0x07, 0x17, 0x8b,
	0x9b, 0xa3, 0xa7, 0x8f, 0x00, 0xa3, 0x93, 0x58, 0x94, 0x88, 0xa3, 0xb7, 0x9b, 0xa3, 0xb7, 0x3e,
	0xaa, 0x07, 0x92, 0xd8, 0xc0, 0x7c, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf5, 0x72, 0xa7,
	0x49, 0xd9, 0x00, 0x00, 0x00,
}
