// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/consumepb/consume.proto

package consumepb

import (
	clustermetadatapb "AKFAK/proto/clustermetadatapb"
	recordpb "AKFAK/proto/recordpb"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConsumeRequest struct {
	GroupID              int32    `protobuf:"varint,1,opt,name=groupID,proto3" json:"groupID,omitempty"`
	ConsumerID           int32    `protobuf:"varint,2,opt,name=consumerID,proto3" json:"consumerID,omitempty"`
	Partition            int32    `protobuf:"varint,3,opt,name=partition,proto3" json:"partition,omitempty"`
	TopicName            string   `protobuf:"bytes,4,opt,name=topicName,proto3" json:"topicName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsumeRequest) Reset()         { *m = ConsumeRequest{} }
func (m *ConsumeRequest) String() string { return proto.CompactTextString(m) }
func (*ConsumeRequest) ProtoMessage()    {}
func (*ConsumeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a0fb7c1a5499aef, []int{0}
}

func (m *ConsumeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsumeRequest.Unmarshal(m, b)
}
func (m *ConsumeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsumeRequest.Marshal(b, m, deterministic)
}
func (m *ConsumeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumeRequest.Merge(m, src)
}
func (m *ConsumeRequest) XXX_Size() int {
	return xxx_messageInfo_ConsumeRequest.Size(m)
}
func (m *ConsumeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumeRequest proto.InternalMessageInfo

func (m *ConsumeRequest) GetGroupID() int32 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

func (m *ConsumeRequest) GetConsumerID() int32 {
	if m != nil {
		return m.ConsumerID
	}
	return 0
}

func (m *ConsumeRequest) GetPartition() int32 {
	if m != nil {
		return m.Partition
	}
	return 0
}

func (m *ConsumeRequest) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

type ConsumeResponse struct {
	TopicName            string                `protobuf:"bytes,1,opt,name=topicName,proto3" json:"topicName,omitempty"`
	Partition            int32                 `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	RecordSet            *recordpb.RecordBatch `protobuf:"bytes,3,opt,name=recordSet,proto3" json:"recordSet,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ConsumeResponse) Reset()         { *m = ConsumeResponse{} }
func (m *ConsumeResponse) String() string { return proto.CompactTextString(m) }
func (*ConsumeResponse) ProtoMessage()    {}
func (*ConsumeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a0fb7c1a5499aef, []int{1}
}

func (m *ConsumeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsumeResponse.Unmarshal(m, b)
}
func (m *ConsumeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsumeResponse.Marshal(b, m, deterministic)
}
func (m *ConsumeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumeResponse.Merge(m, src)
}
func (m *ConsumeResponse) XXX_Size() int {
	return xxx_messageInfo_ConsumeResponse.Size(m)
}
func (m *ConsumeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumeResponse proto.InternalMessageInfo

func (m *ConsumeResponse) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *ConsumeResponse) GetPartition() int32 {
	if m != nil {
		return m.Partition
	}
	return 0
}

func (m *ConsumeResponse) GetRecordSet() *recordpb.RecordBatch {
	if m != nil {
		return m.RecordSet
	}
	return nil
}

type GetAssignmentRequest struct {
	GroupID              int32    `protobuf:"varint,1,opt,name=groupID,proto3" json:"groupID,omitempty"`
	TopicName            string   `protobuf:"bytes,2,opt,name=topicName,proto3" json:"topicName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAssignmentRequest) Reset()         { *m = GetAssignmentRequest{} }
func (m *GetAssignmentRequest) String() string { return proto.CompactTextString(m) }
func (*GetAssignmentRequest) ProtoMessage()    {}
func (*GetAssignmentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a0fb7c1a5499aef, []int{2}
}

func (m *GetAssignmentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAssignmentRequest.Unmarshal(m, b)
}
func (m *GetAssignmentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAssignmentRequest.Marshal(b, m, deterministic)
}
func (m *GetAssignmentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAssignmentRequest.Merge(m, src)
}
func (m *GetAssignmentRequest) XXX_Size() int {
	return xxx_messageInfo_GetAssignmentRequest.Size(m)
}
func (m *GetAssignmentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAssignmentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAssignmentRequest proto.InternalMessageInfo

func (m *GetAssignmentRequest) GetGroupID() int32 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

func (m *GetAssignmentRequest) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

type MetadataAssignmenttate struct {
	TopicName      string `protobuf:"bytes,1,opt,name=topicName,proto3" json:"topicName,omitempty"`
	PartitionIndex int32  `protobuf:"varint,2,opt,name=partitionIndex,proto3" json:"partitionIndex,omitempty"`
	// broker holding replica that is assigned to consumer for that partition
	Broker               *clustermetadatapb.MetadataBroker `protobuf:"bytes,3,opt,name=broker,proto3" json:"broker,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *MetadataAssignmenttate) Reset()         { *m = MetadataAssignmenttate{} }
func (m *MetadataAssignmenttate) String() string { return proto.CompactTextString(m) }
func (*MetadataAssignmenttate) ProtoMessage()    {}
func (*MetadataAssignmenttate) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a0fb7c1a5499aef, []int{3}
}

func (m *MetadataAssignmenttate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetadataAssignmenttate.Unmarshal(m, b)
}
func (m *MetadataAssignmenttate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetadataAssignmenttate.Marshal(b, m, deterministic)
}
func (m *MetadataAssignmenttate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetadataAssignmenttate.Merge(m, src)
}
func (m *MetadataAssignmenttate) XXX_Size() int {
	return xxx_messageInfo_MetadataAssignmenttate.Size(m)
}
func (m *MetadataAssignmenttate) XXX_DiscardUnknown() {
	xxx_messageInfo_MetadataAssignmenttate.DiscardUnknown(m)
}

var xxx_messageInfo_MetadataAssignmenttate proto.InternalMessageInfo

func (m *MetadataAssignmenttate) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *MetadataAssignmenttate) GetPartitionIndex() int32 {
	if m != nil {
		return m.PartitionIndex
	}
	return 0
}

func (m *MetadataAssignmenttate) GetBroker() *clustermetadatapb.MetadataBroker {
	if m != nil {
		return m.Broker
	}
	return nil
}

type GetAssignmentResponse struct {
	// list of brokers holding isr for partition (excludes broker with assigned replica)
	// contacted when an assigned replica fails to respond
	IsrBrokers []*clustermetadatapb.MetadataBroker `protobuf:"bytes,1,rep,name=isrBrokers,proto3" json:"isrBrokers,omitempty"`
	// assigned Assignment. len(Assignment) == len(partitions)
	Assignments          []*MetadataAssignmenttate `protobuf:"bytes,2,rep,name=assignments,proto3" json:"assignments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *GetAssignmentResponse) Reset()         { *m = GetAssignmentResponse{} }
func (m *GetAssignmentResponse) String() string { return proto.CompactTextString(m) }
func (*GetAssignmentResponse) ProtoMessage()    {}
func (*GetAssignmentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a0fb7c1a5499aef, []int{4}
}

func (m *GetAssignmentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAssignmentResponse.Unmarshal(m, b)
}
func (m *GetAssignmentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAssignmentResponse.Marshal(b, m, deterministic)
}
func (m *GetAssignmentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAssignmentResponse.Merge(m, src)
}
func (m *GetAssignmentResponse) XXX_Size() int {
	return xxx_messageInfo_GetAssignmentResponse.Size(m)
}
func (m *GetAssignmentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAssignmentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAssignmentResponse proto.InternalMessageInfo

func (m *GetAssignmentResponse) GetIsrBrokers() []*clustermetadatapb.MetadataBroker {
	if m != nil {
		return m.IsrBrokers
	}
	return nil
}

func (m *GetAssignmentResponse) GetAssignments() []*MetadataAssignmenttate {
	if m != nil {
		return m.Assignments
	}
	return nil
}

func init() {
	proto.RegisterType((*ConsumeRequest)(nil), "proto.consumepb.ConsumeRequest")
	proto.RegisterType((*ConsumeResponse)(nil), "proto.consumepb.ConsumeResponse")
	proto.RegisterType((*GetAssignmentRequest)(nil), "proto.consumepb.GetAssignmentRequest")
	proto.RegisterType((*MetadataAssignmenttate)(nil), "proto.consumepb.MetadataAssignmenttate")
	proto.RegisterType((*GetAssignmentResponse)(nil), "proto.consumepb.GetAssignmentResponse")
}

func init() {
	proto.RegisterFile("proto/consumepb/consume.proto", fileDescriptor_0a0fb7c1a5499aef)
}

var fileDescriptor_0a0fb7c1a5499aef = []byte{
	// 372 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x25, 0x9d, 0x4e, 0x76, 0x07, 0x1b, 0x14, 0xa7, 0x65, 0x53, 0x19, 0x7d, 0xd0, 0x3d, 0x75,
	0xa0, 0x4f, 0x3e, 0xc9, 0xe6, 0x70, 0x94, 0xe1, 0x1e, 0xea, 0x9b, 0x2f, 0x92, 0x76, 0x61, 0x16,
	0x6d, 0x13, 0x93, 0x14, 0xfc, 0x02, 0xf1, 0x2f, 0xfc, 0x00, 0x7f, 0x52, 0x96, 0xa4, 0xed, 0x5a,
	0x85, 0xe1, 0x53, 0x6f, 0xcf, 0x3d, 0xf7, 0xe4, 0x9e, 0xd3, 0x14, 0x4e, 0x19, 0xa7, 0x92, 0x8e,
	0x23, 0x9a, 0x8a, 0x2c, 0x21, 0x2c, 0xcc, 0x2b, 0x4f, 0xe1, 0x76, 0x57, 0x3d, 0xbc, 0xa2, 0xdd,
	0x1f, 0x68, 0x3e, 0x27, 0x11, 0xe5, 0x2b, 0x16, 0x9a, 0x42, 0xb3, 0xfb, 0x9e, 0x11, 0x7b, 0xcd,
	0x84, 0x24, 0x3c, 0x21, 0x12, 0xaf, 0xb0, 0xc4, 0x1b, 0x51, 0x8d, 0x3c, 0xe5, 0x90, 0x26, 0xba,
	0x1f, 0x08, 0x3a, 0xb7, 0x5a, 0x3a, 0x20, 0x6f, 0x19, 0x11, 0xd2, 0x76, 0xe0, 0x60, 0xcd, 0x69,
	0xc6, 0xfc, 0x99, 0x83, 0x86, 0x68, 0xb4, 0x1f, 0xe4, 0xaf, 0xf6, 0x19, 0x80, 0x59, 0x83, 0xfb,
	0x33, 0xc7, 0x52, 0xcd, 0x2d, 0xc4, 0x3e, 0x81, 0x16, 0xc3, 0x5c, 0xc6, 0x32, 0xa6, 0xa9, 0xd3,
	0x50, 0xed, 0x12, 0xd8, 0x74, 0x25, 0x65, 0x71, 0xb4, 0xc4, 0x09, 0x71, 0xf6, 0x86, 0x68, 0xd4,
	0x0a, 0x4a, 0xc0, 0xfd, 0x44, 0xd0, 0x2d, 0x16, 0x11, 0x8c, 0xa6, 0x82, 0x54, 0x27, 0x50, 0x6d,
	0xa2, 0x7a, 0x9a, 0x55, 0x3f, 0xed, 0x1a, 0x5a, 0x3a, 0x98, 0x07, 0x22, 0xd5, 0x2e, 0xed, 0xcb,
	0x81, 0xf6, 0xec, 0xe5, 0xc9, 0x79, 0x81, 0x2a, 0xa6, 0x58, 0x46, 0xcf, 0x41, 0xc9, 0x76, 0x97,
	0x70, 0x38, 0x27, 0x72, 0x22, 0x44, 0xbc, 0x4e, 0x13, 0x92, 0xca, 0xdd, 0xc1, 0x54, 0x16, 0xb5,
	0xea, 0xd6, 0xbe, 0x10, 0x1c, 0xdd, 0x9b, 0xd8, 0x4b, 0x55, 0x89, 0xe5, 0x2e, 0x87, 0xe7, 0xd0,
	0x29, 0x0c, 0xf9, 0xe9, 0x8a, 0xbc, 0x1b, 0x9b, 0x35, 0xd4, 0xbe, 0x81, 0x66, 0xc8, 0xe9, 0x0b,
	0xe1, 0xc6, 0xe8, 0x85, 0x31, 0xfa, 0xeb, 0x16, 0x78, 0xf9, 0x1a, 0x53, 0x45, 0x0f, 0xcc, 0x98,
	0xfb, 0x8d, 0xa0, 0x57, 0xb3, 0x6c, 0x3e, 0xc1, 0x1c, 0x20, 0x16, 0x5c, 0xd3, 0x85, 0x83, 0x86,
	0x8d, 0xff, 0xc8, 0x6f, 0x8d, 0xda, 0x3e, 0xb4, 0x71, 0x21, 0x2f, 0x1c, 0xab, 0xaa, 0x94, 0x5f,
	0x6e, 0xef, 0xef, 0x9c, 0x82, 0xed, 0xd9, 0xe9, 0xf1, 0x63, 0x6f, 0xb2, 0xb8, 0x9b, 0x2c, 0xc6,
	0xb5, 0x1f, 0x27, 0x6c, 0x2a, 0xe0, 0xea, 0x27, 0x00, 0x00, 0xff, 0xff, 0x91, 0x33, 0x4c, 0xc5,
	0x52, 0x03, 0x00, 0x00,
}
