// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/consumepb/consume.proto

package consumepb

import (
	clustermetadatapb "AKFAK/proto/clustermetadatapb"
	recordpb "AKFAK/proto/recordpb"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ConsumeRequest struct {
	GroupID              int32    `protobuf:"varint,1,opt,name=groupID,proto3" json:"groupID,omitempty"`
	ConsumerID           int32    `protobuf:"varint,2,opt,name=consumerID,proto3" json:"consumerID,omitempty"`
	Partition            int32    `protobuf:"varint,3,opt,name=partition,proto3" json:"partition,omitempty"`
	TopicName            string   `protobuf:"bytes,4,opt,name=topicName,proto3" json:"topicName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsumeRequest) Reset()         { *m = ConsumeRequest{} }
func (m *ConsumeRequest) String() string { return proto.CompactTextString(m) }
func (*ConsumeRequest) ProtoMessage()    {}
func (*ConsumeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a0fb7c1a5499aef, []int{0}
}

func (m *ConsumeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsumeRequest.Unmarshal(m, b)
}
func (m *ConsumeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsumeRequest.Marshal(b, m, deterministic)
}
func (m *ConsumeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumeRequest.Merge(m, src)
}
func (m *ConsumeRequest) XXX_Size() int {
	return xxx_messageInfo_ConsumeRequest.Size(m)
}
func (m *ConsumeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumeRequest proto.InternalMessageInfo

func (m *ConsumeRequest) GetGroupID() int32 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

func (m *ConsumeRequest) GetConsumerID() int32 {
	if m != nil {
		return m.ConsumerID
	}
	return 0
}

func (m *ConsumeRequest) GetPartition() int32 {
	if m != nil {
		return m.Partition
	}
	return 0
}

func (m *ConsumeRequest) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

type ConsumeResponse struct {
	TopicName            string                `protobuf:"bytes,1,opt,name=topicName,proto3" json:"topicName,omitempty"`
	Partition            int32                 `protobuf:"varint,2,opt,name=partition,proto3" json:"partition,omitempty"`
	RecordSet            *recordpb.RecordBatch `protobuf:"bytes,3,opt,name=recordSet,proto3" json:"recordSet,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ConsumeResponse) Reset()         { *m = ConsumeResponse{} }
func (m *ConsumeResponse) String() string { return proto.CompactTextString(m) }
func (*ConsumeResponse) ProtoMessage()    {}
func (*ConsumeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a0fb7c1a5499aef, []int{1}
}

func (m *ConsumeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsumeResponse.Unmarshal(m, b)
}
func (m *ConsumeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsumeResponse.Marshal(b, m, deterministic)
}
func (m *ConsumeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsumeResponse.Merge(m, src)
}
func (m *ConsumeResponse) XXX_Size() int {
	return xxx_messageInfo_ConsumeResponse.Size(m)
}
func (m *ConsumeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsumeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConsumeResponse proto.InternalMessageInfo

func (m *ConsumeResponse) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *ConsumeResponse) GetPartition() int32 {
	if m != nil {
		return m.Partition
	}
	return 0
}

func (m *ConsumeResponse) GetRecordSet() *recordpb.RecordBatch {
	if m != nil {
		return m.RecordSet
	}
	return nil
}

type GetReplicasRequest struct {
	GroupID              int32    `protobuf:"varint,1,opt,name=groupID,proto3" json:"groupID,omitempty"`
	TopicName            string   `protobuf:"bytes,2,opt,name=topicName,proto3" json:"topicName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetReplicasRequest) Reset()         { *m = GetReplicasRequest{} }
func (m *GetReplicasRequest) String() string { return proto.CompactTextString(m) }
func (*GetReplicasRequest) ProtoMessage()    {}
func (*GetReplicasRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a0fb7c1a5499aef, []int{2}
}

func (m *GetReplicasRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReplicasRequest.Unmarshal(m, b)
}
func (m *GetReplicasRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReplicasRequest.Marshal(b, m, deterministic)
}
func (m *GetReplicasRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReplicasRequest.Merge(m, src)
}
func (m *GetReplicasRequest) XXX_Size() int {
	return xxx_messageInfo_GetReplicasRequest.Size(m)
}
func (m *GetReplicasRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReplicasRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetReplicasRequest proto.InternalMessageInfo

func (m *GetReplicasRequest) GetGroupID() int32 {
	if m != nil {
		return m.GroupID
	}
	return 0
}

func (m *GetReplicasRequest) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

type MetadataReplicaState struct {
	TopicName      string `protobuf:"bytes,1,opt,name=topicName,proto3" json:"topicName,omitempty"`
	PartitionIndex int32  `protobuf:"varint,2,opt,name=partitionIndex,proto3" json:"partitionIndex,omitempty"`
	// broker holding replica that is assigned to consumer for that partition
	Broker               *clustermetadatapb.MetadataBroker `protobuf:"bytes,3,opt,name=broker,proto3" json:"broker,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *MetadataReplicaState) Reset()         { *m = MetadataReplicaState{} }
func (m *MetadataReplicaState) String() string { return proto.CompactTextString(m) }
func (*MetadataReplicaState) ProtoMessage()    {}
func (*MetadataReplicaState) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a0fb7c1a5499aef, []int{3}
}

func (m *MetadataReplicaState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetadataReplicaState.Unmarshal(m, b)
}
func (m *MetadataReplicaState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetadataReplicaState.Marshal(b, m, deterministic)
}
func (m *MetadataReplicaState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetadataReplicaState.Merge(m, src)
}
func (m *MetadataReplicaState) XXX_Size() int {
	return xxx_messageInfo_MetadataReplicaState.Size(m)
}
func (m *MetadataReplicaState) XXX_DiscardUnknown() {
	xxx_messageInfo_MetadataReplicaState.DiscardUnknown(m)
}

var xxx_messageInfo_MetadataReplicaState proto.InternalMessageInfo

func (m *MetadataReplicaState) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

func (m *MetadataReplicaState) GetPartitionIndex() int32 {
	if m != nil {
		return m.PartitionIndex
	}
	return 0
}

func (m *MetadataReplicaState) GetBroker() *clustermetadatapb.MetadataBroker {
	if m != nil {
		return m.Broker
	}
	return nil
}

type GetReplicasResponse struct {
	// need to connect to controller to receive changes on replica assignments
	Controller *clustermetadatapb.MetadataBroker `protobuf:"bytes,1,opt,name=controller,proto3" json:"controller,omitempty"`
	// assigned replicas. len(replicas) == len(partitions)
	Replicas             []*MetadataReplicaState `protobuf:"bytes,2,rep,name=replicas,proto3" json:"replicas,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GetReplicasResponse) Reset()         { *m = GetReplicasResponse{} }
func (m *GetReplicasResponse) String() string { return proto.CompactTextString(m) }
func (*GetReplicasResponse) ProtoMessage()    {}
func (*GetReplicasResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0a0fb7c1a5499aef, []int{4}
}

func (m *GetReplicasResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetReplicasResponse.Unmarshal(m, b)
}
func (m *GetReplicasResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetReplicasResponse.Marshal(b, m, deterministic)
}
func (m *GetReplicasResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetReplicasResponse.Merge(m, src)
}
func (m *GetReplicasResponse) XXX_Size() int {
	return xxx_messageInfo_GetReplicasResponse.Size(m)
}
func (m *GetReplicasResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetReplicasResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetReplicasResponse proto.InternalMessageInfo

func (m *GetReplicasResponse) GetController() *clustermetadatapb.MetadataBroker {
	if m != nil {
		return m.Controller
	}
	return nil
}

func (m *GetReplicasResponse) GetReplicas() []*MetadataReplicaState {
	if m != nil {
		return m.Replicas
	}
	return nil
}

func init() {
	proto.RegisterType((*ConsumeRequest)(nil), "proto.consumepb.ConsumeRequest")
	proto.RegisterType((*ConsumeResponse)(nil), "proto.consumepb.ConsumeResponse")
	proto.RegisterType((*GetReplicasRequest)(nil), "proto.consumepb.GetReplicasRequest")
	proto.RegisterType((*MetadataReplicaState)(nil), "proto.consumepb.MetadataReplicaState")
	proto.RegisterType((*GetReplicasResponse)(nil), "proto.consumepb.GetReplicasResponse")
}

func init() {
	proto.RegisterFile("proto/consumepb/consume.proto", fileDescriptor_0a0fb7c1a5499aef)
}

var fileDescriptor_0a0fb7c1a5499aef = []byte{
	// 378 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xc1, 0x4a, 0xeb, 0x40,
	0x14, 0x65, 0xd2, 0xf7, 0xfa, 0x5e, 0xa7, 0xd0, 0x42, 0xde, 0x13, 0x43, 0xab, 0x52, 0x02, 0x6a,
	0x57, 0x53, 0xa8, 0x2b, 0x57, 0xd2, 0x5a, 0x2c, 0xa5, 0xea, 0x62, 0xba, 0x73, 0x23, 0x93, 0x74,
	0xd0, 0x60, 0x9a, 0x19, 0x27, 0x37, 0xe0, 0x17, 0x88, 0x3f, 0xe1, 0xc2, 0x3f, 0x95, 0xce, 0x4c,
	0xd2, 0x26, 0x0a, 0xc5, 0x55, 0x6e, 0xce, 0xbd, 0xf7, 0xcc, 0x39, 0x27, 0x13, 0x7c, 0x28, 0x95,
	0x00, 0x31, 0x08, 0x45, 0x92, 0x66, 0x2b, 0x2e, 0x83, 0xbc, 0x22, 0x1a, 0x77, 0xdb, 0xfa, 0x41,
	0x8a, 0x76, 0xa7, 0x6b, 0xe6, 0x15, 0x0f, 0x85, 0x5a, 0xca, 0xc0, 0x16, 0x66, 0xba, 0x43, 0x2c,
	0x59, 0x9c, 0xa5, 0xc0, 0xd5, 0x8a, 0x03, 0x5b, 0x32, 0x60, 0x6b, 0x52, 0x83, 0xdc, 0xe7, 0x90,
	0x19, 0xf4, 0x5f, 0x11, 0x6e, 0x5d, 0x1a, 0x6a, 0xca, 0x9f, 0x33, 0x9e, 0x82, 0xeb, 0xe1, 0x3f,
	0x0f, 0x4a, 0x64, 0x72, 0x36, 0xf1, 0x50, 0x0f, 0xf5, 0x7f, 0xd3, 0xfc, 0xd5, 0x3d, 0xc2, 0xd8,
	0xca, 0x50, 0xb3, 0x89, 0xe7, 0xe8, 0xe6, 0x16, 0xe2, 0x1e, 0xe0, 0x86, 0x64, 0x0a, 0x22, 0x88,
	0x44, 0xe2, 0xd5, 0x74, 0x7b, 0x03, 0xac, 0xbb, 0x20, 0x64, 0x14, 0xde, 0xb2, 0x15, 0xf7, 0x7e,
	0xf5, 0x50, 0xbf, 0x41, 0x37, 0x80, 0xff, 0x86, 0x70, 0xbb, 0x10, 0x92, 0x4a, 0x91, 0xa4, 0xbc,
	0xbc, 0x81, 0x2a, 0x1b, 0xe5, 0xd3, 0x9c, 0xea, 0x69, 0xe7, 0xb8, 0x61, 0x82, 0x59, 0x70, 0xd0,
	0x5a, 0x9a, 0xc3, 0xae, 0xf1, 0x4c, 0xf2, 0xe4, 0x08, 0xd5, 0xc5, 0x98, 0x41, 0xf8, 0x48, 0x37,
	0xd3, 0xfe, 0x35, 0x76, 0xa7, 0x1c, 0x28, 0x97, 0x71, 0x14, 0xb2, 0x74, 0x77, 0x2c, 0x25, 0x99,
	0x4e, 0xd5, 0xd8, 0x3b, 0xc2, 0xff, 0x6f, 0x6c, 0xe8, 0x96, 0x73, 0x01, 0x0c, 0x76, 0xb9, 0x3b,
	0xc1, 0xad, 0xc2, 0xcc, 0x2c, 0x59, 0xf2, 0x17, 0x6b, 0xb1, 0x82, 0xba, 0x17, 0xb8, 0x1e, 0x28,
	0xf1, 0xc4, 0x95, 0x35, 0x79, 0x6a, 0x4d, 0x7e, 0xb9, 0x01, 0x24, 0x17, 0x31, 0xd6, 0xe3, 0xd4,
	0xae, 0xf9, 0x1f, 0x08, 0xff, 0x2b, 0xd9, 0xb5, 0xe1, 0x4f, 0xf5, 0xc7, 0x06, 0x25, 0xe2, 0x98,
	0x2b, 0xad, 0xef, 0x07, 0xe4, 0x5b, 0xab, 0xee, 0x08, 0xff, 0x55, 0x96, 0xdc, 0x73, 0x7a, 0xb5,
	0x7e, 0x73, 0x78, 0x4c, 0x2a, 0x77, 0x9a, 0x7c, 0x17, 0x10, 0x2d, 0xd6, 0xc6, 0xfb, 0x77, 0x7b,
	0xa3, 0xf9, 0xd5, 0x68, 0x3e, 0xa8, 0xfc, 0x2a, 0x41, 0x5d, 0x03, 0x67, 0x9f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0xbf, 0x36, 0xd4, 0x87, 0x44, 0x03, 0x00, 0x00,
}
