// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/clientpb/client.proto

package clientpb

import (
	messagepb "AKFAK/proto/messagepb"
	metadatapb "AKFAK/proto/metadatapb"
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() {
	proto.RegisterFile("proto/clientpb/client.proto", fileDescriptor_e0b4fa04edbad8e6)
}

var fileDescriptor_e0b4fa04edbad8e6 = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2e, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xce, 0xc9, 0x4c, 0xcd, 0x2b, 0x29, 0x48, 0x82, 0x32, 0xf4, 0xc0, 0xa2, 0x42,
	0x7c, 0x60, 0x4a, 0x0f, 0x26, 0x29, 0x25, 0x0b, 0x51, 0x9c, 0x9b, 0x5a, 0x5c, 0x9c, 0x98, 0x9e,
	0x5a, 0x90, 0x04, 0x63, 0x41, 0x94, 0x4b, 0xc9, 0xc3, 0xa4, 0x4b, 0x12, 0x53, 0x12, 0x4b, 0x12,
	0xc1, 0xf2, 0x10, 0x26, 0x44, 0x81, 0xd1, 0x59, 0x46, 0x2e, 0x5e, 0x67, 0xb0, 0x61, 0xc1, 0xa9,
	0x45, 0x65, 0x99, 0xc9, 0xa9, 0x42, 0x89, 0x5c, 0x3c, 0xbe, 0x10, 0x33, 0x9c, 0x12, 0x4b, 0x92,
	0x33, 0x84, 0x54, 0x20, 0x2a, 0xf5, 0xe0, 0x56, 0xe8, 0x21, 0x4b, 0x07, 0xa5, 0x16, 0x96, 0xa6,
	0x16, 0x97, 0x48, 0xa9, 0x12, 0x50, 0x55, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0xaa, 0xc4, 0xa0, 0xc1,
	0x68, 0xc0, 0x28, 0x14, 0xc9, 0xc5, 0x17, 0x9e, 0x98, 0x59, 0xe2, 0x9f, 0xe7, 0x0b, 0x75, 0x8c,
	0x90, 0x22, 0x5c, 0x3b, 0xcc, 0xa1, 0x7a, 0x30, 0x39, 0x98, 0x0d, 0x4a, 0xf8, 0x94, 0xc0, 0x8c,
	0x77, 0x12, 0x8b, 0x12, 0x71, 0xf4, 0x76, 0x73, 0xf4, 0xd6, 0x47, 0x0d, 0xc4, 0x24, 0x36, 0x30,
	0xdf, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x16, 0xee, 0xc8, 0x29, 0x5d, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ClientServiceClient is the client API for ClientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClientServiceClient interface {
	// Producer RPC
	MessageBatch(ctx context.Context, opts ...grpc.CallOption) (ClientService_MessageBatchClient, error)
	WaitOnMetadata(ctx context.Context, in *metadatapb.MetadataRequest, opts ...grpc.CallOption) (*metadatapb.MetadataResponse, error)
}

type clientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClientServiceClient(cc grpc.ClientConnInterface) ClientServiceClient {
	return &clientServiceClient{cc}
}

func (c *clientServiceClient) MessageBatch(ctx context.Context, opts ...grpc.CallOption) (ClientService_MessageBatchClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ClientService_serviceDesc.Streams[0], "/proto.clientpb.ClientService/MessageBatch", opts...)
	if err != nil {
		return nil, err
	}
	x := &clientServiceMessageBatchClient{stream}
	return x, nil
}

type ClientService_MessageBatchClient interface {
	Send(*messagepb.MessageBatchRequest) error
	Recv() (*messagepb.MessageBatchResponse, error)
	grpc.ClientStream
}

type clientServiceMessageBatchClient struct {
	grpc.ClientStream
}

func (x *clientServiceMessageBatchClient) Send(m *messagepb.MessageBatchRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *clientServiceMessageBatchClient) Recv() (*messagepb.MessageBatchResponse, error) {
	m := new(messagepb.MessageBatchResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *clientServiceClient) WaitOnMetadata(ctx context.Context, in *metadatapb.MetadataRequest, opts ...grpc.CallOption) (*metadatapb.MetadataResponse, error) {
	out := new(metadatapb.MetadataResponse)
	err := c.cc.Invoke(ctx, "/proto.clientpb.ClientService/WaitOnMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientServiceServer is the server API for ClientService service.
type ClientServiceServer interface {
	// Producer RPC
	MessageBatch(ClientService_MessageBatchServer) error
	WaitOnMetadata(context.Context, *metadatapb.MetadataRequest) (*metadatapb.MetadataResponse, error)
}

// UnimplementedClientServiceServer can be embedded to have forward compatible implementations.
type UnimplementedClientServiceServer struct {
}

func (*UnimplementedClientServiceServer) MessageBatch(srv ClientService_MessageBatchServer) error {
	return status.Errorf(codes.Unimplemented, "method MessageBatch not implemented")
}
func (*UnimplementedClientServiceServer) WaitOnMetadata(ctx context.Context, req *metadatapb.MetadataRequest) (*metadatapb.MetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WaitOnMetadata not implemented")
}

func RegisterClientServiceServer(s *grpc.Server, srv ClientServiceServer) {
	s.RegisterService(&_ClientService_serviceDesc, srv)
}

func _ClientService_MessageBatch_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ClientServiceServer).MessageBatch(&clientServiceMessageBatchServer{stream})
}

type ClientService_MessageBatchServer interface {
	Send(*messagepb.MessageBatchResponse) error
	Recv() (*messagepb.MessageBatchRequest, error)
	grpc.ServerStream
}

type clientServiceMessageBatchServer struct {
	grpc.ServerStream
}

func (x *clientServiceMessageBatchServer) Send(m *messagepb.MessageBatchResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *clientServiceMessageBatchServer) Recv() (*messagepb.MessageBatchRequest, error) {
	m := new(messagepb.MessageBatchRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _ClientService_WaitOnMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(metadatapb.MetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServiceServer).WaitOnMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.clientpb.ClientService/WaitOnMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServiceServer).WaitOnMetadata(ctx, req.(*metadatapb.MetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ClientService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.clientpb.ClientService",
	HandlerType: (*ClientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WaitOnMetadata",
			Handler:    _ClientService_WaitOnMetadata_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MessageBatch",
			Handler:       _ClientService_MessageBatch_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/clientpb/client.proto",
}
