// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/recordpb/record.proto

package recordpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Header struct {
	HeaderKeyLength      int32    `protobuf:"varint,1,opt,name=headerKeyLength,proto3" json:"headerKeyLength,omitempty"`
	HeaderKey            string   `protobuf:"bytes,2,opt,name=headerKey,proto3" json:"headerKey,omitempty"`
	HeaderValueLength    int32    `protobuf:"varint,3,opt,name=headerValueLength,proto3" json:"headerValueLength,omitempty"`
	Value                []byte   `protobuf:"bytes,4,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea920a3f23369c2d, []int{0}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetHeaderKeyLength() int32 {
	if m != nil {
		return m.HeaderKeyLength
	}
	return 0
}

func (m *Header) GetHeaderKey() string {
	if m != nil {
		return m.HeaderKey
	}
	return ""
}

func (m *Header) GetHeaderValueLength() int32 {
	if m != nil {
		return m.HeaderValueLength
	}
	return 0
}

func (m *Header) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type Record struct {
	Length               int32     `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	Attributes           int32     `protobuf:"varint,2,opt,name=attributes,proto3" json:"attributes,omitempty"`
	TimestampDelta       int32     `protobuf:"varint,3,opt,name=timestampDelta,proto3" json:"timestampDelta,omitempty"`
	OffsetDelta          int32     `protobuf:"varint,4,opt,name=offsetDelta,proto3" json:"offsetDelta,omitempty"`
	KeyLength            int32     `protobuf:"varint,5,opt,name=keyLength,proto3" json:"keyLength,omitempty"`
	Key                  []byte    `protobuf:"bytes,6,opt,name=key,proto3" json:"key,omitempty"`
	ValueLen             int32     `protobuf:"varint,7,opt,name=valueLen,proto3" json:"valueLen,omitempty"`
	Value                []byte    `protobuf:"bytes,8,opt,name=value,proto3" json:"value,omitempty"`
	Headers              []*Header `protobuf:"bytes,9,rep,name=Headers,proto3" json:"Headers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea920a3f23369c2d, []int{1}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *Record) GetAttributes() int32 {
	if m != nil {
		return m.Attributes
	}
	return 0
}

func (m *Record) GetTimestampDelta() int32 {
	if m != nil {
		return m.TimestampDelta
	}
	return 0
}

func (m *Record) GetOffsetDelta() int32 {
	if m != nil {
		return m.OffsetDelta
	}
	return 0
}

func (m *Record) GetKeyLength() int32 {
	if m != nil {
		return m.KeyLength
	}
	return 0
}

func (m *Record) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *Record) GetValueLen() int32 {
	if m != nil {
		return m.ValueLen
	}
	return 0
}

func (m *Record) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Record) GetHeaders() []*Header {
	if m != nil {
		return m.Headers
	}
	return nil
}

type RecordBatch struct {
	BaseOffset           int64 `protobuf:"varint,1,opt,name=baseOffset,proto3" json:"baseOffset,omitempty"`
	BatchLength          int32 `protobuf:"varint,2,opt,name=batchLength,proto3" json:"batchLength,omitempty"`
	PartitionLeaderEpoch int32 `protobuf:"varint,3,opt,name=partitionLeaderEpoch,proto3" json:"partitionLeaderEpoch,omitempty"`
	Magic                int32 `protobuf:"varint,4,opt,name=magic,proto3" json:"magic,omitempty"`
	Crc                  int32 `protobuf:"varint,5,opt,name=crc,proto3" json:"crc,omitempty"`
	Attributes           int32 `protobuf:"varint,6,opt,name=attributes,proto3" json:"attributes,omitempty"`
	// attributes
	//bit 0~2:
	//0: no compression
	//1: gzip
	//2: snappy
	//3: lz4
	//4: zstd
	//bit 3: timestampType
	//bit 4: isTransactional (0 means not transactional)
	//bit 5: isControlBatch (0 means not a control batch)
	//bit 6~15: unused
	LastOffsetDelta      int32     `protobuf:"varint,7,opt,name=lastOffsetDelta,proto3" json:"lastOffsetDelta,omitempty"`
	FirstTimestamp       int64     `protobuf:"varint,8,opt,name=firstTimestamp,proto3" json:"firstTimestamp,omitempty"`
	MaxTimestamp         int64     `protobuf:"varint,9,opt,name=maxTimestamp,proto3" json:"maxTimestamp,omitempty"`
	ProducerId           int64     `protobuf:"varint,10,opt,name=producerId,proto3" json:"producerId,omitempty"`
	ProducerEpoch        int32     `protobuf:"varint,11,opt,name=producerEpoch,proto3" json:"producerEpoch,omitempty"`
	BaseSequence         int32     `protobuf:"varint,12,opt,name=baseSequence,proto3" json:"baseSequence,omitempty"`
	Records              []*Record `protobuf:"bytes,13,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RecordBatch) Reset()         { *m = RecordBatch{} }
func (m *RecordBatch) String() string { return proto.CompactTextString(m) }
func (*RecordBatch) ProtoMessage()    {}
func (*RecordBatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea920a3f23369c2d, []int{2}
}

func (m *RecordBatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordBatch.Unmarshal(m, b)
}
func (m *RecordBatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordBatch.Marshal(b, m, deterministic)
}
func (m *RecordBatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordBatch.Merge(m, src)
}
func (m *RecordBatch) XXX_Size() int {
	return xxx_messageInfo_RecordBatch.Size(m)
}
func (m *RecordBatch) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordBatch.DiscardUnknown(m)
}

var xxx_messageInfo_RecordBatch proto.InternalMessageInfo

func (m *RecordBatch) GetBaseOffset() int64 {
	if m != nil {
		return m.BaseOffset
	}
	return 0
}

func (m *RecordBatch) GetBatchLength() int32 {
	if m != nil {
		return m.BatchLength
	}
	return 0
}

func (m *RecordBatch) GetPartitionLeaderEpoch() int32 {
	if m != nil {
		return m.PartitionLeaderEpoch
	}
	return 0
}

func (m *RecordBatch) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *RecordBatch) GetCrc() int32 {
	if m != nil {
		return m.Crc
	}
	return 0
}

func (m *RecordBatch) GetAttributes() int32 {
	if m != nil {
		return m.Attributes
	}
	return 0
}

func (m *RecordBatch) GetLastOffsetDelta() int32 {
	if m != nil {
		return m.LastOffsetDelta
	}
	return 0
}

func (m *RecordBatch) GetFirstTimestamp() int64 {
	if m != nil {
		return m.FirstTimestamp
	}
	return 0
}

func (m *RecordBatch) GetMaxTimestamp() int64 {
	if m != nil {
		return m.MaxTimestamp
	}
	return 0
}

func (m *RecordBatch) GetProducerId() int64 {
	if m != nil {
		return m.ProducerId
	}
	return 0
}

func (m *RecordBatch) GetProducerEpoch() int32 {
	if m != nil {
		return m.ProducerEpoch
	}
	return 0
}

func (m *RecordBatch) GetBaseSequence() int32 {
	if m != nil {
		return m.BaseSequence
	}
	return 0
}

func (m *RecordBatch) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

func init() {
	proto.RegisterType((*Header)(nil), "proto.recordpb.Header")
	proto.RegisterType((*Record)(nil), "proto.recordpb.Record")
	proto.RegisterType((*RecordBatch)(nil), "proto.recordpb.RecordBatch")
}

func init() {
	proto.RegisterFile("proto/recordpb/record.proto", fileDescriptor_ea920a3f23369c2d)
}

var fileDescriptor_ea920a3f23369c2d = []byte{
	// 464 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x53, 0xd1, 0x6a, 0x13, 0x41,
	0x14, 0x65, 0xbb, 0xcd, 0xb6, 0xb9, 0x49, 0x5b, 0x1d, 0x42, 0x18, 0x54, 0x64, 0x09, 0x22, 0xfb,
	0x20, 0xa9, 0xd4, 0x2f, 0x68, 0x51, 0x51, 0x52, 0x28, 0x8c, 0xe2, 0x83, 0x6f, 0xb3, 0x93, 0x9b,
	0x76, 0x69, 0x92, 0x5d, 0x67, 0x26, 0x62, 0xff, 0xc3, 0x67, 0xff, 0xcc, 0x7f, 0x29, 0x73, 0x67,
	0x36, 0xd9, 0xdd, 0xe6, 0x29, 0xf7, 0x9c, 0x7b, 0xd8, 0x39, 0xf7, 0x1c, 0x02, 0x2f, 0x2b, 0x5d,
	0xda, 0xf2, 0x5c, 0xa3, 0x2a, 0xf5, 0xbc, 0xca, 0xc3, 0x30, 0x25, 0x96, 0x9d, 0xd2, 0xcf, 0xb4,
	0x5e, 0x4e, 0xfe, 0x46, 0x90, 0x7c, 0x41, 0x39, 0x47, 0xcd, 0x32, 0x38, 0xbb, 0xa3, 0x69, 0x86,
	0x0f, 0xd7, 0xb8, 0xbe, 0xb5, 0x77, 0x3c, 0x4a, 0xa3, 0xac, 0x27, 0xba, 0x34, 0x7b, 0x05, 0xfd,
	0x2d, 0xc5, 0x0f, 0xd2, 0x28, 0xeb, 0x8b, 0x1d, 0xc1, 0xde, 0xc1, 0x73, 0x0f, 0x7e, 0xc8, 0xe5,
	0x06, 0xc3, 0x97, 0x62, 0xfa, 0xd2, 0xd3, 0x05, 0x1b, 0x41, 0x8f, 0x20, 0x3f, 0x4c, 0xa3, 0x6c,
	0x28, 0x3c, 0x98, 0xfc, 0x3b, 0x80, 0x44, 0x90, 0x47, 0x36, 0x86, 0x64, 0xd9, 0x74, 0x13, 0x10,
	0x7b, 0x0d, 0x20, 0xad, 0xd5, 0x45, 0xbe, 0xb1, 0x68, 0xc8, 0x45, 0x4f, 0x34, 0x18, 0xf6, 0x16,
	0x4e, 0x6d, 0xb1, 0x42, 0x63, 0xe5, 0xaa, 0xfa, 0x88, 0x4b, 0x2b, 0x83, 0x87, 0x0e, 0xcb, 0x52,
	0x18, 0x94, 0x8b, 0x85, 0x41, 0xeb, 0x45, 0x87, 0x24, 0x6a, 0x52, 0xee, 0xdc, 0xfb, 0x6d, 0x24,
	0x3d, 0xda, 0xef, 0x08, 0xf6, 0x0c, 0xe2, 0x7b, 0x7c, 0xe0, 0x09, 0xd9, 0x77, 0x23, 0x7b, 0x01,
	0xc7, 0xbf, 0xc3, 0x85, 0xfc, 0x88, 0xe4, 0x5b, 0xec, 0xce, 0xa5, 0x99, 0x1f, 0xfb, 0x73, 0x09,
	0xb0, 0xf7, 0x70, 0xe4, 0x4b, 0x30, 0xbc, 0x9f, 0xc6, 0xd9, 0xe0, 0x62, 0x3c, 0x6d, 0xf7, 0x34,
	0xf5, 0x6b, 0x51, 0xcb, 0x26, 0xff, 0x63, 0x18, 0xf8, 0x80, 0xae, 0xa4, 0x55, 0x94, 0x46, 0x2e,
	0x0d, 0xde, 0x90, 0x6d, 0x4a, 0x2a, 0x16, 0x0d, 0xc6, 0x5d, 0x99, 0x3b, 0x61, 0xb8, 0xc2, 0xc7,
	0xd5, 0xa4, 0xd8, 0x05, 0x8c, 0x2a, 0xa9, 0x6d, 0x61, 0x8b, 0x72, 0x7d, 0x4d, 0xaf, 0x7c, 0xaa,
	0x4a, 0x55, 0x37, 0xb7, 0x77, 0xe7, 0xae, 0x59, 0xc9, 0xdb, 0x42, 0x85, 0xd4, 0x3c, 0x70, 0x89,
	0x28, 0xad, 0x42, 0x52, 0x6e, 0xec, 0x74, 0x95, 0x3c, 0xe9, 0x2a, 0x83, 0xb3, 0xa5, 0x34, 0xf6,
	0xa6, 0xd1, 0x83, 0x0f, 0xae, 0x4b, 0xbb, 0x56, 0x17, 0x85, 0x36, 0xf6, 0x7b, 0x5d, 0x22, 0x05,
	0x19, 0x8b, 0x0e, 0xcb, 0x26, 0x30, 0x5c, 0xc9, 0x3f, 0x3b, 0x55, 0x9f, 0x54, 0x2d, 0xce, 0xb9,
	0xaa, 0x74, 0x39, 0xdf, 0x28, 0xd4, 0x5f, 0xe7, 0x1c, 0x7c, 0x66, 0x3b, 0x86, 0xbd, 0x81, 0x93,
	0x1a, 0xf9, 0x28, 0x06, 0xe4, 0xa9, 0x4d, 0xba, 0x97, 0x5c, 0xce, 0xdf, 0xf0, 0xd7, 0x06, 0xd7,
	0x0a, 0xf9, 0x90, 0x44, 0x2d, 0xce, 0xf5, 0xeb, 0x9b, 0x34, 0xfc, 0x64, 0x7f, 0xbf, 0xbe, 0x4b,
	0x51, 0xcb, 0xae, 0xc6, 0x3f, 0x47, 0x97, 0xb3, 0xcf, 0x97, 0xb3, 0xf3, 0xf6, 0x9f, 0x39, 0x4f,
	0x08, 0x7f, 0x78, 0x0c, 0x00, 0x00, 0xff, 0xff, 0x7e, 0xd0, 0x2e, 0x87, 0xe5, 0x03, 0x00, 0x00,
}
