// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/recordpb/record.proto

package recordpb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Record struct {
	Length     int32 `protobuf:"varint,1,opt,name=length,proto3" json:"length,omitempty"`
	Attributes int32 `protobuf:"varint,2,opt,name=attributes,proto3" json:"attributes,omitempty"`
	// attributes
	//bit 0~7: unused
	TimestampDelta       int32    `protobuf:"varint,3,opt,name=timestampDelta,proto3" json:"timestampDelta,omitempty"`
	OffsetDelta          int32    `protobuf:"varint,4,opt,name=offsetDelta,proto3" json:"offsetDelta,omitempty"`
	ValueLen             int32    `protobuf:"varint,5,opt,name=valueLen,proto3" json:"valueLen,omitempty"`
	Value                []byte   `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Record) Reset()         { *m = Record{} }
func (m *Record) String() string { return proto.CompactTextString(m) }
func (*Record) ProtoMessage()    {}
func (*Record) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea920a3f23369c2d, []int{0}
}

func (m *Record) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Record.Unmarshal(m, b)
}
func (m *Record) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Record.Marshal(b, m, deterministic)
}
func (m *Record) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Record.Merge(m, src)
}
func (m *Record) XXX_Size() int {
	return xxx_messageInfo_Record.Size(m)
}
func (m *Record) XXX_DiscardUnknown() {
	xxx_messageInfo_Record.DiscardUnknown(m)
}

var xxx_messageInfo_Record proto.InternalMessageInfo

func (m *Record) GetLength() int32 {
	if m != nil {
		return m.Length
	}
	return 0
}

func (m *Record) GetAttributes() int32 {
	if m != nil {
		return m.Attributes
	}
	return 0
}

func (m *Record) GetTimestampDelta() int32 {
	if m != nil {
		return m.TimestampDelta
	}
	return 0
}

func (m *Record) GetOffsetDelta() int32 {
	if m != nil {
		return m.OffsetDelta
	}
	return 0
}

func (m *Record) GetValueLen() int32 {
	if m != nil {
		return m.ValueLen
	}
	return 0
}

func (m *Record) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type RecordBatch struct {
	BaseOffset           int64  `protobuf:"varint,1,opt,name=baseOffset,proto3" json:"baseOffset,omitempty"`
	BatchLength          []byte `protobuf:"bytes,2,opt,name=batchLength,proto3" json:"batchLength,omitempty"`
	PartitionLeaderEpoch int32  `protobuf:"varint,3,opt,name=partitionLeaderEpoch,proto3" json:"partitionLeaderEpoch,omitempty"`
	Magic                int32  `protobuf:"varint,4,opt,name=magic,proto3" json:"magic,omitempty"`
	Crc                  int32  `protobuf:"varint,5,opt,name=crc,proto3" json:"crc,omitempty"`
	Attributes           int32  `protobuf:"varint,6,opt,name=attributes,proto3" json:"attributes,omitempty"`
	// attributes
	//bit 0~2:
	//0: no compression
	//1: gzip
	//2: snappy
	//3: lz4
	//4: zstd
	//bit 3: timestampType
	//bit 4: isTransactional (0 means not transactional)
	//bit 5: isControlBatch (0 means not a control batch)
	//bit 6~15: unused
	LastOffsetDelta      int32     `protobuf:"varint,7,opt,name=lastOffsetDelta,proto3" json:"lastOffsetDelta,omitempty"`
	FirstTimestamp       int64     `protobuf:"varint,8,opt,name=firstTimestamp,proto3" json:"firstTimestamp,omitempty"`
	MaxTimestamp         int64     `protobuf:"varint,9,opt,name=maxTimestamp,proto3" json:"maxTimestamp,omitempty"`
	Records              []*Record `protobuf:"bytes,10,rep,name=records,proto3" json:"records,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RecordBatch) Reset()         { *m = RecordBatch{} }
func (m *RecordBatch) String() string { return proto.CompactTextString(m) }
func (*RecordBatch) ProtoMessage()    {}
func (*RecordBatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_ea920a3f23369c2d, []int{1}
}

func (m *RecordBatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RecordBatch.Unmarshal(m, b)
}
func (m *RecordBatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RecordBatch.Marshal(b, m, deterministic)
}
func (m *RecordBatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RecordBatch.Merge(m, src)
}
func (m *RecordBatch) XXX_Size() int {
	return xxx_messageInfo_RecordBatch.Size(m)
}
func (m *RecordBatch) XXX_DiscardUnknown() {
	xxx_messageInfo_RecordBatch.DiscardUnknown(m)
}

var xxx_messageInfo_RecordBatch proto.InternalMessageInfo

func (m *RecordBatch) GetBaseOffset() int64 {
	if m != nil {
		return m.BaseOffset
	}
	return 0
}

func (m *RecordBatch) GetBatchLength() []byte {
	if m != nil {
		return m.BatchLength
	}
	return nil
}

func (m *RecordBatch) GetPartitionLeaderEpoch() int32 {
	if m != nil {
		return m.PartitionLeaderEpoch
	}
	return 0
}

func (m *RecordBatch) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *RecordBatch) GetCrc() int32 {
	if m != nil {
		return m.Crc
	}
	return 0
}

func (m *RecordBatch) GetAttributes() int32 {
	if m != nil {
		return m.Attributes
	}
	return 0
}

func (m *RecordBatch) GetLastOffsetDelta() int32 {
	if m != nil {
		return m.LastOffsetDelta
	}
	return 0
}

func (m *RecordBatch) GetFirstTimestamp() int64 {
	if m != nil {
		return m.FirstTimestamp
	}
	return 0
}

func (m *RecordBatch) GetMaxTimestamp() int64 {
	if m != nil {
		return m.MaxTimestamp
	}
	return 0
}

func (m *RecordBatch) GetRecords() []*Record {
	if m != nil {
		return m.Records
	}
	return nil
}

func init() {
	proto.RegisterType((*Record)(nil), "proto.recordpb.Record")
	proto.RegisterType((*RecordBatch)(nil), "proto.recordpb.RecordBatch")
}

func init() {
	proto.RegisterFile("proto/recordpb/record.proto", fileDescriptor_ea920a3f23369c2d)
}

var fileDescriptor_ea920a3f23369c2d = []byte{
	// 335 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x25, 0x8d, 0x4d, 0xeb, 0xb4, 0x54, 0x59, 0x4a, 0x59, 0x14, 0x24, 0xf4, 0x20, 0x39, 0xa5,
	0x52, 0xbf, 0xa0, 0x45, 0xbd, 0xb4, 0x50, 0x08, 0x9e, 0xbc, 0x6d, 0xd2, 0x6d, 0x1b, 0x48, 0xba,
	0x61, 0x77, 0x2a, 0x7e, 0x9c, 0x7f, 0xe5, 0x0f, 0x48, 0x66, 0x53, 0x4d, 0xa2, 0xa7, 0x9d, 0xf7,
	0xe6, 0xb1, 0xbc, 0xf7, 0x18, 0xb8, 0x2d, 0xb4, 0x42, 0x35, 0xd3, 0x32, 0x51, 0x7a, 0x5b, 0xc4,
	0xd5, 0x10, 0x12, 0xcb, 0x46, 0xf4, 0x84, 0xe7, 0xe5, 0xf4, 0xd3, 0x01, 0x2f, 0x22, 0xc0, 0x26,
	0xe0, 0x65, 0xf2, 0xb8, 0xc7, 0x03, 0x77, 0x7c, 0x27, 0xe8, 0x46, 0x15, 0x62, 0x77, 0x00, 0x02,
	0x51, 0xa7, 0xf1, 0x09, 0xa5, 0xe1, 0x1d, 0xda, 0xd5, 0x18, 0x76, 0x0f, 0x23, 0x4c, 0x73, 0x69,
	0x50, 0xe4, 0xc5, 0x93, 0xcc, 0x50, 0x70, 0x97, 0x34, 0x2d, 0x96, 0xf9, 0x30, 0x50, 0xbb, 0x9d,
	0x91, 0x68, 0x45, 0x17, 0x24, 0xaa, 0x53, 0xec, 0x06, 0xfa, 0xef, 0x22, 0x3b, 0xc9, 0xb5, 0x3c,
	0xf2, 0x2e, 0xad, 0x7f, 0x30, 0x1b, 0x43, 0x97, 0x66, 0xee, 0xf9, 0x4e, 0x30, 0x8c, 0x2c, 0x98,
	0x7e, 0x75, 0x60, 0x60, 0xed, 0x2f, 0x05, 0x26, 0xe4, 0x35, 0x16, 0x46, 0x6e, 0xe8, 0x53, 0xca,
	0xe1, 0x46, 0x35, 0xa6, 0xf4, 0x10, 0x97, 0xc2, 0xb5, 0x0d, 0xda, 0xa1, 0xbf, 0xea, 0x14, 0x9b,
	0xc3, 0xb8, 0x10, 0x1a, 0x53, 0x4c, 0xd5, 0x71, 0x2d, 0xc5, 0x56, 0xea, 0xe7, 0x42, 0x25, 0x87,
	0x2a, 0xd3, 0xbf, 0xbb, 0xd2, 0x5b, 0x2e, 0xf6, 0x69, 0x52, 0x65, 0xb2, 0x80, 0x5d, 0x83, 0x9b,
	0xe8, 0xa4, 0x0a, 0x52, 0x8e, 0xad, 0x26, 0xbd, 0x3f, 0x4d, 0x06, 0x70, 0x95, 0x09, 0x83, 0x9b,
	0x5a, 0x4b, 0x3d, 0x12, 0xb5, 0xe9, 0xb2, 0xf3, 0x5d, 0xaa, 0x0d, 0xbe, 0x9e, 0x2b, 0xe6, 0x7d,
	0xca, 0xda, 0x62, 0xd9, 0x14, 0x86, 0xb9, 0xf8, 0xf8, 0x55, 0x5d, 0x92, 0xaa, 0xc1, 0xb1, 0x07,
	0xe8, 0xd9, 0x73, 0x30, 0x1c, 0x7c, 0x37, 0x18, 0xcc, 0x27, 0x61, 0xf3, 0x48, 0x42, 0xdb, 0x70,
	0x74, 0x96, 0x2d, 0x27, 0x6f, 0xe3, 0xc5, 0xea, 0x65, 0xb1, 0x9a, 0x35, 0x2f, 0x2d, 0xf6, 0x08,
	0x3f, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0xbf, 0x35, 0xed, 0x7b, 0x82, 0x02, 0x00, 0x00,
}
