// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/metadatapb/metadata.proto

package metadatapb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MetadataRequest struct {
	TopicNames           []string `protobuf:"bytes,1,rep,name=topicNames,proto3" json:"topicNames,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetadataRequest) Reset()         { *m = MetadataRequest{} }
func (m *MetadataRequest) String() string { return proto.CompactTextString(m) }
func (*MetadataRequest) ProtoMessage()    {}
func (*MetadataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62d81771a13bf91c, []int{0}
}

func (m *MetadataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetadataRequest.Unmarshal(m, b)
}
func (m *MetadataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetadataRequest.Marshal(b, m, deterministic)
}
func (m *MetadataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetadataRequest.Merge(m, src)
}
func (m *MetadataRequest) XXX_Size() int {
	return xxx_messageInfo_MetadataRequest.Size(m)
}
func (m *MetadataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MetadataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MetadataRequest proto.InternalMessageInfo

func (m *MetadataRequest) GetTopicNames() []string {
	if m != nil {
		return m.TopicNames
	}
	return nil
}

type MetadataResponse struct {
	Brokers              []*Broker `protobuf:"bytes,1,rep,name=brokers,proto3" json:"brokers,omitempty"`
	Topics               []*Topic  `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MetadataResponse) Reset()         { *m = MetadataResponse{} }
func (m *MetadataResponse) String() string { return proto.CompactTextString(m) }
func (*MetadataResponse) ProtoMessage()    {}
func (*MetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_62d81771a13bf91c, []int{1}
}

func (m *MetadataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetadataResponse.Unmarshal(m, b)
}
func (m *MetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetadataResponse.Marshal(b, m, deterministic)
}
func (m *MetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetadataResponse.Merge(m, src)
}
func (m *MetadataResponse) XXX_Size() int {
	return xxx_messageInfo_MetadataResponse.Size(m)
}
func (m *MetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MetadataResponse proto.InternalMessageInfo

func (m *MetadataResponse) GetBrokers() []*Broker {
	if m != nil {
		return m.Brokers
	}
	return nil
}

func (m *MetadataResponse) GetTopics() []*Topic {
	if m != nil {
		return m.Topics
	}
	return nil
}

type Broker struct {
	NodeID               int32    `protobuf:"varint,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32    `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Broker) Reset()         { *m = Broker{} }
func (m *Broker) String() string { return proto.CompactTextString(m) }
func (*Broker) ProtoMessage()    {}
func (*Broker) Descriptor() ([]byte, []int) {
	return fileDescriptor_62d81771a13bf91c, []int{2}
}

func (m *Broker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Broker.Unmarshal(m, b)
}
func (m *Broker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Broker.Marshal(b, m, deterministic)
}
func (m *Broker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Broker.Merge(m, src)
}
func (m *Broker) XXX_Size() int {
	return xxx_messageInfo_Broker.Size(m)
}
func (m *Broker) XXX_DiscardUnknown() {
	xxx_messageInfo_Broker.DiscardUnknown(m)
}

var xxx_messageInfo_Broker proto.InternalMessageInfo

func (m *Broker) GetNodeID() int32 {
	if m != nil {
		return m.NodeID
	}
	return 0
}

func (m *Broker) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Broker) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type Topic struct {
	ErrorCode            int32        `protobuf:"varint,1,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Name                 string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Partitions           []*Partition `protobuf:"bytes,3,rep,name=partitions,proto3" json:"partitions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Topic) Reset()         { *m = Topic{} }
func (m *Topic) String() string { return proto.CompactTextString(m) }
func (*Topic) ProtoMessage()    {}
func (*Topic) Descriptor() ([]byte, []int) {
	return fileDescriptor_62d81771a13bf91c, []int{3}
}

func (m *Topic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Topic.Unmarshal(m, b)
}
func (m *Topic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Topic.Marshal(b, m, deterministic)
}
func (m *Topic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Topic.Merge(m, src)
}
func (m *Topic) XXX_Size() int {
	return xxx_messageInfo_Topic.Size(m)
}
func (m *Topic) XXX_DiscardUnknown() {
	xxx_messageInfo_Topic.DiscardUnknown(m)
}

var xxx_messageInfo_Topic proto.InternalMessageInfo

func (m *Topic) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *Topic) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Topic) GetPartitions() []*Partition {
	if m != nil {
		return m.Partitions
	}
	return nil
}

type Partition struct {
	ErrorCode      int32 `protobuf:"varint,1,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	PartitionIndex int32 `protobuf:"varint,2,opt,name=partitionIndex,proto3" json:"partitionIndex,omitempty"`
	LeaderID       int32 `protobuf:"varint,3,opt,name=leaderID,proto3" json:"leaderID,omitempty"`
	//
	//leader represents the node id for the kafka broker current acting as the leader
	//for this partition. If no leader exists because system is in the middle of a
	//leader election, this id will be -1
	ReplicaNodes []int32 `protobuf:"varint,4,rep,packed,name=replicaNodes,proto3" json:"replicaNodes,omitempty"`
	// set of alive nodes that current act as slaves for the leader for this partition
	IsrNodes             []int32  `protobuf:"varint,5,rep,packed,name=isrNodes,proto3" json:"isrNodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Partition) Reset()         { *m = Partition{} }
func (m *Partition) String() string { return proto.CompactTextString(m) }
func (*Partition) ProtoMessage()    {}
func (*Partition) Descriptor() ([]byte, []int) {
	return fileDescriptor_62d81771a13bf91c, []int{4}
}

func (m *Partition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Partition.Unmarshal(m, b)
}
func (m *Partition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Partition.Marshal(b, m, deterministic)
}
func (m *Partition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Partition.Merge(m, src)
}
func (m *Partition) XXX_Size() int {
	return xxx_messageInfo_Partition.Size(m)
}
func (m *Partition) XXX_DiscardUnknown() {
	xxx_messageInfo_Partition.DiscardUnknown(m)
}

var xxx_messageInfo_Partition proto.InternalMessageInfo

func (m *Partition) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *Partition) GetPartitionIndex() int32 {
	if m != nil {
		return m.PartitionIndex
	}
	return 0
}

func (m *Partition) GetLeaderID() int32 {
	if m != nil {
		return m.LeaderID
	}
	return 0
}

func (m *Partition) GetReplicaNodes() []int32 {
	if m != nil {
		return m.ReplicaNodes
	}
	return nil
}

func (m *Partition) GetIsrNodes() []int32 {
	if m != nil {
		return m.IsrNodes
	}
	return nil
}

// The request message containing the user's name.
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62d81771a13bf91c, []int{5}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_62d81771a13bf91c, []int{6}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*MetadataRequest)(nil), "proto.metadatapb.MetadataRequest")
	proto.RegisterType((*MetadataResponse)(nil), "proto.metadatapb.MetadataResponse")
	proto.RegisterType((*Broker)(nil), "proto.metadatapb.Broker")
	proto.RegisterType((*Topic)(nil), "proto.metadatapb.Topic")
	proto.RegisterType((*Partition)(nil), "proto.metadatapb.Partition")
	proto.RegisterType((*HelloRequest)(nil), "proto.metadatapb.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "proto.metadatapb.HelloReply")
}

func init() {
	proto.RegisterFile("proto/metadatapb/metadata.proto", fileDescriptor_62d81771a13bf91c)
}

var fileDescriptor_62d81771a13bf91c = []byte{
	// 424 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x4f, 0x6f, 0xd3, 0x30,
	0x14, 0x5f, 0xd6, 0xa5, 0x5b, 0xdf, 0x26, 0x98, 0xde, 0x61, 0x58, 0x65, 0x1a, 0xc5, 0x87, 0xa9,
	0xa7, 0x56, 0x94, 0x23, 0xa7, 0x8d, 0x09, 0x56, 0x26, 0x26, 0xe4, 0x21, 0x0e, 0xdc, 0xdc, 0xe6,
	0x09, 0x22, 0x92, 0xd8, 0xd8, 0x66, 0xd0, 0x0f, 0xc5, 0x91, 0xef, 0x87, 0xe2, 0xc4, 0x49, 0x49,
	0x04, 0x9c, 0xf2, 0xde, 0xef, 0x9f, 0x9f, 0xad, 0x17, 0x78, 0xa2, 0x8d, 0x72, 0x6a, 0x9e, 0x93,
	0x93, 0x89, 0x74, 0x52, 0xaf, 0x9a, 0x72, 0xe6, 0x19, 0x3c, 0xf6, 0x9f, 0x59, 0x2b, 0xe0, 0xcf,
	0xe0, 0xe1, 0xdb, 0xba, 0x13, 0xf4, 0xf5, 0x1b, 0x59, 0x87, 0x67, 0x00, 0x4e, 0xe9, 0x74, 0x7d,
	0x2b, 0x73, 0xb2, 0x2c, 0x9a, 0x0c, 0xa6, 0x23, 0xb1, 0x85, 0xf0, 0xef, 0x70, 0xdc, 0x5a, 0xac,
	0x56, 0x85, 0x25, 0x5c, 0xc0, 0xfe, 0xca, 0xa8, 0x2f, 0x64, 0x2a, 0xc3, 0xe1, 0x82, 0xcd, 0xba,
	0x47, 0xcd, 0x2e, 0xbd, 0x40, 0x04, 0x21, 0xce, 0x61, 0xe8, 0x53, 0x2d, 0xdb, 0xf5, 0x96, 0x47,
	0x7d, 0xcb, 0xfb, 0x92, 0x17, 0xb5, 0x8c, 0x5f, 0xc3, 0xb0, 0xca, 0xc0, 0x13, 0x18, 0x16, 0x2a,
	0xa1, 0xe5, 0x15, 0x8b, 0x26, 0xd1, 0x34, 0x16, 0x75, 0x87, 0x08, 0x7b, 0x9f, 0x95, 0x75, 0x6c,
	0x77, 0x12, 0x4d, 0x47, 0xc2, 0xd7, 0x25, 0xa6, 0x95, 0x71, 0x6c, 0xe0, 0x95, 0xbe, 0xe6, 0xf7,
	0x10, 0xfb, 0x68, 0x3c, 0x85, 0x11, 0x19, 0xa3, 0xcc, 0x4b, 0x95, 0x50, 0x9d, 0xd5, 0x02, 0xa5,
	0xb5, 0x90, 0x39, 0x85, 0xb8, 0xb2, 0xc6, 0x17, 0x00, 0x5a, 0x1a, 0x97, 0xba, 0x54, 0x15, 0x96,
	0x0d, 0xfc, 0xe4, 0x8f, 0xfb, 0x93, 0xbf, 0x0b, 0x1a, 0xb1, 0x25, 0xe7, 0x3f, 0x23, 0x18, 0x35,
	0xcc, 0x7f, 0x0e, 0x3f, 0x87, 0x07, 0x8d, 0x73, 0x59, 0x24, 0xf4, 0xc3, 0x8f, 0x11, 0x8b, 0x0e,
	0x8a, 0x63, 0x38, 0xc8, 0x48, 0x26, 0x64, 0x96, 0x57, 0xf5, 0x1d, 0x9b, 0x1e, 0x39, 0x1c, 0x19,
	0xd2, 0x59, 0xba, 0x96, 0xb7, 0x2a, 0x21, 0xcb, 0xf6, 0x26, 0x83, 0x69, 0x2c, 0xfe, 0xc0, 0x4a,
	0x7f, 0x6a, 0x4d, 0xc5, 0xc7, 0x9e, 0x6f, 0x7a, 0xce, 0xe1, 0xe8, 0x9a, 0xb2, 0x4c, 0x85, 0xd5,
	0x08, 0x0f, 0x12, 0xb5, 0x0f, 0xc2, 0xcf, 0x01, 0x6a, 0x8d, 0xce, 0x36, 0xc8, 0x60, 0x3f, 0x27,
	0x6b, 0xe5, 0xa7, 0x20, 0x0a, 0xed, 0xe2, 0x57, 0xd4, 0xae, 0xda, 0x1d, 0x99, 0xfb, 0x74, 0x4d,
	0xf8, 0x01, 0x0e, 0x5f, 0x93, 0x0b, 0x28, 0x3e, 0xed, 0xbf, 0x63, 0x67, 0x39, 0xc7, 0xfc, 0x5f,
	0x92, 0x6a, 0x19, 0xf9, 0x0e, 0xbe, 0x81, 0x83, 0x3b, 0xb9, 0xf1, 0x63, 0xe1, 0x59, 0xdf, 0xb1,
	0x7d, 0xa7, 0xf1, 0xe9, 0x5f, 0x79, 0x9d, 0x6d, 0xf8, 0xce, 0x25, 0xfb, 0x78, 0x72, 0x71, 0xf3,
	0xea, 0xe2, 0x66, 0xde, 0xfd, 0xb9, 0x56, 0x43, 0x8f, 0x3c, 0xff, 0x1d, 0x00, 0x00, 0xff, 0xff,
	0xed, 0x72, 0xc3, 0xf0, 0x77, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MetadataServiceClient is the client API for MetadataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MetadataServiceClient interface {
	GetMetadata(ctx context.Context, in *MetadataRequest, opts ...grpc.CallOption) (*MetadataResponse, error)
	// == Test to see if gRPC works; REMOVE LATER ==
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type metadataServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetadataServiceClient(cc grpc.ClientConnInterface) MetadataServiceClient {
	return &metadataServiceClient{cc}
}

func (c *metadataServiceClient) GetMetadata(ctx context.Context, in *MetadataRequest, opts ...grpc.CallOption) (*MetadataResponse, error) {
	out := new(MetadataResponse)
	err := c.cc.Invoke(ctx, "/proto.metadatapb.MetadataService/GetMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/proto.metadatapb.MetadataService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetadataServiceServer is the server API for MetadataService service.
type MetadataServiceServer interface {
	GetMetadata(context.Context, *MetadataRequest) (*MetadataResponse, error)
	// == Test to see if gRPC works; REMOVE LATER ==
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}

// UnimplementedMetadataServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMetadataServiceServer struct {
}

func (*UnimplementedMetadataServiceServer) GetMetadata(ctx context.Context, req *MetadataRequest) (*MetadataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetadata not implemented")
}
func (*UnimplementedMetadataServiceServer) SayHello(ctx context.Context, req *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}

func RegisterMetadataServiceServer(s *grpc.Server, srv MetadataServiceServer) {
	s.RegisterService(&_MetadataService_serviceDesc, srv)
}

func _MetadataService_GetMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.metadatapb.MetadataService/GetMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetMetadata(ctx, req.(*MetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.metadatapb.MetadataService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MetadataService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.metadatapb.MetadataService",
	HandlerType: (*MetadataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMetadata",
			Handler:    _MetadataService_GetMetadata_Handler,
		},
		{
			MethodName: "SayHello",
			Handler:    _MetadataService_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/metadatapb/metadata.proto",
}
