// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/metadatapb/metadata.proto

package metadatapb

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MetadataRequest struct {
	TopicName            string   `protobuf:"bytes,1,opt,name=topicName,proto3" json:"topicName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetadataRequest) Reset()         { *m = MetadataRequest{} }
func (m *MetadataRequest) String() string { return proto.CompactTextString(m) }
func (*MetadataRequest) ProtoMessage()    {}
func (*MetadataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_62d81771a13bf91c, []int{0}
}

func (m *MetadataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetadataRequest.Unmarshal(m, b)
}
func (m *MetadataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetadataRequest.Marshal(b, m, deterministic)
}
func (m *MetadataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetadataRequest.Merge(m, src)
}
func (m *MetadataRequest) XXX_Size() int {
	return xxx_messageInfo_MetadataRequest.Size(m)
}
func (m *MetadataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MetadataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MetadataRequest proto.InternalMessageInfo

func (m *MetadataRequest) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

type MetadataResponse struct {
	Brokers              []*Broker `protobuf:"bytes,1,rep,name=brokers,proto3" json:"brokers,omitempty"`
	Topic                *Topic    `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MetadataResponse) Reset()         { *m = MetadataResponse{} }
func (m *MetadataResponse) String() string { return proto.CompactTextString(m) }
func (*MetadataResponse) ProtoMessage()    {}
func (*MetadataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_62d81771a13bf91c, []int{1}
}

func (m *MetadataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetadataResponse.Unmarshal(m, b)
}
func (m *MetadataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetadataResponse.Marshal(b, m, deterministic)
}
func (m *MetadataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetadataResponse.Merge(m, src)
}
func (m *MetadataResponse) XXX_Size() int {
	return xxx_messageInfo_MetadataResponse.Size(m)
}
func (m *MetadataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MetadataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MetadataResponse proto.InternalMessageInfo

func (m *MetadataResponse) GetBroker() *Broker {
	if m != nil {
		return m.Broker
	}
	return nil
}

func (m *MetadataResponse) GetTopic() *Topic {
	if m != nil {
		return m.Topic
	}
	return nil
}

type Broker struct {
	NodeID               int32    `protobuf:"varint,1,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	Host                 string   `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Port                 int32    `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Broker) Reset()         { *m = Broker{} }
func (m *Broker) String() string { return proto.CompactTextString(m) }
func (*Broker) ProtoMessage()    {}
func (*Broker) Descriptor() ([]byte, []int) {
	return fileDescriptor_62d81771a13bf91c, []int{2}
}

func (m *Broker) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Broker.Unmarshal(m, b)
}
func (m *Broker) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Broker.Marshal(b, m, deterministic)
}
func (m *Broker) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Broker.Merge(m, src)
}
func (m *Broker) XXX_Size() int {
	return xxx_messageInfo_Broker.Size(m)
}
func (m *Broker) XXX_DiscardUnknown() {
	xxx_messageInfo_Broker.DiscardUnknown(m)
}

var xxx_messageInfo_Broker proto.InternalMessageInfo

func (m *Broker) GetNodeID() int32 {
	if m != nil {
		return m.NodeID
	}
	return 0
}

func (m *Broker) GetHost() string {
	if m != nil {
		return m.Host
	}
	return ""
}

func (m *Broker) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type Topic struct {
	ErrorCode            int32        `protobuf:"varint,1,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	Name                 string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Partitions           []*Partition `protobuf:"bytes,3,rep,name=partitions,proto3" json:"partitions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Topic) Reset()         { *m = Topic{} }
func (m *Topic) String() string { return proto.CompactTextString(m) }
func (*Topic) ProtoMessage()    {}
func (*Topic) Descriptor() ([]byte, []int) {
	return fileDescriptor_62d81771a13bf91c, []int{3}
}

func (m *Topic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Topic.Unmarshal(m, b)
}
func (m *Topic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Topic.Marshal(b, m, deterministic)
}
func (m *Topic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Topic.Merge(m, src)
}
func (m *Topic) XXX_Size() int {
	return xxx_messageInfo_Topic.Size(m)
}
func (m *Topic) XXX_DiscardUnknown() {
	xxx_messageInfo_Topic.DiscardUnknown(m)
}

var xxx_messageInfo_Topic proto.InternalMessageInfo

func (m *Topic) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *Topic) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Topic) GetPartitions() []*Partition {
	if m != nil {
		return m.Partitions
	}
	return nil
}

type Partition struct {
	ErrorCode      int32 `protobuf:"varint,1,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	PartitionIndex int32 `protobuf:"varint,2,opt,name=partitionIndex,proto3" json:"partitionIndex,omitempty"`
	LeaderID       int32 `protobuf:"varint,3,opt,name=leaderID,proto3" json:"leaderID,omitempty"`
	//
	//leader represents the node id for the kafka broker current acting as the
	//leader for this partition. If no leader exists because system is in the middle
	//of a leader election, this id will be -1
	ReplicaNodes []int32 `protobuf:"varint,4,rep,packed,name=replicaNodes,proto3" json:"replicaNodes,omitempty"`
	// set of alive nodes that current act as slaves for the leader for this
	// partition
	IsrNodes             []int32  `protobuf:"varint,5,rep,packed,name=isrNodes,proto3" json:"isrNodes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Partition) Reset()         { *m = Partition{} }
func (m *Partition) String() string { return proto.CompactTextString(m) }
func (*Partition) ProtoMessage()    {}
func (*Partition) Descriptor() ([]byte, []int) {
	return fileDescriptor_62d81771a13bf91c, []int{4}
}

func (m *Partition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Partition.Unmarshal(m, b)
}
func (m *Partition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Partition.Marshal(b, m, deterministic)
}
func (m *Partition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Partition.Merge(m, src)
}
func (m *Partition) XXX_Size() int {
	return xxx_messageInfo_Partition.Size(m)
}
func (m *Partition) XXX_DiscardUnknown() {
	xxx_messageInfo_Partition.DiscardUnknown(m)
}

var xxx_messageInfo_Partition proto.InternalMessageInfo

func (m *Partition) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *Partition) GetPartitionIndex() int32 {
	if m != nil {
		return m.PartitionIndex
	}
	return 0
}

func (m *Partition) GetLeaderID() int32 {
	if m != nil {
		return m.LeaderID
	}
	return 0
}

func (m *Partition) GetReplicaNodes() []int32 {
	if m != nil {
		return m.ReplicaNodes
	}
	return nil
}

func (m *Partition) GetIsrNodes() []int32 {
	if m != nil {
		return m.IsrNodes
	}
	return nil
}

func init() {
	proto.RegisterType((*MetadataRequest)(nil), "proto.metadatapb.MetadataRequest")
	proto.RegisterType((*MetadataResponse)(nil), "proto.metadatapb.MetadataResponse")
	proto.RegisterType((*Broker)(nil), "proto.metadatapb.Broker")
	proto.RegisterType((*Topic)(nil), "proto.metadatapb.Topic")
	proto.RegisterType((*Partition)(nil), "proto.metadatapb.Partition")
}

func init() {
	proto.RegisterFile("proto/metadatapb/metadata.proto", fileDescriptor_62d81771a13bf91c)
}

var fileDescriptor_62d81771a13bf91c = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xcd, 0x4a, 0xc3, 0x40,
	0x10, 0x26, 0xa6, 0xa9, 0x66, 0x2a, 0x5a, 0xf6, 0x50, 0x17, 0x15, 0x0c, 0x39, 0x48, 0x2e, 0xa6,
	0x50, 0x8f, 0x9e, 0x5a, 0x8b, 0x58, 0x8a, 0x45, 0x16, 0x4f, 0xde, 0xd2, 0x66, 0xc0, 0x60, 0x9b,
	0x5d, 0x77, 0xb7, 0xe2, 0x4b, 0xf9, 0x8e, 0xb2, 0xd3, 0x34, 0xd1, 0xf6, 0xe0, 0x29, 0x33, 0xdf,
	0xdf, 0xcc, 0x84, 0x85, 0x2b, 0xa5, 0xa5, 0x95, 0xfd, 0x15, 0xda, 0x2c, 0xcf, 0x6c, 0xa6, 0xe6,
	0x75, 0x99, 0x12, 0xc3, 0xba, 0xf4, 0x49, 0x1b, 0x41, 0xdc, 0x87, 0xd3, 0xa7, 0xaa, 0x13, 0xf8,
	0xb1, 0x46, 0x63, 0xd9, 0x25, 0x84, 0x56, 0xaa, 0x62, 0x31, 0xcb, 0x56, 0xc8, 0xbd, 0xc8, 0x4b,
	0x42, 0xd1, 0x00, 0xf1, 0x1a, 0xba, 0x8d, 0xc1, 0x28, 0x59, 0x1a, 0x64, 0x03, 0x38, 0x9c, 0x6b,
	0xf9, 0x8e, 0xda, 0x70, 0x2f, 0xf2, 0x93, 0xce, 0x80, 0xa7, 0xbb, 0x83, 0xd2, 0x11, 0x09, 0xc4,
	0x56, 0xc8, 0x6e, 0x20, 0xa0, 0x50, 0x7e, 0x10, 0x79, 0x49, 0x67, 0x70, 0xb6, 0xef, 0x78, 0x71,
	0xb4, 0xd8, 0xa8, 0xe2, 0x47, 0x68, 0x6f, 0x12, 0x58, 0x0f, 0xda, 0xa5, 0xcc, 0x71, 0x32, 0xa6,
	0xdd, 0x02, 0x51, 0x75, 0x8c, 0x41, 0xeb, 0x4d, 0x1a, 0x4b, 0x79, 0xa1, 0xa0, 0xda, 0x61, 0x4a,
	0x6a, 0xcb, 0x7d, 0x52, 0x52, 0x1d, 0x7f, 0x42, 0x40, 0xc9, 0xee, 0x4e, 0xd4, 0x5a, 0xea, 0x7b,
	0x99, 0x63, 0x95, 0xd5, 0x00, 0xce, 0x5a, 0xba, 0x1f, 0x50, 0xc5, 0xb9, 0x9a, 0xdd, 0x01, 0xa8,
	0x4c, 0xdb, 0xc2, 0x16, 0xb2, 0x34, 0xdc, 0xa7, 0x53, 0x2f, 0xf6, 0x17, 0x7f, 0xde, 0x6a, 0xc4,
	0x2f, 0x79, 0xfc, 0xed, 0x41, 0x58, 0x33, 0xff, 0x0c, 0xbf, 0x86, 0x93, 0xda, 0x39, 0x29, 0x73,
	0xfc, 0xa2, 0x35, 0x02, 0xb1, 0x83, 0xb2, 0x73, 0x38, 0x5a, 0x62, 0x96, 0xa3, 0x9e, 0x8c, 0xab,
	0x1b, 0xeb, 0x9e, 0xc5, 0x70, 0xac, 0x51, 0x2d, 0x8b, 0x45, 0x36, 0x93, 0x39, 0x1a, 0xde, 0x8a,
	0xfc, 0x24, 0x10, 0x7f, 0x30, 0xe7, 0x2f, 0x8c, 0xde, 0xf0, 0x01, 0xf1, 0x75, 0x3f, 0xe2, 0xaf,
	0xbd, 0xe1, 0xf4, 0x61, 0x38, 0xed, 0xef, 0x3e, 0xaa, 0x79, 0x9b, 0x90, 0xdb, 0x9f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xa1, 0xcd, 0x4d, 0xf9, 0x6f, 0x02, 0x00, 0x00,
}
