// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/messagepb/message.proto

package messagepb

import (
	commonpb "AKFAK/proto/commonpb"
	recordpb "AKFAK/proto/recordpb"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MessageBatchRequest struct {
	Records              *recordpb.RecordBatch `protobuf:"bytes,1,opt,name=records,proto3" json:"records,omitempty"`
	TopicName            string                `protobuf:"bytes,2,opt,name=topicName,proto3" json:"topicName,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *MessageBatchRequest) Reset()         { *m = MessageBatchRequest{} }
func (m *MessageBatchRequest) String() string { return proto.CompactTextString(m) }
func (*MessageBatchRequest) ProtoMessage()    {}
func (*MessageBatchRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_afea1b987f254e01, []int{0}
}

func (m *MessageBatchRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageBatchRequest.Unmarshal(m, b)
}
func (m *MessageBatchRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageBatchRequest.Marshal(b, m, deterministic)
}
func (m *MessageBatchRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageBatchRequest.Merge(m, src)
}
func (m *MessageBatchRequest) XXX_Size() int {
	return xxx_messageInfo_MessageBatchRequest.Size(m)
}
func (m *MessageBatchRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageBatchRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageBatchRequest proto.InternalMessageInfo

func (m *MessageBatchRequest) GetRecords() *recordpb.RecordBatch {
	if m != nil {
		return m.Records
	}
	return nil
}

func (m *MessageBatchRequest) GetTopicName() string {
	if m != nil {
		return m.TopicName
	}
	return ""
}

type MessageBatchResponse struct {
	Response             *commonpb.Response `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *MessageBatchResponse) Reset()         { *m = MessageBatchResponse{} }
func (m *MessageBatchResponse) String() string { return proto.CompactTextString(m) }
func (*MessageBatchResponse) ProtoMessage()    {}
func (*MessageBatchResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_afea1b987f254e01, []int{1}
}

func (m *MessageBatchResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageBatchResponse.Unmarshal(m, b)
}
func (m *MessageBatchResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageBatchResponse.Marshal(b, m, deterministic)
}
func (m *MessageBatchResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageBatchResponse.Merge(m, src)
}
func (m *MessageBatchResponse) XXX_Size() int {
	return xxx_messageInfo_MessageBatchResponse.Size(m)
}
func (m *MessageBatchResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageBatchResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageBatchResponse proto.InternalMessageInfo

func (m *MessageBatchResponse) GetResponse() *commonpb.Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func init() {
	proto.RegisterType((*MessageBatchRequest)(nil), "proto.messagepb.MessageBatchRequest")
	proto.RegisterType((*MessageBatchResponse)(nil), "proto.messagepb.MessageBatchResponse")
}

func init() {
	proto.RegisterFile("proto/messagepb/message.proto", fileDescriptor_afea1b987f254e01)
}

var fileDescriptor_afea1b987f254e01 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2d, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x2d, 0x48, 0x82, 0xb1, 0xf4, 0xc0, 0xe2,
	0x42, 0xfc, 0x60, 0x4a, 0x0f, 0x2e, 0x2d, 0x25, 0x0d, 0x51, 0x5f, 0x94, 0x9a, 0x9c, 0x5f, 0x94,
	0x52, 0x90, 0x04, 0x65, 0x40, 0x54, 0x4b, 0x41, 0x0d, 0x4b, 0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0x03,
	0x4b, 0x16, 0x17, 0xe4, 0xe7, 0x15, 0x43, 0x0d, 0x53, 0xca, 0xe2, 0x12, 0xf6, 0x85, 0x18, 0xe4,
	0x94, 0x58, 0x92, 0x9c, 0x11, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x22, 0x64, 0xca, 0xc5, 0x0e,
	0x31, 0xa5, 0x58, 0x82, 0x51, 0x81, 0x51, 0x83, 0xdb, 0x48, 0x1a, 0xa2, 0x5e, 0x0f, 0x66, 0x89,
	0x5e, 0x10, 0x98, 0x01, 0xd1, 0x04, 0x53, 0x2b, 0x24, 0xc3, 0xc5, 0x59, 0x92, 0x5f, 0x90, 0x99,
	0xec, 0x97, 0x98, 0x9b, 0x2a, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x19, 0x84, 0x10, 0x50, 0xf2, 0xe1,
	0x12, 0x41, 0xb5, 0x0b, 0xe2, 0x12, 0x21, 0x13, 0x2e, 0x0e, 0x98, 0xab, 0xa0, 0xb6, 0x49, 0x40,
	0x6d, 0x83, 0xb9, 0x5a, 0x0f, 0xa6, 0x36, 0x08, 0xae, 0xd2, 0x49, 0x3c, 0x4a, 0xd4, 0xd1, 0xdb,
	0xcd, 0xd1, 0x5b, 0x1f, 0x2d, 0xb4, 0x92, 0xd8, 0xc0, 0x02, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x2b, 0xce, 0x47, 0x9b, 0x47, 0x01, 0x00, 0x00,
}
